-- Metric views for domain: marketing | Business: Retail | Version: 2 | Generated on: 2026-07-12 14:06:09

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_campaign_performance`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Core campaign effectiveness KPIs measuring spend efficiency, revenue attribution, engagement quality, and conversion outcomes across campaigns, channels, and financial periods. Primary steering dashboard for marketing leadership."
  source: "`vibe_retail_v1`.`marketing`.`campaign_performance`"
  dimensions:
    - name: "campaign_id"
      expr: campaign_id
      comment: "Campaign identifier for grouping performance metrics by individual campaign."
    - name: "channel_id"
      expr: channel_id
      comment: "Marketing channel identifier enabling channel-level performance comparison."
    - name: "financial_period_id"
      expr: financial_period_id
      comment: "Financial period for aligning campaign spend and revenue to accounting periods."
    - name: "reporting_period_type"
      expr: reporting_period_type
      comment: "Granularity of the reporting period (daily, weekly, monthly) for time-series analysis."
    - name: "reporting_period_start_date"
      expr: reporting_period_start_date
      comment: "Start date of the reporting window for trend and period-over-period analysis."
    - name: "reporting_period_end_date"
      expr: reporting_period_end_date
      comment: "End date of the reporting window."
    - name: "performance_status"
      expr: performance_status
      comment: "Current status of the performance record (active, closed, under_review)."
    - name: "attribution_model_id"
      expr: attribution_model_id
      comment: "Attribution model used to assign credit, enabling model-comparison analysis."
    - name: "storefront_id"
      expr: storefront_id
      comment: "Storefront dimension for e-commerce channel performance segmentation."
    - name: "item_hierarchy_id"
      expr: item_hierarchy_id
      comment: "Product hierarchy dimension for category-level campaign performance analysis."
  measures:
    - name: "total_spend_amount"
      expr: SUM(CAST(spend_amount AS DOUBLE))
      comment: "Total marketing spend invested across campaigns. Core budget utilization KPI used by CMO to track investment levels and pacing against budget."
    - name: "total_attributed_revenue"
      expr: SUM(CAST(attributed_revenue_amount AS DOUBLE))
      comment: "Total revenue attributed to marketing campaigns. Directly measures marketing's contribution to top-line revenue — primary ROI input for executive steering."
    - name: "total_impressions_delivered"
      expr: SUM(CAST(impressions_delivered AS DOUBLE))
      comment: "Total ad impressions delivered. Measures campaign reach and media delivery fulfillment against planned impressions."
    - name: "total_clicks"
      expr: SUM(CAST(click_count AS DOUBLE))
      comment: "Total clicks generated by campaigns. Measures audience engagement and intent signal volume."
    - name: "total_conversions"
      expr: SUM(CAST(conversion_count AS DOUBLE))
      comment: "Total conversion events attributed to campaigns. Core demand-generation KPI linking marketing activity to purchase outcomes."
    - name: "total_reach"
      expr: SUM(CAST(reach_count AS DOUBLE))
      comment: "Total unique audience members reached. Measures campaign penetration into target segments."
    - name: "total_email_sends"
      expr: SUM(CAST(email_send_count AS DOUBLE))
      comment: "Total emails sent across campaigns. Volume baseline for email channel efficiency analysis."
    - name: "total_email_opens"
      expr: SUM(CAST(email_open_count AS DOUBLE))
      comment: "Total email opens. Measures email content relevance and subject line effectiveness."
    - name: "total_email_unsubscribes"
      expr: SUM(CAST(email_unsubscribe_count AS DOUBLE))
      comment: "Total email unsubscribes. Elevated unsubscribe rates signal audience fatigue or irrelevant messaging — triggers list hygiene action."
    - name: "total_video_views"
      expr: SUM(CAST(video_view_count AS DOUBLE))
      comment: "Total video views delivered. Measures video content consumption and creative effectiveness."
    - name: "avg_roas"
      expr: AVG(CAST(roas_ratio AS DOUBLE))
      comment: "Average return on ad spend ratio across performance records. Primary efficiency KPI: every dollar of spend generating X dollars of revenue. Drives budget reallocation decisions."
    - name: "avg_conversion_rate_pct"
      expr: AVG(CAST(conversion_rate_percent AS DOUBLE))
      comment: "Average conversion rate percentage. Measures funnel efficiency from impression/click to purchase — key lever for campaign optimization."
    - name: "avg_ctr_pct"
      expr: AVG(CAST(ctr_percent AS DOUBLE))
      comment: "Average click-through rate percentage. Measures creative and targeting relevance — low CTR triggers creative refresh or audience refinement."
    - name: "avg_cpa_amount"
      expr: AVG(CAST(cpa_amount AS DOUBLE))
      comment: "Average cost per acquisition. Measures efficiency of converting spend into customers — compared against customer lifetime value to assess profitability."
    - name: "avg_cpm_amount"
      expr: AVG(CAST(cpm_amount AS DOUBLE))
      comment: "Average cost per thousand impressions. Media buying efficiency benchmark used to compare channel and publisher costs."
    - name: "avg_cpc_amount"
      expr: AVG(CAST(cpc_amount AS DOUBLE))
      comment: "Average cost per click. Measures paid media efficiency — rising CPC signals increased competition or poor quality score."
    - name: "avg_email_open_rate_pct"
      expr: AVG(CAST(email_open_rate_percent AS DOUBLE))
      comment: "Average email open rate percentage. Measures email channel health and audience engagement quality."
    - name: "avg_email_unsubscribe_rate_pct"
      expr: AVG(CAST(email_unsubscribe_rate_percent AS DOUBLE))
      comment: "Average email unsubscribe rate. Threshold breaches trigger immediate campaign review to protect deliverability and list health."
    - name: "avg_video_completion_rate_pct"
      expr: AVG(CAST(video_completion_rate_percent AS DOUBLE))
      comment: "Average video completion rate percentage. Measures video creative quality — low completion rates indicate poor hook or irrelevant content."
    - name: "avg_engagement_rate_pct"
      expr: AVG(CAST(engagement_rate_percent AS DOUBLE))
      comment: "Average engagement rate across campaigns. Composite measure of audience interaction quality used to rank campaign creative effectiveness."
    - name: "campaign_performance_record_count"
      expr: COUNT(1)
      comment: "Count of campaign performance measurement records. Used to assess reporting coverage and data completeness."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_campaign`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Campaign portfolio KPIs measuring budget utilization, spend pacing, campaign mix, and pipeline of active campaigns. Used by marketing leadership to manage the campaign portfolio and investment allocation."
  source: "`vibe_retail_v1`.`marketing`.`campaign`"
  dimensions:
    - name: "campaign_status"
      expr: campaign_status
      comment: "Current lifecycle status of the campaign (planned, active, paused, completed, cancelled)."
    - name: "campaign_type"
      expr: campaign_type
      comment: "Type of campaign (acquisition, retention, brand, promotional) for portfolio mix analysis."
    - name: "channel_id"
      expr: channel_id
      comment: "Primary channel for the campaign enabling channel investment analysis."
    - name: "marketing_brand_id"
      expr: marketing_brand_id
      comment: "Brand associated with the campaign for brand-level budget and activity tracking."
    - name: "approval_status"
      expr: approval_status
      comment: "Approval workflow status — campaigns pending approval represent blocked spend."
    - name: "planned_start_date"
      expr: planned_start_date
      comment: "Planned campaign start date for timeline and pipeline analysis."
    - name: "planned_end_date"
      expr: planned_end_date
      comment: "Planned campaign end date for duration and scheduling analysis."
    - name: "is_omnichannel"
      expr: is_omnichannel
      comment: "Flag indicating whether the campaign spans multiple channels — omnichannel campaigns typically have higher complexity and budget."
    - name: "geographic_scope"
      expr: geographic_scope
      comment: "Geographic scope of the campaign for regional investment analysis."
    - name: "campaign_id"
      expr: campaign_id
      comment: "Campaign identifier for drill-down analysis."
  measures:
    - name: "total_budget_amount"
      expr: SUM(CAST(budget_amount AS DOUBLE))
      comment: "Total approved campaign budget. Primary investment planning KPI — CMO uses this to track total marketing investment commitment."
    - name: "total_actual_spend"
      expr: SUM(CAST(actual_spend_amount AS DOUBLE))
      comment: "Total actual spend incurred across campaigns. Compared against budget to measure pacing and identify over/under-spend."
    - name: "total_target_revenue_goal"
      expr: SUM(CAST(target_revenue_goal AS DOUBLE))
      comment: "Sum of revenue goals set for all campaigns. Measures the aggregate revenue ambition of the marketing portfolio."
    - name: "total_target_audience_size"
      expr: SUM(CAST(target_audience_size AS DOUBLE))
      comment: "Total targeted audience size across campaigns. Measures the intended reach of the marketing portfolio."
    - name: "avg_budget_per_campaign"
      expr: AVG(CAST(budget_amount AS DOUBLE))
      comment: "Average budget allocated per campaign. Benchmarks investment levels and identifies outlier campaigns requiring scrutiny."
    - name: "avg_actual_spend_per_campaign"
      expr: AVG(CAST(actual_spend_amount AS DOUBLE))
      comment: "Average actual spend per campaign. Used alongside average budget to assess typical spend efficiency."
    - name: "active_campaign_count"
      expr: COUNT(CASE WHEN campaign_status = 'active' THEN 1 END)
      comment: "Number of currently active campaigns. Measures marketing execution capacity and pipeline activity."
    - name: "total_campaign_count"
      expr: COUNT(1)
      comment: "Total number of campaigns in the portfolio. Portfolio size baseline for investment density analysis."
    - name: "omnichannel_campaign_count"
      expr: COUNT(CASE WHEN is_omnichannel = TRUE THEN 1 END)
      comment: "Number of omnichannel campaigns. Measures the organization's cross-channel marketing maturity."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_conversion_event`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Conversion funnel KPIs measuring revenue attribution, conversion volume, new customer acquisition, and omnichannel conversion patterns. Core demand-generation performance layer for marketing and e-commerce leadership."
  source: "`vibe_retail_v1`.`marketing`.`conversion_event`"
  dimensions:
    - name: "conversion_type"
      expr: conversion_type
      comment: "Type of conversion event (purchase, lead, sign-up, app_install) for funnel stage analysis."
    - name: "conversion_status"
      expr: conversion_status
      comment: "Status of the conversion event for data quality and validity filtering."
    - name: "campaign_id"
      expr: campaign_id
      comment: "Campaign that drove the conversion for campaign-level attribution analysis."
    - name: "attributed_channel"
      expr: attributed_channel
      comment: "Channel credited with the conversion for channel attribution reporting."
    - name: "device_type"
      expr: device_type
      comment: "Device type (mobile, desktop, tablet) for cross-device conversion analysis."
    - name: "is_new_customer"
      expr: is_new_customer
      comment: "Flag indicating whether the converting customer is new — critical for acquisition vs. retention analysis."
    - name: "is_omnichannel"
      expr: is_omnichannel
      comment: "Flag indicating whether the conversion involved multiple channels — measures omnichannel journey effectiveness."
    - name: "geographic_country_code"
      expr: geographic_country_code
      comment: "Country of the conversion event for geographic performance analysis."
    - name: "geographic_region"
      expr: geographic_region
      comment: "Region of the conversion event for regional marketing effectiveness."
    - name: "conversion_timestamp"
      expr: DATE_TRUNC('day', conversion_timestamp)
      comment: "Conversion date (day granularity) for daily trend analysis."
    - name: "utm_source"
      expr: utm_source
      comment: "UTM source parameter for traffic source attribution analysis."
    - name: "utm_medium"
      expr: utm_medium
      comment: "UTM medium parameter for paid vs. organic channel analysis."
  measures:
    - name: "total_attributed_revenue"
      expr: SUM(CAST(attributed_revenue_amount AS DOUBLE))
      comment: "Total revenue attributed to marketing-driven conversion events. Primary revenue contribution KPI for marketing ROI measurement."
    - name: "total_conversion_value"
      expr: SUM(CAST(conversion_value AS DOUBLE))
      comment: "Total value of all conversion events including non-revenue conversions (leads, sign-ups). Broader value measure than revenue alone."
    - name: "total_conversion_count"
      expr: COUNT(1)
      comment: "Total number of conversion events. Volume baseline for conversion rate and cost-per-conversion calculations."
    - name: "new_customer_conversion_count"
      expr: COUNT(CASE WHEN is_new_customer = TRUE THEN 1 END)
      comment: "Number of conversions from new customers. Measures customer acquisition effectiveness — key growth metric for leadership."
    - name: "omnichannel_conversion_count"
      expr: COUNT(CASE WHEN is_omnichannel = TRUE THEN 1 END)
      comment: "Number of conversions involving multiple channels. Measures the value of omnichannel customer journeys."
    - name: "avg_attributed_revenue_per_conversion"
      expr: AVG(CAST(attributed_revenue_amount AS DOUBLE))
      comment: "Average revenue per conversion event. Measures conversion quality — declining average signals lower-value customer acquisition."
    - name: "avg_time_to_conversion_hours"
      expr: AVG(CAST(time_to_conversion_hours AS DOUBLE))
      comment: "Average hours from first touchpoint to conversion. Measures sales cycle length — longer cycles may indicate friction in the purchase journey."
    - name: "distinct_converting_profiles"
      expr: COUNT(DISTINCT profile_id)
      comment: "Number of distinct customer profiles that converted. Measures unique customer acquisition volume, deduplicating repeat converters."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_media_buy`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Paid media investment and delivery KPIs measuring spend efficiency, impression delivery, click performance, and conversion outcomes at the media buy level. Used by media planning teams and CMO to optimize paid media allocation."
  source: "`vibe_retail_v1`.`marketing`.`media_buy`"
  dimensions:
    - name: "campaign_id"
      expr: campaign_id
      comment: "Campaign associated with the media buy for campaign-level media investment analysis."
    - name: "channel_id"
      expr: channel_id
      comment: "Channel of the media buy for channel-level spend and performance comparison."
    - name: "buy_type"
      expr: buy_type
      comment: "Type of media buy (direct, programmatic, sponsorship) for buy-type efficiency analysis."
    - name: "buy_status"
      expr: buy_status
      comment: "Current status of the media buy (booked, live, completed, cancelled)."
    - name: "is_programmatic"
      expr: is_programmatic
      comment: "Flag indicating programmatic vs. direct media buying — enables efficiency comparison between buying methods."
    - name: "placement_type"
      expr: placement_type
      comment: "Ad placement type (banner, video, native, search) for placement-level performance analysis."
    - name: "marketing_brand_id"
      expr: marketing_brand_id
      comment: "Brand associated with the media buy for brand-level media investment tracking."
    - name: "publisher_id"
      expr: publisher_id
      comment: "Publisher running the media buy for publisher performance and cost benchmarking."
    - name: "flight_start_date"
      expr: flight_start_date
      comment: "Media flight start date for scheduling and pacing analysis."
    - name: "flight_end_date"
      expr: flight_end_date
      comment: "Media flight end date for campaign timeline management."
  measures:
    - name: "total_planned_spend"
      expr: SUM(CAST(planned_spend_amount AS DOUBLE))
      comment: "Total planned media spend across all buys. Baseline for budget commitment and pacing analysis."
    - name: "total_actual_spend"
      expr: SUM(CAST(actual_spend_amount AS DOUBLE))
      comment: "Total actual media spend incurred. Compared against planned spend to measure delivery and pacing accuracy."
    - name: "total_planned_impressions"
      expr: SUM(CAST(planned_impressions AS DOUBLE))
      comment: "Total impressions planned across media buys. Measures intended reach commitment."
    - name: "total_delivered_impressions"
      expr: SUM(CAST(delivered_impressions AS DOUBLE))
      comment: "Total impressions actually delivered. Measures media delivery fulfillment — shortfalls trigger make-good negotiations."
    - name: "total_clicks"
      expr: SUM(CAST(click_count AS DOUBLE))
      comment: "Total clicks generated from media buys. Measures audience engagement and intent volume from paid media."
    - name: "total_conversions"
      expr: SUM(CAST(conversion_count AS DOUBLE))
      comment: "Total conversions attributed to media buys. Measures paid media contribution to demand generation."
    - name: "avg_contracted_rate"
      expr: AVG(CAST(contracted_rate AS DOUBLE))
      comment: "Average contracted media rate. Benchmarks negotiated pricing against market rates for procurement efficiency."
    - name: "avg_viewability_rate"
      expr: AVG(CAST(viewability_rate AS DOUBLE))
      comment: "Average ad viewability rate. Measures media quality — low viewability means spend is wasted on unseen impressions."
    - name: "media_buy_count"
      expr: COUNT(1)
      comment: "Total number of media buys. Measures media plan execution complexity and vendor diversification."
    - name: "programmatic_buy_count"
      expr: COUNT(CASE WHEN is_programmatic = TRUE THEN 1 END)
      comment: "Number of programmatic media buys. Measures automation adoption in media buying — programmatic typically delivers better targeting efficiency."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_email_send`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Email channel performance KPIs measuring delivery, engagement, and list health at the send level. Used by CRM and email marketing teams to optimize email program effectiveness and maintain deliverability."
  source: "`vibe_retail_v1`.`marketing`.`email_send`"
  dimensions:
    - name: "campaign_id"
      expr: campaign_id
      comment: "Campaign associated with the email send for campaign-level email performance analysis."
    - name: "email_template_id"
      expr: email_template_id
      comment: "Email template used — enables template performance comparison to identify best-performing creative."
    - name: "audience_segment_id"
      expr: audience_segment_id
      comment: "Audience segment targeted by the send for segment-level engagement analysis."
    - name: "send_type"
      expr: send_type
      comment: "Type of email send (promotional, transactional, triggered, newsletter) for program-type analysis."
    - name: "send_status"
      expr: send_status
      comment: "Current status of the email send (scheduled, in_progress, completed, failed)."
    - name: "is_test_send"
      expr: is_test_send
      comment: "Flag to exclude test sends from production performance analysis."
    - name: "storefront_id"
      expr: storefront_id
      comment: "Storefront associated with the send for channel-specific email performance."
    - name: "scheduled_send_timestamp"
      expr: DATE_TRUNC('week', scheduled_send_timestamp)
      comment: "Week of scheduled send for weekly email volume and performance trending."
    - name: "utm_source"
      expr: utm_source
      comment: "UTM source for email traffic attribution analysis."
  measures:
    - name: "total_email_send_records"
      expr: COUNT(1)
      comment: "Total number of email send jobs executed. Measures email program activity volume."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_sms_send`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "SMS channel performance KPIs measuring delivery costs and send volume. Used by CRM teams to manage SMS program investment and compliance."
  source: "`vibe_retail_v1`.`marketing`.`sms_send`"
  dimensions:
    - name: "campaign_id"
      expr: campaign_id
      comment: "Campaign associated with the SMS send for campaign-level SMS performance analysis."
    - name: "audience_segment_id"
      expr: audience_segment_id
      comment: "Audience segment targeted for segment-level SMS engagement analysis."
    - name: "send_type"
      expr: send_type
      comment: "Type of SMS send (promotional, transactional, alert) for program-type analysis."
    - name: "send_status"
      expr: send_status
      comment: "Current status of the SMS send for operational monitoring."
    - name: "is_mms"
      expr: is_mms
      comment: "Flag indicating MMS (multimedia) vs. plain SMS — MMS has higher cost and engagement potential."
    - name: "geographic_scope"
      expr: geographic_scope
      comment: "Geographic scope of the SMS send for regional compliance and cost analysis."
    - name: "storefront_id"
      expr: storefront_id
      comment: "Storefront associated with the SMS send for channel attribution."
    - name: "scheduled_send_timestamp"
      expr: DATE_TRUNC('week', scheduled_send_timestamp)
      comment: "Week of scheduled send for weekly SMS volume trending."
  measures:
    - name: "total_sms_send_cost"
      expr: SUM(CAST(send_cost_amount AS DOUBLE))
      comment: "Total cost of SMS sends. Primary SMS channel investment KPI — rising costs without proportional conversion growth triggers channel review."
    - name: "avg_sms_send_cost"
      expr: AVG(CAST(send_cost_amount AS DOUBLE))
      comment: "Average cost per SMS send job. Benchmarks SMS platform efficiency and carrier routing costs."
    - name: "total_sms_send_count"
      expr: COUNT(1)
      comment: "Total number of SMS send jobs. Measures SMS program activity volume and cadence."
    - name: "mms_send_count"
      expr: COUNT(CASE WHEN is_mms = TRUE THEN 1 END)
      comment: "Number of MMS sends. Measures multimedia messaging adoption — MMS typically has higher engagement but higher cost."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_push_notification_send`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Push notification channel KPIs measuring delivery, open rates, and engagement for mobile marketing. Used by digital marketing teams to optimize push notification strategy and reduce notification fatigue."
  source: "`vibe_retail_v1`.`marketing`.`push_notification_send`"
  dimensions:
    - name: "campaign_id"
      expr: campaign_id
      comment: "Campaign associated with the push send for campaign-level push performance analysis."
    - name: "audience_segment_id"
      expr: audience_segment_id
      comment: "Audience segment targeted for segment-level push engagement analysis."
    - name: "send_type"
      expr: send_type
      comment: "Type of push notification (promotional, transactional, alert, re-engagement)."
    - name: "send_status"
      expr: send_status
      comment: "Current status of the push send for operational monitoring."
    - name: "platform"
      expr: platform
      comment: "Mobile platform (iOS, Android) for platform-specific performance analysis."
    - name: "is_silent_notification"
      expr: is_silent_notification
      comment: "Flag for silent vs. visible notifications — silent notifications have different engagement patterns."
    - name: "personalization_applied"
      expr: personalization_applied
      comment: "Flag indicating whether personalization was applied — measures personalization impact on engagement."
    - name: "storefront_id"
      expr: storefront_id
      comment: "Storefront associated with the push send for channel attribution."
    - name: "scheduled_send_timestamp"
      expr: DATE_TRUNC('week', scheduled_send_timestamp)
      comment: "Week of scheduled send for weekly push volume and performance trending."
  measures:
    - name: "total_push_delivered"
      expr: SUM(CAST(delivered_count AS DOUBLE))
      comment: "Total push notifications successfully delivered. Measures delivery infrastructure reliability and reach."
    - name: "total_push_opened"
      expr: SUM(CAST(opened_count AS DOUBLE))
      comment: "Total push notifications opened by recipients. Primary engagement KPI for push channel effectiveness."
    - name: "total_push_dismissed"
      expr: SUM(CAST(dismissed_count AS DOUBLE))
      comment: "Total push notifications dismissed without opening. High dismissal rates signal notification fatigue or irrelevant content."
    - name: "total_push_failed"
      expr: SUM(CAST(failed_count AS DOUBLE))
      comment: "Total push notifications that failed to deliver. Measures platform reliability and token health issues."
    - name: "total_push_send_cost"
      expr: SUM(CAST(send_cost_amount AS DOUBLE))
      comment: "Total cost of push notification sends. Measures push channel investment for ROI analysis."
    - name: "total_target_recipients"
      expr: SUM(CAST(target_recipient_count AS DOUBLE))
      comment: "Total intended recipients across push sends. Measures push program reach ambition."
    - name: "total_push_send_count"
      expr: COUNT(1)
      comment: "Total number of push send jobs executed. Measures push program activity volume."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_influencer_engagement`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Influencer marketing performance KPIs measuring reach, engagement, and investment efficiency across influencer partnerships. Used by brand and social teams to evaluate influencer ROI and optimize partnership strategy."
  source: "`vibe_retail_v1`.`marketing`.`influencer_engagement`"
  dimensions:
    - name: "campaign_id"
      expr: campaign_id
      comment: "Campaign associated with the influencer engagement for campaign-level influencer performance."
    - name: "influencer_id"
      expr: influencer_id
      comment: "Influencer identifier for individual influencer performance benchmarking."
    - name: "engagement_type"
      expr: engagement_type
      comment: "Type of influencer engagement (sponsored post, story, video, event) for format-level analysis."
    - name: "engagement_status"
      expr: engagement_status
      comment: "Current status of the engagement (contracted, in_progress, completed, cancelled)."
    - name: "platform_name"
      expr: platform_name
      comment: "Social platform of the engagement for platform-level influencer performance comparison."
    - name: "compensation_type"
      expr: compensation_type
      comment: "Compensation model (flat_fee, commission, gifting, hybrid) for cost structure analysis."
    - name: "approval_status"
      expr: approval_status
      comment: "Content approval status for compliance and workflow monitoring."
    - name: "content_publish_date"
      expr: content_publish_date
      comment: "Date content was published for temporal performance analysis."
    - name: "ftc_disclosure_compliant_flag"
      expr: ftc_disclosure_compliant_flag
      comment: "FTC disclosure compliance flag — non-compliant engagements represent regulatory risk."
  measures:
    - name: "total_flat_fee_spend"
      expr: SUM(CAST(flat_fee_amount AS DOUBLE))
      comment: "Total flat fee spend on influencer engagements. Primary influencer investment KPI for budget management."
    - name: "total_gifting_value"
      expr: SUM(CAST(gifting_value_amount AS DOUBLE))
      comment: "Total value of product gifting to influencers. Measures non-cash influencer investment for total cost-of-partnership analysis."
    - name: "total_actual_impressions"
      expr: SUM(CAST(actual_impressions_count AS DOUBLE))
      comment: "Total impressions delivered through influencer content. Measures influencer reach contribution to brand awareness."
    - name: "total_actual_reach"
      expr: SUM(CAST(actual_reach_count AS DOUBLE))
      comment: "Total unique audience reached through influencer content. Measures net new audience exposure."
    - name: "total_actual_engagements"
      expr: SUM(CAST(actual_engagement_count AS DOUBLE))
      comment: "Total engagement actions (likes, comments, shares, saves) on influencer content. Measures content resonance and audience quality."
    - name: "total_actual_clicks"
      expr: SUM(CAST(actual_clicks_count AS DOUBLE))
      comment: "Total clicks driven by influencer content. Measures influencer contribution to traffic and conversion funnel."
    - name: "total_actual_video_views"
      expr: SUM(CAST(actual_video_views_count AS DOUBLE))
      comment: "Total video views on influencer content. Measures video content consumption from influencer partnerships."
    - name: "avg_commission_rate_pct"
      expr: AVG(CAST(commission_rate_percent AS DOUBLE))
      comment: "Average commission rate across influencer engagements. Benchmarks performance-based compensation levels."
    - name: "influencer_engagement_count"
      expr: COUNT(1)
      comment: "Total number of influencer engagements. Measures influencer program scale and partnership diversification."
    - name: "non_compliant_disclosure_count"
      expr: COUNT(CASE WHEN ftc_disclosure_compliant_flag = FALSE THEN 1 END)
      comment: "Number of influencer engagements without compliant FTC disclosure. Regulatory risk KPI — any non-zero value triggers immediate remediation."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_audience_segment`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Audience segment quality and reach KPIs measuring segment size, confidence, and engagement potential. Used by marketing analytics teams to evaluate segment health and prioritize activation."
  source: "`vibe_retail_v1`.`marketing`.`audience_segment`"
  dimensions:
    - name: "segment_type"
      expr: segment_type
      comment: "Type of audience segment (behavioral, demographic, lookalike, RFM) for segment strategy analysis."
    - name: "segment_status"
      expr: segment_status
      comment: "Current status of the segment (active, inactive, draft, archived)."
    - name: "activation_status"
      expr: activation_status
      comment: "Activation status of the segment across channels."
    - name: "creation_method"
      expr: creation_method
      comment: "Method used to create the segment (rule-based, ML model, manual) for methodology analysis."
    - name: "consent_required_flag"
      expr: consent_required_flag
      comment: "Flag indicating whether consent is required for activation — consent-gated segments have activation constraints."
    - name: "exclusion_flag"
      expr: exclusion_flag
      comment: "Flag indicating suppression/exclusion segments vs. targeting segments."
    - name: "effective_start_date"
      expr: effective_start_date
      comment: "Date the segment became effective for temporal segment lifecycle analysis."
    - name: "owning_team"
      expr: owning_team
      comment: "Team owning the segment for governance and accountability analysis."
  measures:
    - name: "total_estimated_reach"
      expr: SUM(CAST(estimated_reach AS DOUBLE))
      comment: "Total estimated reach across all active segments. Measures the addressable audience available for marketing activation."
    - name: "total_actual_reach"
      expr: SUM(CAST(actual_reach AS DOUBLE))
      comment: "Total actual reach achieved across segments. Compared against estimated reach to measure segment accuracy."
    - name: "avg_confidence_score"
      expr: AVG(CAST(confidence_score AS DOUBLE))
      comment: "Average segment confidence score. Measures data quality and model accuracy — low confidence scores indicate segments needing refresh."
    - name: "avg_average_aov"
      expr: AVG(CAST(average_aov AS DOUBLE))
      comment: "Average order value across segments. Identifies high-value segments for premium campaign investment."
    - name: "avg_average_cltv"
      expr: AVG(CAST(average_cltv AS DOUBLE))
      comment: "Average customer lifetime value across segments. Primary segment value KPI for investment prioritization."
    - name: "avg_purchase_frequency"
      expr: AVG(CAST(average_purchase_frequency AS DOUBLE))
      comment: "Average purchase frequency across segments. Identifies high-frequency segments for loyalty and retention investment."
    - name: "active_segment_count"
      expr: COUNT(CASE WHEN segment_status = 'active' THEN 1 END)
      comment: "Number of active audience segments. Measures the breadth of addressable audience strategy."
    - name: "total_segment_count"
      expr: COUNT(1)
      comment: "Total number of audience segments in the portfolio. Measures segmentation strategy complexity."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_budget`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Marketing budget management KPIs measuring allocation, utilization, and channel investment mix. Used by marketing finance and CMO to govern budget health, prevent overspend, and optimize channel investment allocation."
  source: "`vibe_retail_v1`.`marketing`.`marketing_budget`"
  dimensions:
    - name: "budget_status"
      expr: budget_status
      comment: "Current status of the budget (draft, approved, active, closed) for budget lifecycle management."
    - name: "approval_status"
      expr: approval_status
      comment: "Approval workflow status — unapproved budgets represent uncommitted spend."
    - name: "marketing_brand_id"
      expr: marketing_brand_id
      comment: "Brand associated with the budget for brand-level investment analysis."
    - name: "cost_center_id"
      expr: cost_center_id
      comment: "Cost center for financial accountability and P&L alignment."
    - name: "fiscal_year"
      expr: fiscal_year
      comment: "Fiscal year of the budget for annual investment planning and year-over-year comparison."
    - name: "fiscal_period"
      expr: fiscal_period
      comment: "Fiscal period for in-period budget pacing and variance analysis."
    - name: "geographic_scope"
      expr: geographic_scope
      comment: "Geographic scope of the budget for regional investment analysis."
    - name: "start_date"
      expr: start_date
      comment: "Budget period start date for timeline analysis."
  measures:
    - name: "total_actual_spend_to_date"
      expr: SUM(CAST(actual_spend_to_date AS DOUBLE))
      comment: "Total actual spend incurred to date. Compared against approved budget to measure pacing and identify risk of over/under-spend."
    - name: "total_committed_spend"
      expr: SUM(CAST(committed_spend AS DOUBLE))
      comment: "Total committed (contracted but not yet invoiced) spend. Measures future spend obligations for cash flow planning."
    - name: "total_remaining_budget"
      expr: SUM(CAST(remaining_budget AS DOUBLE))
      comment: "Total remaining unspent budget. Measures available investment capacity — large remaining budgets late in period trigger acceleration decisions."
    - name: "total_digital_channel_budget"
      expr: SUM(CAST(digital_channel_budget AS DOUBLE))
      comment: "Total budget allocated to digital channels. Measures digital investment share for channel mix strategy analysis."
    - name: "total_social_media_budget"
      expr: SUM(CAST(social_media_budget AS DOUBLE))
      comment: "Total budget allocated to social media. Measures social investment level for platform strategy decisions."
    - name: "total_influencer_marketing_budget"
      expr: SUM(CAST(influencer_marketing_budget AS DOUBLE))
      comment: "Total budget allocated to influencer marketing. Measures influencer investment scale for partnership strategy."
    - name: "total_email_marketing_budget"
      expr: SUM(CAST(email_marketing_budget AS DOUBLE))
      comment: "Total budget allocated to email marketing. Measures CRM channel investment level."
    - name: "avg_utilization_percentage"
      expr: AVG(CAST(utilization_percentage AS DOUBLE))
      comment: "Average budget utilization percentage. Measures spend efficiency — consistently low utilization indicates planning inaccuracy or execution gaps."
    - name: "avg_target_roi_percentage"
      expr: AVG(CAST(target_roi_percentage AS DOUBLE))
      comment: "Average target ROI percentage set for budgets. Benchmarks investment return expectations across the portfolio."
    - name: "budget_count"
      expr: COUNT(1)
      comment: "Total number of marketing budget records. Measures budget management complexity."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_ab_test_campaign`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "A/B test performance KPIs measuring test outcomes, statistical significance, and lift across marketing experiments. Used by marketing analytics and optimization teams to validate campaign hypotheses and drive evidence-based decisions."
  source: "`vibe_retail_v1`.`marketing`.`campaign`"
  dimensions:
    - name: "campaign_id"
      expr: campaign_id
      comment: "Campaign associated with the A/B test for campaign-level experimentation analysis."
    - name: "approval_status"
      expr: approval_status
      comment: "Approval status of the test for governance tracking."
    - name: "channel_id"
      expr: channel_id
      comment: "Channel where the test was executed for channel-level experimentation analysis."
  measures:
    - name: "total_test_count"
      expr: COUNT(1)
      comment: "Total number of A/B tests. Measures overall experimentation program scale."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_attribution_touchpoint`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Customer journey and attribution KPIs measuring touchpoint volume, conversion contribution, and channel influence across the purchase path. Used by marketing analytics to optimize channel mix and attribution model accuracy."
  source: "`vibe_retail_v1`.`marketing`.`attribution_touchpoint`"
  dimensions:
    - name: "campaign_id"
      expr: campaign_id
      comment: "Campaign associated with the touchpoint for campaign-level journey analysis."
    - name: "channel_type"
      expr: channel_type
      comment: "Channel type of the touchpoint for channel influence analysis across the customer journey."
    - name: "touchpoint_type"
      expr: touchpoint_type
      comment: "Type of touchpoint (impression, click, email_open, site_visit) for journey stage analysis."
    - name: "conversion_event_flag"
      expr: conversion_event_flag
      comment: "Flag indicating whether this touchpoint resulted in a conversion — enables conversion touchpoint analysis."
    - name: "is_view_through"
      expr: is_view_through
      comment: "Flag for view-through vs. click-through touchpoints — measures passive vs. active engagement contribution."
    - name: "device_type"
      expr: device_type
      comment: "Device type for cross-device journey analysis."
    - name: "geographic_country_code"
      expr: geographic_country_code
      comment: "Country of the touchpoint for geographic attribution analysis."
    - name: "attribution_model_id"
      expr: attribution_model_id
      comment: "Attribution model applied — enables model comparison analysis."
    - name: "touchpoint_timestamp"
      expr: DATE_TRUNC('day', touchpoint_timestamp)
      comment: "Day of touchpoint for daily journey volume trending."
    - name: "utm_source"
      expr: utm_source
      comment: "UTM source for traffic source attribution analysis."
    - name: "utm_medium"
      expr: utm_medium
      comment: "UTM medium for paid vs. organic attribution analysis."
  measures:
    - name: "total_conversion_revenue"
      expr: SUM(CAST(conversion_revenue_amount AS DOUBLE))
      comment: "Total revenue from converting touchpoints. Measures the revenue value of touchpoints that directly drove conversions."
    - name: "total_touchpoint_cost"
      expr: SUM(CAST(cost_per_touchpoint AS DOUBLE))
      comment: "Total cost of all touchpoints. Measures total investment in customer journey interactions for cost-per-journey analysis."
    - name: "total_touchpoint_count"
      expr: COUNT(1)
      comment: "Total number of touchpoints recorded. Measures customer journey volume and marketing interaction density."
    - name: "converting_touchpoint_count"
      expr: COUNT(CASE WHEN conversion_event_flag = TRUE THEN 1 END)
      comment: "Number of touchpoints that resulted in a conversion. Measures conversion touchpoint volume for attribution analysis."
    - name: "distinct_converting_profiles"
      expr: COUNT(DISTINCT CASE WHEN conversion_event_flag = TRUE THEN profile_id END)
      comment: "Number of distinct customer profiles that converted. Measures unique customer acquisition from touchpoint interactions."
    - name: "avg_time_to_conversion_hours"
      expr: AVG(CAST(time_to_conversion_hours AS DOUBLE))
      comment: "Average time from touchpoint to conversion in hours. Measures purchase journey length — longer journeys may indicate friction or consideration-heavy categories."
    - name: "avg_cost_per_touchpoint"
      expr: AVG(CAST(cost_per_touchpoint AS DOUBLE))
      comment: "Average cost per touchpoint. Benchmarks channel efficiency — high cost-per-touchpoint channels need conversion rate justification."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_social_post`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Social media performance KPIs measuring reach, engagement, and content effectiveness across platforms. Used by social media and brand teams to optimize content strategy and measure organic social ROI."
  source: "`vibe_retail_v1`.`marketing`.`social_post`"
  dimensions:
    - name: "campaign_id"
      expr: campaign_id
      comment: "Campaign associated with the social post for campaign-level social performance analysis."
    - name: "platform"
      expr: platform
      comment: "Social media platform for platform-level performance comparison and investment allocation."
    - name: "post_type"
      expr: post_type
      comment: "Type of social post (image, video, carousel, story, reel) for content format performance analysis."
    - name: "post_status"
      expr: post_status
      comment: "Current status of the post (scheduled, published, archived)."
    - name: "marketing_brand_id"
      expr: marketing_brand_id
      comment: "Brand associated with the post for brand-level social performance analysis."
    - name: "is_boosted"
      expr: is_boosted
      comment: "Flag indicating whether the post was boosted with paid spend — enables organic vs. paid social comparison."
    - name: "actual_publish_timestamp"
      expr: DATE_TRUNC('week', actual_publish_timestamp)
      comment: "Week of publication for weekly social performance trending."
    - name: "target_country_codes"
      expr: target_country_codes
      comment: "Target countries for geographic social performance analysis."
  measures:
    - name: "total_impressions"
      expr: SUM(CAST(impressions AS DOUBLE))
      comment: "Total social media impressions. Measures brand visibility and content distribution scale."
    - name: "total_reach"
      expr: SUM(CAST(reach AS DOUBLE))
      comment: "Total unique users reached by social content. Measures net audience exposure beyond impression frequency."
    - name: "total_likes"
      expr: SUM(CAST(likes AS DOUBLE))
      comment: "Total likes across social posts. Measures positive audience sentiment and content resonance."
    - name: "total_comments"
      expr: SUM(CAST(comments AS DOUBLE))
      comment: "Total comments on social posts. Measures deep engagement and community interaction quality."
    - name: "total_shares"
      expr: SUM(CAST(shares AS DOUBLE))
      comment: "Total shares of social posts. Measures organic amplification — shares extend reach beyond paid distribution."
    - name: "total_link_clicks"
      expr: SUM(CAST(link_clicks AS DOUBLE))
      comment: "Total link clicks from social posts. Measures social-to-site traffic contribution for conversion funnel analysis."
    - name: "total_video_views"
      expr: SUM(CAST(video_views AS DOUBLE))
      comment: "Total video views on social posts. Measures video content consumption and creative effectiveness."
    - name: "total_boost_spend"
      expr: SUM(CAST(boost_budget_amount AS DOUBLE))
      comment: "Total paid boost spend on social posts. Measures paid social amplification investment."
    - name: "avg_engagement_rate"
      expr: AVG(CAST(engagement_rate AS DOUBLE))
      comment: "Average engagement rate across social posts. Primary social content quality KPI — measures audience interaction relative to reach."
    - name: "avg_sentiment_score"
      expr: AVG(CAST(sentiment_score AS DOUBLE))
      comment: "Average sentiment score of social posts. Measures brand perception health — declining sentiment triggers content strategy review."
    - name: "total_post_count"
      expr: COUNT(1)
      comment: "Total number of social posts published. Measures content production volume and publishing cadence."
    - name: "boosted_post_count"
      expr: COUNT(CASE WHEN is_boosted = TRUE THEN 1 END)
      comment: "Number of boosted posts. Measures paid amplification strategy scale."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_automation_flow`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Marketing automation program KPIs measuring enrollment volume, goal achievement, and flow effectiveness. Used by CRM and lifecycle marketing teams to optimize automated customer journeys."
  source: "`vibe_retail_v1`.`marketing`.`automation_flow`"
  dimensions:
    - name: "campaign_id"
      expr: campaign_id
      comment: "Campaign associated with the automation flow for campaign-level automation analysis."
    - name: "flow_type"
      expr: flow_type
      comment: "Type of automation flow (welcome, abandoned_cart, re-engagement, post-purchase) for program-type analysis."
    - name: "flow_status"
      expr: flow_status
      comment: "Current status of the flow (active, paused, draft, archived)."
    - name: "primary_channel"
      expr: primary_channel
      comment: "Primary channel of the automation flow for channel-level automation performance."
    - name: "consent_required_flag"
      expr: consent_required_flag
      comment: "Flag indicating consent requirement — consent-gated flows have activation constraints."
    - name: "activation_date"
      expr: activation_date
      comment: "Date the flow was activated for lifecycle and cohort analysis."
    - name: "business_unit"
      expr: business_unit
      comment: "Business unit owning the flow for organizational accountability."
  measures:
    - name: "total_enrolled_count"
      expr: SUM(CAST(total_enrolled_count AS DOUBLE))
      comment: "Total customers enrolled across automation flows. Measures automation program reach and scale."
    - name: "total_active_enrolled_count"
      expr: SUM(CAST(active_enrolled_count AS DOUBLE))
      comment: "Total customers currently active in automation flows. Measures live automation engagement volume."
    - name: "total_completed_count"
      expr: SUM(CAST(completed_count AS DOUBLE))
      comment: "Total customers who completed automation flows. Measures flow completion rate baseline."
    - name: "total_goal_achieved_count"
      expr: SUM(CAST(goal_achieved_count AS DOUBLE))
      comment: "Total customers who achieved the flow goal (purchase, sign-up, etc.). Primary automation effectiveness KPI."
    - name: "avg_goal_achievement_rate"
      expr: ROUND(100.0 * SUM(CAST(goal_achieved_count AS DOUBLE)) / NULLIF(SUM(CAST(total_enrolled_count AS DOUBLE)), 0), 2)
      comment: "Goal achievement rate as a percentage of total enrollments. Measures automation flow conversion effectiveness — primary ROI indicator for lifecycle programs."
    - name: "active_flow_count"
      expr: COUNT(CASE WHEN flow_status = 'active' THEN 1 END)
      comment: "Number of currently active automation flows. Measures the breadth of automated customer journey coverage."
    - name: "total_flow_count"
      expr: COUNT(1)
      comment: "Total number of automation flows. Measures automation program portfolio size."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_segment`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Marketing segment portfolio KPIs measuring segment value, churn risk, and RFM distribution. Used by marketing analytics and CRM teams to prioritize segment investment and identify at-risk customer groups."
  source: "`vibe_retail_v1`.`marketing`.`segment`"
  dimensions:
    - name: "segment_type"
      expr: segment_type
      comment: "Type of segment (RFM, behavioral, demographic, lifecycle) for segment strategy analysis."
    - name: "segment_status"
      expr: segment_status
      comment: "Current status of the segment for active portfolio management."
    - name: "b2b_b2c_indicator"
      expr: b2b_b2c_indicator
      comment: "B2B vs. B2C indicator for business model segmentation analysis."
    - name: "priority_tier"
      expr: priority_tier
      comment: "Priority tier of the segment for investment prioritization."
    - name: "discount_sensitivity"
      expr: discount_sensitivity
      comment: "Discount sensitivity classification for promotional strategy targeting."
    - name: "target_marketing_channel"
      expr: target_marketing_channel
      comment: "Preferred marketing channel for the segment for channel strategy alignment."
    - name: "geographic_scope"
      expr: geographic_scope
      comment: "Geographic scope of the segment for regional marketing analysis."
    - name: "effective_start_date"
      expr: effective_start_date
      comment: "Segment effective start date for lifecycle analysis."
  measures:
    - name: "total_membership_count"
      expr: SUM(CAST(membership_count AS DOUBLE))
      comment: "Total customers across all segments. Measures the addressable customer base covered by segmentation."
    - name: "avg_customer_lifetime_value"
      expr: AVG(CAST(average_cltv AS DOUBLE))
      comment: "Average customer lifetime value across segments. Primary segment value KPI — drives investment prioritization toward highest-value segments."
    - name: "avg_order_value"
      expr: AVG(CAST(average_aov AS DOUBLE))
      comment: "Average order value across segments. Identifies high-AOV segments for premium offer targeting."
    - name: "avg_purchase_frequency"
      expr: AVG(CAST(average_purchase_frequency AS DOUBLE))
      comment: "Average purchase frequency across segments. Identifies high-frequency segments for loyalty investment."
    - name: "avg_churn_risk_score"
      expr: AVG(CAST(churn_risk_score AS DOUBLE))
      comment: "Average churn risk score across segments. Elevated churn risk triggers retention campaign activation."
    - name: "avg_nps_score"
      expr: AVG(CAST(nps_score AS DOUBLE))
      comment: "Average Net Promoter Score across segments. Measures customer satisfaction and advocacy potential by segment."
    - name: "active_segment_count"
      expr: COUNT(CASE WHEN segment_status = 'active' THEN 1 END)
      comment: "Number of active marketing segments. Measures segmentation coverage breadth."
    - name: "total_segment_count"
      expr: COUNT(1)
      comment: "Total number of marketing segments. Measures segmentation portfolio size."
$$;

CREATE OR REPLACE VIEW `vibe_retail_v1`.`_metrics`.`marketing_automation_enrollment`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Marketing automation funnel metrics tracking enrollment progression, conversion rates, and engagement through automated customer journeys"
  source: "`vibe_retail_v1`.`marketing`.`automation_enrollment`"
  dimensions:
    - name: "enrollment_status"
      expr: enrollment_status
      comment: "Current status of the automation enrollment (active, completed, exited, paused)"
    - name: "enrollment_source"
      expr: enrollment_source
      comment: "Source that triggered the enrollment"
    - name: "enrollment_channel"
      expr: enrollment_channel
      comment: "Channel through which enrollment occurred"
    - name: "conversion_flag"
      expr: conversion_flag
      comment: "Flag indicating if enrollment resulted in conversion"
    - name: "consent_status"
      expr: consent_status
      comment: "Consent status of the enrolled profile"
    - name: "suppression_flag"
      expr: suppression_flag
      comment: "Flag indicating if enrollment is suppressed"
    - name: "conversion_currency_code"
      expr: conversion_currency_code
      comment: "Currency code for conversion value"
  measures:
    - name: "total_enrollments"
      expr: COUNT(1)
      comment: "Total number of automation enrollments"
    - name: "total_conversion_value"
      expr: SUM(CAST(conversion_value_amount AS DOUBLE))
      comment: "Total conversion value from automation enrollments"
    - name: "total_messages_sent"
      expr: SUM(CAST(total_messages_sent AS BIGINT))
      comment: "Total messages sent through automation flows"
    - name: "total_messages_opened"
      expr: SUM(CAST(total_messages_opened AS BIGINT))
      comment: "Total messages opened in automation flows"
    - name: "total_messages_clicked"
      expr: SUM(CAST(total_messages_clicked AS BIGINT))
      comment: "Total messages clicked in automation flows"
    - name: "total_steps_completed"
      expr: SUM(CAST(total_steps_completed AS BIGINT))
      comment: "Total automation steps completed across enrollments"
    - name: "conversions"
      expr: SUM(CASE WHEN conversion_flag = TRUE THEN 1 ELSE 0 END)
      comment: "Number of enrollments that converted"
    - name: "active_enrollments"
      expr: SUM(CASE WHEN enrollment_status = 'active' THEN 1 ELSE 0 END)
      comment: "Number of currently active enrollments"
    - name: "unique_profiles_enrolled"
      expr: COUNT(DISTINCT profile_id)
      comment: "Number of unique customer profiles enrolled"
    - name: "unique_automation_flows"
      expr: COUNT(DISTINCT automation_flow_id)
      comment: "Number of unique automation flows with enrollments"
$$;