-- Metric views for domain: clinical | Business: Healthcare | Version: 2 | Generated on: 2026-07-02 07:21:53

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_diagnosis`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Diagnosis coding quality, chronicity, and risk-capture KPIs for CDI and HCC steering."
  source: "`vibe_healthcare_v1`.`clinical`.`diagnosis`"
  dimensions:
    - name: "care_setting"
      expr: care_setting
      comment: "Care setting where the diagnosis was recorded (inpatient/outpatient/ED)."
    - name: "encounter_type"
      expr: encounter_type
      comment: "Encounter type classification for the diagnosis."
    - name: "diagnosis_type"
      expr: diagnosis_type
      comment: "Type of diagnosis (principal, secondary, admitting, etc.)."
    - name: "coding_status"
      expr: coding_status
      comment: "Current coding workflow status of the diagnosis."
    - name: "diagnosis_month"
      expr: DATE_TRUNC('MONTH', diagnosis_date)
      comment: "Month the diagnosis was made, for trending."
  measures:
    - name: "Diagnosis Count"
      expr: COUNT(1)
      comment: "Total number of diagnosis records — baseline volume."
    - name: "Distinct Patient Count"
      expr: COUNT(DISTINCT mpi_record_id)
      comment: "Distinct patients with a diagnosis — population coverage."
    - name: "Chronic Condition Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN chronic_condition_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of diagnoses flagged chronic — drives population health and HCC risk management."
    - name: "MCC Capture Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN mcc_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of diagnoses that are Major Complications/Comorbidities — impacts DRG reimbursement."
    - name: "CDI Query Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN cdi_query_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of diagnoses that triggered a CDI query — documentation improvement opportunity."
    - name: "HAC Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN hac_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of diagnoses flagged as Hospital Acquired Conditions — quality/penalty risk."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_procedure_event`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Procedure volume, throughput, RVU productivity, and financial KPIs for OR and service-line steering."
  source: "`vibe_healthcare_v1`.`clinical`.`procedure_event`"
  dimensions:
    - name: "service_line"
      expr: service_line
      comment: "Service line associated with the procedure."
    - name: "procedure_category"
      expr: procedure_category
      comment: "Category grouping of the procedure."
    - name: "procedure_status"
      expr: procedure_status
      comment: "Current status of the procedure event."
    - name: "anesthesia_type"
      expr: anesthesia_type
      comment: "Type of anesthesia used."
    - name: "care_setting"
      expr: care_setting
      comment: "Care setting where the procedure occurred."
    - name: "procedure_month"
      expr: DATE_TRUNC('MONTH', procedure_date)
      comment: "Month the procedure was performed, for volume trending."
  measures:
    - name: "Procedure Count"
      expr: COUNT(1)
      comment: "Total procedures performed — baseline throughput volume."
    - name: "Total Work RVU"
      expr: SUM(CAST(rvu_work AS DOUBLE))
      comment: "Total work RVUs — physician productivity and compensation driver."
    - name: "Avg Work RVU"
      expr: AVG(CAST(rvu_work AS DOUBLE))
      comment: "Average work RVU per procedure — case complexity indicator."
    - name: "Total Charge Amount"
      expr: SUM(CAST(charge_amount AS DOUBLE))
      comment: "Total charges generated by procedures — revenue driver."
    - name: "Avg Charge Amount"
      expr: AVG(CAST(charge_amount AS DOUBLE))
      comment: "Average charge per procedure."
    - name: "Consent Obtained Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN consent_obtained = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of procedures with documented consent — compliance and patient safety KPI."
    - name: "Timeout Compliance Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN timeout_performed = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of procedures with a surgical timeout performed — patient safety compliance."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_hai_event`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Healthcare-associated infection surveillance KPIs for infection prevention and value-based purchasing."
  source: "`vibe_healthcare_v1`.`clinical`.`hai_event`"
  dimensions:
    - name: "infection_type"
      expr: infection_type
      comment: "Type of healthcare-associated infection (CLABSI, CAUTI, SSI, etc.)."
    - name: "infection_site"
      expr: infection_site
      comment: "Anatomical site of the infection."
    - name: "care_setting"
      expr: care_setting
      comment: "Care setting where the infection was identified."
    - name: "event_status"
      expr: event_status
      comment: "Status of the HAI investigation/event."
    - name: "event_month"
      expr: DATE_TRUNC('MONTH', event_date)
      comment: "Month the HAI event occurred, for surveillance trending."
  measures:
    - name: "HAI Event Count"
      expr: COUNT(1)
      comment: "Total HAI events — baseline surveillance volume."
    - name: "NHSN Definition Met Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN nhsn_definition_met = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of events meeting NHSN definition — reportable infection rate driver."
    - name: "Outbreak Linked Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN outbreak_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of HAI events tied to an outbreak — escalation and cluster detection."
    - name: "VBP Penalty Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN vbp_penalty_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of events carrying value-based-purchasing penalty exposure — financial risk."
    - name: "Present On Admission Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN present_on_admission = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent present on admission — distinguishes community vs facility-acquired infections."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_cdi_query`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Clinical documentation improvement query performance and reimbursement-impact KPIs."
  source: "`vibe_healthcare_v1`.`clinical`.`cdi_query`"
  dimensions:
    - name: "query_type"
      expr: query_type
      comment: "Type of CDI query issued."
    - name: "query_category"
      expr: query_category
      comment: "Category of documentation opportunity."
    - name: "query_outcome"
      expr: query_outcome
      comment: "Outcome of the query (agreed, disagreed, no change)."
    - name: "query_status"
      expr: query_status
      comment: "Current status of the CDI query."
    - name: "query_issue_month"
      expr: DATE_TRUNC('MONTH', query_issue_date)
      comment: "Month the query was issued, for trending."
  measures:
    - name: "CDI Query Count"
      expr: COUNT(1)
      comment: "Total CDI queries issued — program activity volume."
    - name: "Total Expected Reimbursement Impact"
      expr: SUM(CAST(expected_reimbursement_impact AS DOUBLE))
      comment: "Sum of expected reimbursement impact from queries — financial opportunity."
    - name: "Total Actual Reimbursement Impact"
      expr: SUM(CAST(actual_reimbursement_impact AS DOUBLE))
      comment: "Sum of realized reimbursement impact — value delivered by CDI program."
    - name: "Avg Actual Reimbursement Impact"
      expr: AVG(CAST(actual_reimbursement_impact AS DOUBLE))
      comment: "Average realized impact per query — query efficiency."
    - name: "Query Response Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN query_response_date IS NOT NULL THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of queries receiving a physician response — engagement KPI."
    - name: "Coding Impact Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN coding_impact_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of queries that changed final coding — CDI effectiveness."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_cdi_worksheet`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "CDI review worksheet KPIs tracking DRG weight change and documentation capture."
  source: "`vibe_healthcare_v1`.`clinical`.`cdi_worksheet`"
  dimensions:
    - name: "review_type"
      expr: review_type
      comment: "Type of CDI review performed."
    - name: "review_outcome"
      expr: review_outcome
      comment: "Outcome of the review."
    - name: "service_line"
      expr: service_line
      comment: "Service line under review."
    - name: "payer_type"
      expr: payer_type
      comment: "Payer type for the reviewed encounter."
    - name: "review_month"
      expr: DATE_TRUNC('MONTH', review_date)
      comment: "Month of the review, for trending."
  measures:
    - name: "Worksheet Count"
      expr: COUNT(1)
      comment: "Total CDI worksheets reviewed — program throughput."
    - name: "Total DRG Weight Change"
      expr: SUM(CAST(drg_weight_change AS DOUBLE))
      comment: "Total DRG weight change captured — case-mix index driver."
    - name: "Avg Final DRG Weight"
      expr: AVG(CAST(final_drg_weight AS DOUBLE))
      comment: "Average final DRG weight — case mix intensity."
    - name: "Total Expected Reimbursement Impact"
      expr: SUM(CAST(expected_reimbursement_impact AS DOUBLE))
      comment: "Total expected reimbursement impact from reviews — financial value."
    - name: "CC MCC Capture Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN cc_mcc_captured = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of worksheets capturing CC/MCC — documentation completeness."
    - name: "Query Opportunity Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN query_opportunity_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of reviews identifying a query opportunity — CDI targeting."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_care_plan_goal`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Care plan goal achievement KPIs for population health and care management effectiveness."
  source: "`vibe_healthcare_v1`.`clinical`.`care_plan_goal`"
  dimensions:
    - name: "goal_status"
      expr: goal_status
      comment: "Current status of the care plan goal."
    - name: "achievement_status"
      expr: achievement_status
      comment: "Achievement status of the goal."
    - name: "priority"
      expr: priority
      comment: "Priority level of the goal."
    - name: "care_setting"
      expr: care_setting
      comment: "Care setting the goal applies to."
    - name: "target_month"
      expr: DATE_TRUNC('MONTH', target_date)
      comment: "Month the goal is targeted, for trending."
  measures:
    - name: "Goal Count"
      expr: COUNT(1)
      comment: "Total care plan goals — care management workload."
    - name: "Goal Achievement Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN achievement_status = 'achieved' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of goals achieved — care management effectiveness KPI."
    - name: "Patient Agreement Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN patient_agreement = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of goals with patient agreement — engagement and shared decision-making."
    - name: "Care Gap Related Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN care_gap_related = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of goals tied to care gaps — quality measure closure focus."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_immunization`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Immunization administration and series-completion KPIs for population health and public health reporting."
  source: "`vibe_healthcare_v1`.`clinical`.`immunization`"
  dimensions:
    - name: "series_name"
      expr: series_name
      comment: "Vaccine series name."
    - name: "administration_status"
      expr: administration_status
      comment: "Administration status of the immunization."
    - name: "series_completion_status"
      expr: series_completion_status
      comment: "Completion status of the vaccine series."
    - name: "care_setting"
      expr: care_setting
      comment: "Care setting where the vaccine was given."
    - name: "administration_month"
      expr: DATE_TRUNC('MONTH', administration_timestamp)
      comment: "Month of administration, for coverage trending."
  measures:
    - name: "Immunization Count"
      expr: COUNT(1)
      comment: "Total immunization records — vaccination volume."
    - name: "Distinct Patient Count"
      expr: COUNT(DISTINCT mpi_record_id)
      comment: "Distinct patients immunized — population coverage."
    - name: "IIS Reporting Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN iis_reported = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent reported to the immunization information system — public health compliance."
    - name: "Adverse Reaction Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN reaction_observed = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent with observed reactions — vaccine safety surveillance."
    - name: "Consent Obtained Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN consent_obtained = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent with documented consent — compliance KPI."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_note`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Clinical documentation timeliness and completeness KPIs for provider productivity and compliance."
  source: "`vibe_healthcare_v1`.`clinical`.`note`"
  dimensions:
    - name: "note_type"
      expr: note_type
      comment: "Type of clinical note."
    - name: "note_status"
      expr: note_status
      comment: "Current status of the note (draft, signed, etc.)."
    - name: "author_role"
      expr: author_role
      comment: "Role of the note author."
    - name: "specialty"
      expr: specialty
      comment: "Specialty associated with the note."
    - name: "authored_month"
      expr: DATE_TRUNC('MONTH', authored_timestamp)
      comment: "Month the note was authored, for trending."
  measures:
    - name: "Note Count"
      expr: COUNT(1)
      comment: "Total clinical notes — documentation volume."
    - name: "Signed Note Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN signed_timestamp IS NOT NULL THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of notes signed — documentation closure compliance."
    - name: "Late Entry Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_late_entry = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of notes flagged as late entries — documentation timeliness risk."
    - name: "Copy Forward Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_copy_forwarded = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of notes using copy-forward — documentation integrity / audit risk."
    - name: "CDI Query Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN cdi_query_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of notes triggering CDI queries — documentation improvement need."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_observation`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Clinical observation value and critical-result KPIs for quality and patient safety."
  source: "`vibe_healthcare_v1`.`clinical`.`observation`"
  dimensions:
    - name: "observation_category"
      expr: observation_category
      comment: "Category of the observation."
    - name: "observation_status"
      expr: observation_status
      comment: "Status of the observation."
    - name: "body_system"
      expr: body_system
      comment: "Body system the observation relates to."
    - name: "care_setting"
      expr: care_setting
      comment: "Care setting where the observation was recorded."
    - name: "observed_month"
      expr: DATE_TRUNC('MONTH', datetime)
      comment: "Month the observation was taken, for trending."
  measures:
    - name: "Observation Count"
      expr: COUNT(1)
      comment: "Total observations recorded — clinical data volume."
    - name: "Avg Observation Value"
      expr: AVG(CAST(value_numeric AS DOUBLE))
      comment: "Average numeric observation value — clinical trend monitoring."
    - name: "Critical Value Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_critical_value = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of observations that are critical values — patient safety escalation KPI."
    - name: "Avg Assessment Score"
      expr: AVG(CAST(assessment_score AS DOUBLE))
      comment: "Average assessment tool score — screening severity indicator."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_vital_sign`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Vital sign monitoring KPIs including abnormal-rate and remote patient monitoring adoption."
  source: "`vibe_healthcare_v1`.`clinical`.`vital_sign`"
  dimensions:
    - name: "observation_type"
      expr: observation_type
      comment: "Type of vital sign observation."
    - name: "vital_sign_status"
      expr: vital_sign_status
      comment: "Status of the vital sign record."
    - name: "care_unit"
      expr: care_unit
      comment: "Care unit where the vital was captured."
    - name: "care_setting"
      expr: care_setting
      comment: "Care setting for the vital measurement."
    - name: "measurement_month"
      expr: DATE_TRUNC('MONTH', measurement_timestamp)
      comment: "Month of measurement, for trending."
  measures:
    - name: "Vital Sign Count"
      expr: COUNT(1)
      comment: "Total vital sign measurements — monitoring volume."
    - name: "Avg Numeric Value"
      expr: AVG(CAST(numeric_value AS DOUBLE))
      comment: "Average numeric vital value — clinical trend monitoring."
    - name: "Abnormal Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN abnormal_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of vitals flagged abnormal — deterioration surveillance KPI."
    - name: "RPM Sourced Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN rpm_device_source_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of vitals from remote patient monitoring devices — digital health adoption."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_allergy`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Allergy documentation and reconciliation KPIs for medication safety."
  source: "`vibe_healthcare_v1`.`clinical`.`allergy`"
  dimensions:
    - name: "allergen_type"
      expr: allergen_type
      comment: "Type of allergen."
    - name: "allergy_category"
      expr: allergy_category
      comment: "Category of the allergy."
    - name: "criticality"
      expr: criticality
      comment: "Criticality of the allergic reaction."
    - name: "reconciliation_status"
      expr: reconciliation_status
      comment: "Reconciliation status of the allergy record."
    - name: "recorded_month"
      expr: DATE_TRUNC('MONTH', recorded_date)
      comment: "Month the allergy was recorded, for trending."
  measures:
    - name: "Allergy Count"
      expr: COUNT(1)
      comment: "Total allergy records — documentation volume."
    - name: "Distinct Patient Count"
      expr: COUNT(DISTINCT mpi_record_id)
      comment: "Distinct patients with documented allergies — safety coverage."
    - name: "Reconciled Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN reconciliation_status = 'reconciled' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of allergies reconciled — medication safety completeness."
    - name: "High Criticality Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN criticality = 'high' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of high-criticality allergies — clinical alert prioritization."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_problem`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Problem list chronicity and risk-adjustment KPIs for population health."
  source: "`vibe_healthcare_v1`.`clinical`.`problem`"
  dimensions:
    - name: "problem_status"
      expr: problem_status
      comment: "Status of the problem (active, resolved, etc.)."
    - name: "problem_type"
      expr: problem_type
      comment: "Type/classification of the problem."
    - name: "priority"
      expr: priority
      comment: "Priority of the problem on the list."
    - name: "care_setting"
      expr: care_setting
      comment: "Care setting for the problem."
    - name: "noted_month"
      expr: DATE_TRUNC('MONTH', noted_date)
      comment: "Month the problem was noted, for trending."
  measures:
    - name: "Problem Count"
      expr: COUNT(1)
      comment: "Total problem list entries — clinical documentation volume."
    - name: "Distinct Patient Count"
      expr: COUNT(DISTINCT mpi_record_id)
      comment: "Distinct patients with problems — population size."
    - name: "Chronic Condition Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN chronic_condition_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of problems that are chronic — population health risk driver."
    - name: "CDI Query Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN cdi_query_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of problems with CDI queries — documentation improvement need."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_nursing_assessment`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Nursing assessment KPIs for fall/pressure-injury risk and discharge readiness."
  source: "`vibe_healthcare_v1`.`clinical`.`nursing_assessment`"
  dimensions:
    - name: "assessment_type"
      expr: assessment_type
      comment: "Type of nursing assessment."
    - name: "fall_risk_category"
      expr: fall_risk_category
      comment: "Fall risk category assigned."
    - name: "nursing_unit"
      expr: nursing_unit
      comment: "Nursing unit performing the assessment."
    - name: "care_setting"
      expr: care_setting
      comment: "Care setting for the assessment."
    - name: "assessment_month"
      expr: DATE_TRUNC('MONTH', assessment_datetime)
      comment: "Month of assessment, for trending."
  measures:
    - name: "Assessment Count"
      expr: COUNT(1)
      comment: "Total nursing assessments — nursing workload volume."
    - name: "Safety Check Completion Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN safety_check_completed = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of assessments with completed safety checks — patient safety compliance."
    - name: "Patient Education Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN patient_education_provided = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent providing patient education — quality of care KPI."
    - name: "Joint Commission Compliance Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN joint_commission_compliant = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent compliant with Joint Commission standards — accreditation readiness."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_finding`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Clinical/imaging finding KPIs for critical-result follow-up and AI-assisted detection."
  source: "`vibe_healthcare_v1`.`clinical`.`clinical_finding`"
  dimensions:
    - name: "finding_category"
      expr: finding_category
      comment: "Category of the clinical finding."
    - name: "finding_status"
      expr: finding_status
      comment: "Status of the finding."
    - name: "specialty"
      expr: specialty
      comment: "Specialty associated with the finding."
    - name: "care_setting"
      expr: care_setting
      comment: "Care setting where the finding was documented."
    - name: "documentation_month"
      expr: DATE_TRUNC('MONTH', documentation_date)
      comment: "Month the finding was documented, for trending."
  measures:
    - name: "Finding Count"
      expr: COUNT(1)
      comment: "Total clinical findings — diagnostic volume."
    - name: "Critical Result Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_critical_result = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent critical findings — patient safety escalation KPI."
    - name: "Follow Up Recommended Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN follow_up_recommended = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of findings recommending follow-up — care continuity driver."
    - name: "AI Detected Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN ai_detected_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of findings detected via AI models — clinical AI adoption KPI."
    - name: "Provider Notified Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN provider_notified = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent with documented provider notification — closed-loop communication compliance."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_functional_status`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Functional status assessment KPIs for rehab potential and post-acute planning."
  source: "`vibe_healthcare_v1`.`clinical`.`functional_status`"
  dimensions:
    - name: "assessment_type"
      expr: assessment_type
      comment: "Type of functional assessment."
    - name: "assessment_status"
      expr: assessment_status
      comment: "Status of the assessment."
    - name: "rehabilitation_potential"
      expr: rehabilitation_potential
      comment: "Rehabilitation potential classification."
    - name: "care_setting"
      expr: care_setting
      comment: "Care setting for the assessment."
    - name: "assessment_month"
      expr: DATE_TRUNC('MONTH', assessment_date)
      comment: "Month of assessment, for trending."
  measures:
    - name: "Assessment Count"
      expr: COUNT(1)
      comment: "Total functional status assessments — volume."
    - name: "Avg ADL Score"
      expr: AVG(CAST(adl_score AS DOUBLE))
      comment: "Average activities-of-daily-living score — functional independence indicator."
    - name: "Avg Cognitive Score"
      expr: AVG(CAST(cognitive_score AS DOUBLE))
      comment: "Average cognitive score — cognitive status monitoring."
    - name: "Avg Mobility Score"
      expr: AVG(CAST(mobility_score AS DOUBLE))
      comment: "Average mobility score — fall and discharge planning input."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_care_team_member`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Care team staffing and coverage KPIs for care coordination workforce planning."
  source: "`vibe_healthcare_v1`.`clinical`.`care_team_member`"
  dimensions:
    - name: "member_type"
      expr: member_type
      comment: "Type of care team member."
    - name: "role_name"
      expr: role_name
      comment: "Role of the member on the care team."
    - name: "assignment_type"
      expr: assignment_type
      comment: "Type of assignment."
    - name: "care_setting"
      expr: care_setting
      comment: "Care setting the member serves."
    - name: "assignment_start_month"
      expr: DATE_TRUNC('MONTH', assignment_start_date)
      comment: "Month the assignment started, for trending."
  measures:
    - name: "Member Count"
      expr: COUNT(1)
      comment: "Total care team member assignments — staffing volume."
    - name: "Total FTE Allocation"
      expr: SUM(CAST(fte_allocation AS DOUBLE))
      comment: "Total FTE allocated to care teams — workforce capacity."
    - name: "Active Member Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_active = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of members currently active — staffing utilization."
    - name: "PCP Assignment Rate Pct"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_pcp = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percent of members serving as PCP — attribution coverage."
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_care_plan_quality`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Key quality indicators for care plans"
  source: "`vibe_healthcare_v1`.`clinical`.`care_plan`"
  dimensions:
    - name: "care_site_id"
      expr: care_site_id
      comment: "Care site associated with the care plan"
    - name: "care_plan_type"
      expr: plan_type
      comment: "Type/category of the care plan"
    - name: "effective_start_month"
      expr: DATE_TRUNC('month', effective_start_date)
      comment: "Month when the care plan became effective"
    - name: "readmission_risk_level"
      expr: readmission_risk_level
      comment: "Risk level for patient readmission"
  measures:
    - name: "care_plan_count"
      expr: COUNT(1)
      comment: "Total number of care plans"
    - name: "advance_directive_on_file_count"
      expr: SUM(CASE WHEN advance_directive_on_file THEN 1 ELSE 0 END)
      comment: "Count of care plans with an advance directive on file"
    - name: "patient_consent_obtained_count"
      expr: SUM(CASE WHEN patient_consent_obtained THEN 1 ELSE 0 END)
      comment: "Count of care plans where patient consent was obtained"
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_observation_numeric`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Aggregates for numeric clinical observations"
  source: "`vibe_healthcare_v1`.`clinical`.`observation`"
  dimensions:
    - name: "loinc_code_id"
      expr: loinc_code_id
      comment: "LOINC code identifying the observation type"
    - name: "observation_status"
      expr: observation_status
      comment: "Status of the observation (e.g., final, preliminary)"
  measures:
    - name: "avg_numeric_value"
      expr: AVG(CAST(value_numeric AS DOUBLE))
      comment: "Average numeric observation value"
    - name: "observation_count"
      expr: COUNT(1)
      comment: "Number of observation records"
$$;

CREATE OR REPLACE VIEW `vibe_healthcare_v1`.`_metrics`.`clinical_procedure_financials`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Financial performance of clinical procedures"
  source: "`vibe_healthcare_v1`.`clinical`.`procedure_event`"
  dimensions:
    - name: "care_site_id"
      expr: care_site_id
      comment: "Identifier of the care site where the procedure occurred"
    - name: "procedure_month"
      expr: DATE_TRUNC('month', procedure_date)
      comment: "Month of the procedure date"
  measures:
    - name: "total_procedure_charge"
      expr: SUM(CAST(charge_amount AS DOUBLE))
      comment: "Total dollar amount charged for procedures"
    - name: "average_procedure_charge"
      expr: AVG(CAST(charge_amount AS DOUBLE))
      comment: "Average charge per procedure record"
    - name: "procedure_count"
      expr: COUNT(1)
      comment: "Number of procedure events recorded"
$$;