-- Metric views for domain: loyalty | Business: Travel_Hospitality | Version: 2 | Generated on: 2026-07-10 20:24:18

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`loyalty_member`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Core loyalty member metrics tracking lifetime value, engagement, and program health"
  source: "`vibe_travel_hospitality_v1`.`loyalty`.`member`"
  dimensions:
    - name: "membership_status"
      expr: membership_status
      comment: "Current status of the loyalty membership (active, suspended, closed)"
    - name: "enrollment_channel"
      expr: enrollment_channel
      comment: "Channel through which member enrolled (web, mobile, property, call center)"
    - name: "tier_name"
      expr: tier_id
      comment: "Member tier level identifier for segmentation"
    - name: "enrollment_year"
      expr: YEAR(enrollment_date)
      comment: "Year member enrolled in loyalty program"
    - name: "enrollment_month"
      expr: DATE_TRUNC('MONTH', enrollment_date)
      comment: "Month member enrolled for cohort analysis"
    - name: "language_preference"
      expr: language_preference
      comment: "Member preferred language for communication"
    - name: "currency_preference"
      expr: currency_preference
      comment: "Member preferred currency for transactions"
    - name: "vip_flag"
      expr: vip_flag
      comment: "Whether member is flagged as VIP"
    - name: "communication_opt_in"
      expr: communication_opt_in
      comment: "Whether member opted in to communications"
  measures:
    - name: "total_members"
      expr: COUNT(DISTINCT member_id)
      comment: "Total unique loyalty members"
    - name: "total_lifetime_revenue"
      expr: SUM(CAST(lifetime_revenue AS DOUBLE))
      comment: "Total lifetime revenue generated by members"
    - name: "avg_lifetime_revenue_per_member"
      expr: AVG(CAST(lifetime_revenue AS DOUBLE))
      comment: "Average lifetime revenue per member"
    - name: "total_lifetime_points_earned"
      expr: SUM(CAST(lifetime_points_earned AS BIGINT))
      comment: "Total points earned by all members lifetime"
    - name: "avg_lifetime_points_per_member"
      expr: AVG(CAST(lifetime_points_earned AS BIGINT))
      comment: "Average lifetime points earned per member"
    - name: "total_current_points_balance"
      expr: SUM(CAST(current_points_balance AS BIGINT))
      comment: "Total outstanding points liability across all members"
    - name: "avg_current_points_balance"
      expr: AVG(CAST(current_points_balance AS BIGINT))
      comment: "Average current points balance per member"
    - name: "total_points_redeemed"
      expr: SUM(CAST(points_redeemed AS BIGINT))
      comment: "Total points redeemed by all members"
    - name: "total_points_expired"
      expr: SUM(CAST(points_expired AS BIGINT))
      comment: "Total points expired (breakage)"
    - name: "points_redemption_rate"
      expr: ROUND(100.0 * SUM(CAST(points_redeemed AS BIGINT)) / NULLIF(SUM(CAST(lifetime_points_earned AS BIGINT)), 0), 2)
      comment: "Percentage of lifetime earned points that have been redeemed"
    - name: "points_breakage_rate"
      expr: ROUND(100.0 * SUM(CAST(points_expired AS BIGINT)) / NULLIF(SUM(CAST(lifetime_points_earned AS BIGINT)), 0), 2)
      comment: "Percentage of lifetime earned points that expired unredeemed"
    - name: "total_ytd_revenue"
      expr: SUM(CAST(ytd_revenue AS DOUBLE))
      comment: "Total year-to-date revenue from members"
    - name: "avg_ytd_revenue_per_member"
      expr: AVG(CAST(ytd_revenue AS DOUBLE))
      comment: "Average year-to-date revenue per member"
    - name: "avg_salt_score"
      expr: AVG(CAST(salt_score AS DOUBLE))
      comment: "Average SALT (satisfaction and loyalty) score across members"
$$;

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`loyalty_points_ledger`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Points transaction metrics tracking earning, redemption, and transfer activity"
  source: "`vibe_travel_hospitality_v1`.`loyalty`.`points_ledger`"
  dimensions:
    - name: "transaction_type"
      expr: transaction_type
      comment: "Type of points transaction (earn, redeem, transfer, adjustment, expiry)"
    - name: "transaction_status"
      expr: transaction_status
      comment: "Status of the transaction (posted, pending, reversed, cancelled)"
    - name: "source_activity_type"
      expr: source_activity_type
      comment: "Activity that triggered the points transaction (stay, dining, spa, promotion)"
    - name: "activity_month"
      expr: DATE_TRUNC('MONTH', activity_date)
      comment: "Month of the points activity for trend analysis"
    - name: "posting_month"
      expr: DATE_TRUNC('MONTH', posting_date)
      comment: "Month transaction was posted to ledger"
    - name: "tier_at_transaction"
      expr: tier_at_transaction
      comment: "Member tier at time of transaction"
    - name: "is_qualifying"
      expr: is_qualifying
      comment: "Whether transaction counts toward tier qualification"
    - name: "transfer_direction"
      expr: transfer_direction
      comment: "Direction of points transfer (inbound, outbound)"
    - name: "base_currency_code"
      expr: base_currency_code
      comment: "Currency code for the transaction"
  measures:
    - name: "total_transactions"
      expr: COUNT(1)
      comment: "Total number of points transactions"
    - name: "total_points_transacted"
      expr: SUM(CAST(points_amount AS DOUBLE))
      comment: "Total points amount across all transactions (net of sign)"
    - name: "avg_points_per_transaction"
      expr: AVG(CAST(points_amount AS DOUBLE))
      comment: "Average points amount per transaction"
    - name: "total_base_amount"
      expr: SUM(CAST(base_amount AS DOUBLE))
      comment: "Total base monetary amount before multipliers"
    - name: "avg_base_amount"
      expr: AVG(CAST(base_amount AS DOUBLE))
      comment: "Average base monetary amount per transaction"
    - name: "total_transfer_fees"
      expr: SUM(CAST(transfer_fee_amount AS DOUBLE))
      comment: "Total fees collected on points transfers"
    - name: "avg_conversion_rate"
      expr: AVG(CAST(conversion_rate AS DOUBLE))
      comment: "Average conversion rate applied to transactions"
    - name: "unique_members_transacting"
      expr: COUNT(DISTINCT member_id)
      comment: "Number of unique members with points activity"
$$;

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`loyalty_redemption`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Redemption metrics tracking how members use their points and program value delivery"
  source: "`vibe_travel_hospitality_v1`.`loyalty`.`redemption`"
  dimensions:
    - name: "redemption_type"
      expr: redemption_type
      comment: "Type of redemption (free night, upgrade, merchandise, experience, partner)"
    - name: "redemption_status"
      expr: redemption_status
      comment: "Status of redemption (requested, confirmed, fulfilled, cancelled, refunded)"
    - name: "fulfillment_channel"
      expr: fulfillment_channel
      comment: "Channel through which redemption was fulfilled"
    - name: "request_month"
      expr: DATE_TRUNC('MONTH', request_date)
      comment: "Month redemption was requested"
    - name: "fulfillment_month"
      expr: DATE_TRUNC('MONTH', fulfillment_date)
      comment: "Month redemption was fulfilled"
    - name: "tier_at_redemption"
      expr: tier_at_redemption
      comment: "Member tier at time of redemption"
    - name: "currency_code"
      expr: currency_code
      comment: "Currency code for monetary values"
    - name: "property_code"
      expr: property_code
      comment: "Property where redemption occurred"
  measures:
    - name: "total_redemptions"
      expr: COUNT(1)
      comment: "Total number of redemption transactions"
    - name: "total_points_redeemed"
      expr: SUM(CAST(points_redeemed AS BIGINT))
      comment: "Total points redeemed across all transactions"
    - name: "avg_points_per_redemption"
      expr: AVG(CAST(points_redeemed AS BIGINT))
      comment: "Average points redeemed per transaction"
    - name: "total_monetary_value"
      expr: SUM(CAST(monetary_equivalent_value AS DOUBLE))
      comment: "Total monetary value delivered through redemptions"
    - name: "avg_monetary_value_per_redemption"
      expr: AVG(CAST(monetary_equivalent_value AS DOUBLE))
      comment: "Average monetary value per redemption"
    - name: "total_cash_amount"
      expr: SUM(CAST(cash_amount AS DOUBLE))
      comment: "Total cash component in cash-plus-points redemptions"
    - name: "total_points_refunded"
      expr: SUM(CAST(points_refunded AS BIGINT))
      comment: "Total points refunded due to cancellations"
    - name: "redemption_value_per_point"
      expr: ROUND(SUM(CAST(monetary_equivalent_value AS DOUBLE)) / NULLIF(SUM(CAST(points_redeemed AS BIGINT)), 0), 4)
      comment: "Average monetary value delivered per point redeemed"
    - name: "unique_members_redeeming"
      expr: COUNT(DISTINCT member_id)
      comment: "Number of unique members who redeemed points"
$$;

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`loyalty_promotion`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Promotion performance metrics tracking campaign effectiveness and ROI"
  source: "`vibe_travel_hospitality_v1`.`loyalty`.`promotion`"
  dimensions:
    - name: "promotion_status"
      expr: promotion_status
      comment: "Current status of promotion (draft, active, paused, completed, cancelled)"
    - name: "promotion_type"
      expr: promotion_type
      comment: "Type of promotion (bonus points, multiplier, status match, welcome bonus)"
    - name: "marketing_channel"
      expr: marketing_channel
      comment: "Marketing channel used to distribute promotion"
    - name: "start_month"
      expr: DATE_TRUNC('MONTH', start_date)
      comment: "Month promotion started"
    - name: "registration_required_flag"
      expr: registration_required_flag
      comment: "Whether promotion requires member registration"
    - name: "stackable_flag"
      expr: stackable_flag
      comment: "Whether promotion can be combined with others"
  measures:
    - name: "total_promotions"
      expr: COUNT(1)
      comment: "Total number of promotions"
    - name: "total_enrollments"
      expr: SUM(CAST(total_enrollments AS BIGINT))
      comment: "Total member enrollments across all promotions"
    - name: "total_completions"
      expr: SUM(CAST(total_completions AS BIGINT))
      comment: "Total completed promotions (members who met criteria)"
    - name: "promotion_completion_rate"
      expr: ROUND(100.0 * SUM(CAST(total_completions AS BIGINT)) / NULLIF(SUM(CAST(total_enrollments AS BIGINT)), 0), 2)
      comment: "Percentage of enrolled members who completed promotion requirements"
    - name: "total_budget_allocated"
      expr: SUM(CAST(budget_cap_amount AS DOUBLE))
      comment: "Total budget allocated to promotions"
    - name: "total_budget_consumed"
      expr: SUM(CAST(budget_consumed_amount AS DOUBLE))
      comment: "Total budget consumed by promotions"
    - name: "budget_utilization_rate"
      expr: ROUND(100.0 * SUM(CAST(budget_consumed_amount AS DOUBLE)) / NULLIF(SUM(CAST(budget_cap_amount AS DOUBLE)), 0), 2)
      comment: "Percentage of allocated budget consumed"
    - name: "avg_bonus_points_multiplier"
      expr: AVG(CAST(bonus_points_multiplier AS DOUBLE))
      comment: "Average bonus points multiplier across promotions"
    - name: "avg_minimum_spend"
      expr: AVG(CAST(minimum_spend_amount AS DOUBLE))
      comment: "Average minimum spend requirement across promotions"
$$;

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`loyalty_tier_history`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Tier movement metrics tracking member progression and program health"
  source: "`vibe_travel_hospitality_v1`.`loyalty`.`tier_history`"
  dimensions:
    - name: "change_type"
      expr: change_type
      comment: "Type of tier change (upgrade, downgrade, renewal, status match)"
    - name: "change_reason_code"
      expr: change_reason_code
      comment: "Reason code for tier change"
    - name: "qualification_basis"
      expr: qualification_basis
      comment: "Basis for tier qualification (nights, points, spend, status match)"
    - name: "effective_month"
      expr: DATE_TRUNC('MONTH', effective_date)
      comment: "Month tier change became effective"
    - name: "is_current_tier_flag"
      expr: is_current_tier_flag
      comment: "Whether this is the member's current tier"
    - name: "tier_extension_granted_flag"
      expr: tier_extension_granted_flag
      comment: "Whether tier extension was granted"
  measures:
    - name: "total_tier_changes"
      expr: COUNT(1)
      comment: "Total number of tier change events"
    - name: "unique_members_with_changes"
      expr: COUNT(DISTINCT member_id)
      comment: "Number of unique members with tier changes"
    - name: "total_bonus_points_awarded"
      expr: SUM(CAST(bonus_points_awarded AS DOUBLE))
      comment: "Total bonus points awarded for tier changes"
    - name: "avg_bonus_points_per_change"
      expr: AVG(CAST(bonus_points_awarded AS DOUBLE))
      comment: "Average bonus points awarded per tier change"
    - name: "total_qualifying_points"
      expr: SUM(CAST(qualifying_points_achieved AS DOUBLE))
      comment: "Total qualifying points achieved across all tier changes"
    - name: "avg_qualifying_points"
      expr: AVG(CAST(qualifying_points_achieved AS DOUBLE))
      comment: "Average qualifying points per tier change"
    - name: "total_qualifying_spend"
      expr: SUM(CAST(qualifying_spend_amount AS DOUBLE))
      comment: "Total qualifying spend across all tier changes"
    - name: "avg_qualifying_spend"
      expr: AVG(CAST(qualifying_spend_amount AS DOUBLE))
      comment: "Average qualifying spend per tier change"
$$;

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`loyalty_fraud_alert`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Fraud detection and prevention metrics tracking program integrity and risk"
  source: "`vibe_travel_hospitality_v1`.`loyalty`.`fraud_alert`"
  dimensions:
    - name: "alert_type"
      expr: alert_type
      comment: "Type of fraud alert (account takeover, points theft, fake redemption, collusion)"
    - name: "alert_severity"
      expr: alert_severity
      comment: "Severity level of the alert (low, medium, high, critical)"
    - name: "alert_status"
      expr: alert_status
      comment: "Current status of alert (open, investigating, resolved, false positive)"
    - name: "detection_method"
      expr: detection_method
      comment: "Method used to detect fraud (rule-based, ML model, manual review)"
    - name: "detection_month"
      expr: DATE_TRUNC('MONTH', detection_timestamp)
      comment: "Month fraud was detected"
    - name: "account_frozen_flag"
      expr: account_frozen_flag
      comment: "Whether member account was frozen due to alert"
    - name: "law_enforcement_notified_flag"
      expr: law_enforcement_notified_flag
      comment: "Whether law enforcement was notified"
    - name: "regulatory_reporting_required_flag"
      expr: regulatory_reporting_required_flag
      comment: "Whether regulatory reporting is required"
  measures:
    - name: "total_fraud_alerts"
      expr: COUNT(1)
      comment: "Total number of fraud alerts generated"
    - name: "unique_members_flagged"
      expr: COUNT(DISTINCT member_id)
      comment: "Number of unique members flagged for fraud"
    - name: "total_points_involved"
      expr: SUM(CAST(points_amount_involved AS BIGINT))
      comment: "Total points involved in fraud alerts"
    - name: "total_monetary_value_involved"
      expr: SUM(CAST(monetary_value_involved AS DOUBLE))
      comment: "Total monetary value involved in fraud cases"
    - name: "total_points_reversed"
      expr: SUM(CAST(points_reversed_amount AS BIGINT))
      comment: "Total points reversed due to fraud"
    - name: "avg_risk_score"
      expr: AVG(CAST(risk_score AS DOUBLE))
      comment: "Average risk score across fraud alerts"
    - name: "fraud_recovery_rate"
      expr: ROUND(100.0 * SUM(CAST(points_reversed_amount AS BIGINT)) / NULLIF(SUM(CAST(points_amount_involved AS BIGINT)), 0), 2)
      comment: "Percentage of fraudulent points successfully recovered"
$$;

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`loyalty_accrual_rule`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Points earning rule metrics tracking program economics and earning opportunities"
  source: "`vibe_travel_hospitality_v1`.`loyalty`.`accrual_rule`"
  dimensions:
    - name: "rule_type"
      expr: rule_type
      comment: "Type of accrual rule (base, bonus, promotional, tier multiplier)"
    - name: "rule_status"
      expr: rule_status
      comment: "Current status of rule (active, inactive, expired, pending)"
    - name: "approval_status"
      expr: approval_status
      comment: "Approval status of rule (draft, pending, approved, rejected)"
    - name: "earning_basis"
      expr: earning_basis
      comment: "Basis for earning points (spend, nights, stays, activity)"
    - name: "is_stackable"
      expr: is_stackable
      comment: "Whether rule can be combined with other rules"
    - name: "effective_start_month"
      expr: DATE_TRUNC('MONTH', effective_start_date)
      comment: "Month rule became effective"
  measures:
    - name: "total_accrual_rules"
      expr: COUNT(1)
      comment: "Total number of accrual rules"
    - name: "avg_points_per_currency_unit"
      expr: AVG(CAST(points_per_currency_unit AS DOUBLE))
      comment: "Average points earned per currency unit spent"
    - name: "avg_tier_multiplier"
      expr: AVG(CAST(tier_multiplier AS DOUBLE))
      comment: "Average tier multiplier across rules"
    - name: "avg_segment_multiplier"
      expr: AVG(CAST(segment_multiplier AS DOUBLE))
      comment: "Average segment multiplier across rules"
    - name: "total_estimated_annual_points"
      expr: SUM(CAST(estimated_annual_points_volume AS BIGINT))
      comment: "Total estimated annual points volume across all rules"
    - name: "avg_minimum_transaction_amount"
      expr: AVG(CAST(minimum_transaction_amount AS DOUBLE))
      comment: "Average minimum transaction amount required for earning"
$$;

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`loyalty_partner_program`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Partner program metrics tracking ecosystem value and transfer activity"
  source: "`vibe_travel_hospitality_v1`.`loyalty`.`partner_program`"
  dimensions:
    - name: "partner_program_status"
      expr: partner_program_status
      comment: "Current status of partner program (active, suspended, terminated)"
    - name: "partner_type"
      expr: partner_type
      comment: "Type of partner (airline, credit card, retail, travel, other)"
    - name: "partnership_tier"
      expr: partnership_tier
      comment: "Tier level of partnership (strategic, preferred, standard)"
    - name: "earn_eligibility_flag"
      expr: earn_eligibility_flag
      comment: "Whether members can earn points through partner"
    - name: "redemption_eligibility_flag"
      expr: redemption_eligibility_flag
      comment: "Whether members can redeem points with partner"
    - name: "transfer_eligibility_flag"
      expr: transfer_eligibility_flag
      comment: "Whether members can transfer points to/from partner"
  measures:
    - name: "total_partner_programs"
      expr: COUNT(1)
      comment: "Total number of partner programs"
    - name: "avg_hotel_to_partner_ratio"
      expr: AVG(CAST(hotel_to_partner_ratio AS DOUBLE))
      comment: "Average conversion ratio from hotel points to partner currency"
    - name: "avg_partner_to_hotel_ratio"
      expr: AVG(CAST(partner_to_hotel_ratio AS DOUBLE))
      comment: "Average conversion ratio from partner currency to hotel points"
    - name: "avg_revenue_share_percentage"
      expr: AVG(CAST(revenue_share_percentage AS DOUBLE))
      comment: "Average revenue share percentage across partner programs"
$$;