-- Schema for Domain: digital_health | Business:  | Version: v2_ecm
-- Generated on: 2026-06-23 13:03:44

-- ========= DATABASE =========
CREATE DATABASE IF NOT EXISTS `vibe_healthcare_v1`.`digital_health` COMMENT '';

-- ========= TABLES =========
CREATE OR REPLACE TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` (
    `digital_health_rpm_device_reading_id` BIGINT COMMENT 'Surrogate primary key for each RPM device reading event.',
    `care_site_id` BIGINT COMMENT 'FK to the care site responsible for the RPM program.',
    `demographics_id` BIGINT COMMENT '',
    `observation_id` BIGINT COMMENT 'FHIR Observation resource ID if this reading was mapped to a FHIR resource.',
    `mpi_record_id` BIGINT COMMENT 'FK to patient MPI record; links the reading to the enterprise patient identity.',
    `digital_health_rpm_alert_threshold_id` BIGINT COMMENT 'Threshold rule evaluated against this reading.',
    `rpm_alert_threshold_id` BIGINT COMMENT 'FK to the alert threshold rule that was evaluated for this reading.',
    `clinician_id` BIGINT COMMENT 'FK to the ordering or supervising clinician for the RPM program.',
    `digital_health_rpm_program_enrollment_id` BIGINT COMMENT 'FK to the RPM program enrollment that authorized this monitoring.',
    `rpm_reviewed_by_clinician_id` BIGINT COMMENT '',
    `alert_acknowledged_by` STRING COMMENT 'Name or user ID of the clinician who acknowledged the alert.',
    `alert_acknowledged_flag` BOOLEAN COMMENT 'Whether the alert generated by this reading has been acknowledged by a clinician.',
    `alert_acknowledged_timestamp` TIMESTAMP COMMENT 'Timestamp when the alert was acknowledged.',
    `alert_severity` STRING COMMENT 'Severity of the triggered alert: low, medium, high, critical.',
    `alert_triggered_flag` BOOLEAN COMMENT 'Indicates whether this reading triggered an alert based on configured thresholds.',
    `context_code` STRING COMMENT 'Clinical context of the reading: fasting, post_meal, post_exercise, resting, sleeping.',
    `created_timestamp` TIMESTAMP COMMENT 'Record creation timestamp in the data lakehouse.',
    `data_quality_flag` BOOLEAN COMMENT 'Whether the reading passed data quality validation.',
    `data_source` STRING COMMENT '',
    `device_identifier` STRING COMMENT 'Unique device identifier (UDI or serial number) of the RPM device that generated the reading.',
    `device_manufacturer` STRING COMMENT 'Manufacturer name of the RPM device.',
    `device_model` STRING COMMENT 'Model name/number of the RPM device.',
    `device_serial_number` STRING COMMENT '',
    `device_type` STRING COMMENT 'Type of device (e.g., pulse_oximeter, glucometer, blood_pressure_cuff, weight_scale, ecg_patch).',
    `diastolic_bp` STRING COMMENT '',
    `diastolic_mmhg` DECIMAL(18,2) COMMENT 'Diastolic blood pressure in mmHg.',
    `ehr_sync_timestamp` TIMESTAMP COMMENT 'Timestamp when the reading was synced to the EHR.',
    `ehr_synced_flag` BOOLEAN COMMENT 'Whether this reading has been synced to the EHR as a clinical observation.',
    `glucose_mg_dl` DECIMAL(18,2) COMMENT 'Blood glucose level in mg/dL; populated when measurement_type=glucose.',
    `heart_rate_bpm` DECIMAL(18,2) COMMENT 'Heart rate in beats per minute; populated when measurement_type=heart_rate.',
    `is_out_of_range_flag` BOOLEAN COMMENT '',
    `loinc_code` STRING COMMENT 'LOINC code corresponding to the measurement type for semantic interoperability.',
    `measurement_type` STRING COMMENT 'Type of measurement: heart_rate, glucose, spo2, weight, blood_pressure_systolic, blood_pressure_diastolic, temperature, respiratory_rate.',
    `measurement_unit` STRING COMMENT 'Unit of measure (e.g., bpm, mg/dL, %, kg, lbs, mmHg, degC, degF, breaths/min).',
    `measurement_value` DECIMAL(18,2) COMMENT 'Numeric value of the measurement in the specified unit.',
    `notes` STRING COMMENT 'Free-text notes from the patient or clinician about this reading.',
    `out_of_range_flag` BOOLEAN COMMENT 'Whether the reading breached an alert threshold.',
    `patient_reported_flag` BOOLEAN COMMENT 'True if the reading was manually entered by the patient rather than auto-transmitted by device.',
    `quality_flag` BOOLEAN COMMENT '',
    `reading_date` DATE COMMENT 'Calendar date of the reading, derived from reading_timestamp for partitioning.',
    `reading_quality_flag` STRING COMMENT 'Quality indicator for the reading: valid, artifact, out_of_range, device_error.',
    `reading_timestamp` TIMESTAMP COMMENT 'Timestamp when the measurement was taken by the device.',
    `reading_type` STRING COMMENT 'Vital type measured (heart_rate, glucose, spo2, weight, blood_pressure).',
    `reading_unit` STRING COMMENT '',
    `reading_value` DECIMAL(18,2) COMMENT '',
    `received_timestamp` TIMESTAMP COMMENT 'Timestamp when the reading was received by the RPM platform.',
    `respiratory_rate_bpm` DECIMAL(18,2) COMMENT 'Respiratory rate in breaths per minute.',
    `reviewed_flag` BOOLEAN COMMENT '',
    `reviewed_timestamp` TIMESTAMP COMMENT '',
    `spo2_percent` DECIMAL(18,2) COMMENT 'Peripheral oxygen saturation percentage; populated when measurement_type=spo2.',
    `systolic_bp` STRING COMMENT '',
    `systolic_mmhg` DECIMAL(18,2) COMMENT 'Systolic blood pressure in mmHg.',
    `temperature_celsius` DECIMAL(18,2) COMMENT 'Body temperature in degrees Celsius.',
    `transmission_method` STRING COMMENT 'How the reading was transmitted: bluetooth, cellular, wifi, manual_entry.',
    `updated_timestamp` TIMESTAMP COMMENT 'Record last-updated timestamp.',
    `weight_kg` DECIMAL(18,2) COMMENT 'Body weight in kilograms; populated when measurement_type=weight.',
    CONSTRAINT pk_digital_health_rpm_device_reading PRIMARY KEY(`digital_health_rpm_device_reading_id`)
) COMMENT 'Stores individual sensor/device readings from Remote Patient Monitoring (RPM) devices including heart rate, glucose, SpO2, and weight. Each row represents a single measurement event transmitted from a patient-connected device.';

CREATE OR REPLACE TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` (
    `digital_health_rpm_program_enrollment_id` BIGINT COMMENT 'Surrogate primary key for the RPM program enrollment record.',
    `employee_id` BIGINT COMMENT 'FK to the care manager or nurse assigned to monitor this enrollment.',
    `care_program_enrollment_id` BIGINT COMMENT 'FK to the broader care program enrollment if RPM is part of a care management program.',
    `care_site_id` BIGINT COMMENT 'FK to the care site managing the RPM program.',
    `demographics_id` BIGINT COMMENT '',
    `insurance_coverage_id` BIGINT COMMENT 'FK to the insurance coverage used for RPM billing.',
    `mpi_record_id` BIGINT COMMENT 'FK to patient MPI record.',
    `clinician_id` BIGINT COMMENT 'FK to the ordering/supervising clinician.',
    `rpm_enrolling_clinician_id` BIGINT COMMENT '',
    `patient_rpm_alert_threshold_id` BIGINT COMMENT 'Default alert threshold set applied to this enrollment.',
    `adherence_rate` DECIMAL(18,2) COMMENT '',
    `billing_code` STRING COMMENT 'CPT/HCPCS code used for RPM billing.',
    `billing_eligible_flag` BOOLEAN COMMENT '',
    `billing_month` STRING COMMENT 'Billing month in YYYY-MM format for monthly RPM billing cycle tracking.',
    `billing_threshold_met_flag` BOOLEAN COMMENT 'Whether the minimum reading threshold for billing has been met this month.',
    `condition_managed` STRING COMMENT '',
    `consent_date` DATE COMMENT 'Date RPM consent was obtained.',
    `consent_document_reference` STRING COMMENT 'Reference to the consent document in the document management system.',
    `consent_obtained_flag` BOOLEAN COMMENT 'Whether informed consent for RPM monitoring was obtained.',
    `cpt_code_primary` STRING COMMENT 'Primary CPT billing code for the RPM program (e.g., 99453, 99454, 99457, 99458).',
    `created_timestamp` TIMESTAMP COMMENT 'Record creation timestamp.',
    `device_identifier` STRING COMMENT 'Primary device UDI or serial number assigned at enrollment.',
    `device_issued_date` DATE COMMENT 'Date devices were issued to patient.',
    `device_issued_flag` BOOLEAN COMMENT 'Whether monitoring devices were issued.',
    `device_type_list` STRING COMMENT 'Comma-separated list of device types assigned to this enrollment.',
    `disenrollment_date` DATE COMMENT 'Date the patient was disenrolled or completed the program.',
    `disenrollment_reason` STRING COMMENT 'Reason for disenrollment: completed, patient_withdrew, non_compliant, deceased, insurance_denied.',
    `enrollment_date` DATE COMMENT 'Date the patient was enrolled in the RPM program.',
    `enrollment_status` STRING COMMENT 'Current enrollment status: active, paused, completed, withdrawn, pending.',
    `escalation_count` STRING COMMENT 'Number of times readings triggered escalation to clinical staff.',
    `expected_reading_frequency` STRING COMMENT '',
    `last_clinician_review_date` DATE COMMENT 'Date the supervising clinician last reviewed the RPM data.',
    `last_reading_date` DATE COMMENT 'Date of the most recent device reading received.',
    `minimum_readings_per_month` STRING COMMENT 'Minimum number of readings required per month for billing compliance (CMS requires 16 days/month for CPT 99454).',
    `monitoring_duration_days` DECIMAL(18,2) COMMENT 'Total planned duration of the RPM program in days.',
    `monitoring_frequency` STRING COMMENT 'Expected reading cadence (daily, twice daily).',
    `monitoring_frequency_days` STRING COMMENT 'Expected frequency of readings in days (e.g., 1 = daily).',
    `monthly_reimbursement_amount` DECIMAL(18,2) COMMENT '',
    `next_review_date` DATE COMMENT 'Scheduled date for the next clinician review of RPM data.',
    `patient_compliance_rate` DECIMAL(18,2) COMMENT 'Percentage of expected readings actually received, indicating patient compliance.',
    `primary_diagnosis_icd10` STRING COMMENT 'Primary ICD-10 diagnosis code justifying RPM enrollment.',
    `program_name` STRING COMMENT 'Name of the RPM program (e.g., Cardiac RPM, Diabetes RPM, Hypertension Management).',
    `program_type` STRING COMMENT 'Type of RPM program: chronic_disease_management, post_discharge, preventive, oncology.',
    `readings_this_month` STRING COMMENT 'Count of qualifying readings received in the current billing month.',
    `updated_timestamp` TIMESTAMP COMMENT 'Record last-updated timestamp.',
    CONSTRAINT pk_digital_health_rpm_program_enrollment PRIMARY KEY(`digital_health_rpm_program_enrollment_id`)
) COMMENT 'Tracks patient enrollment in Remote Patient Monitoring (RPM) programs, including the devices assigned, monitoring parameters, billing codes, and program lifecycle dates.';

CREATE OR REPLACE TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` (
    `digital_health_rpm_alert_threshold_id` BIGINT COMMENT 'Surrogate primary key for the alert threshold rule.',
    `care_site_id` BIGINT COMMENT 'FK to the care site that owns this threshold configuration.',
    `mpi_record_id` BIGINT COMMENT 'FK to patient MPI record; NULL for program-level defaults.',
    `clinician_id` BIGINT COMMENT 'FK to the clinician who approved this threshold configuration.',
    `rpm_clinician_id` BIGINT COMMENT 'FK to the clinician who configured or approved this threshold.',
    `rpm_created_by_clinician_id` BIGINT COMMENT 'FK to the clinician who created this threshold.',
    `rpm_notify_clinician_id` BIGINT COMMENT '',
    `digital_health_rpm_program_enrollment_id` BIGINT COMMENT 'FK to the specific patient enrollment this threshold applies to; NULL if it is a program-level default.',
    `rpm_set_by_clinician_id` BIGINT COMMENT 'Clinician who configured the threshold.',
    `alert_notification_method` STRING COMMENT 'How alerts are delivered: in_app, sms, email, phone_call, ehr_inbox.',
    `alert_recipient_role` STRING COMMENT 'Role of the alert recipient: care_manager, attending_physician, on_call_nurse.',
    `alert_severity` STRING COMMENT 'Severity assigned when threshold is breached.',
    `alert_severity_lower_critical` STRING COMMENT 'Alert severity label for lower critical breach: critical, high, medium, low.',
    `alert_severity_upper_critical` STRING COMMENT 'Alert severity label for upper critical breach.',
    `clinical_rationale` DECIMAL(18,2) COMMENT 'Free-text clinical rationale for the threshold values.',
    `consecutive_readings_required` STRING COMMENT 'Number of consecutive out-of-range readings required before triggering an alert (reduces false positives).',
    `created_timestamp` TIMESTAMP COMMENT 'Record creation timestamp.',
    `effective_end_date` DATE COMMENT 'Date this threshold rule expires or was superseded.',
    `effective_start_date` DATE COMMENT 'Date this threshold rule became effective.',
    `escalation_rule` STRING COMMENT '',
    `high_critical_value` DECIMAL(18,2) COMMENT '',
    `high_warning_value` DECIMAL(18,2) COMMENT '',
    `is_active` BOOLEAN COMMENT 'Whether this threshold rule is currently active.',
    `is_active_flag` BOOLEAN COMMENT '',
    `loinc_code` STRING COMMENT '',
    `low_critical_value` DECIMAL(18,2) COMMENT '',
    `low_warning_value` DECIMAL(18,2) COMMENT '',
    `lower_critical_value` DECIMAL(18,2) COMMENT 'Lower critical threshold; readings below this value trigger a critical alert.',
    `lower_warning_value` DECIMAL(18,2) COMMENT 'Lower warning threshold; readings below this value trigger a warning alert.',
    `measurement_type` STRING COMMENT 'Measurement type this threshold applies to: heart_rate, glucose, spo2, weight, blood_pressure_systolic, blood_pressure_diastolic, temperature, respiratory_rate.',
    `measurement_unit` STRING COMMENT 'Unit of measure for the threshold values (e.g., bpm, mg/dL, %, kg, mmHg).',
    `reading_type` STRING COMMENT 'Vital type the threshold governs.',
    `suppression_window_minutes` STRING COMMENT 'Minimum minutes between repeated alerts for the same threshold breach to prevent alert fatigue.',
    `threshold_scope` STRING COMMENT 'Scope of the threshold: patient_specific or program_default.',
    `threshold_unit` STRING COMMENT 'Unit of measure for threshold bounds.',
    `unit` STRING COMMENT '',
    `updated_timestamp` TIMESTAMP COMMENT 'Record last-updated timestamp.',
    `upper_critical_value` DECIMAL(18,2) COMMENT 'Upper critical threshold; readings above this value trigger a critical alert.',
    `upper_warning_value` DECIMAL(18,2) COMMENT 'Upper warning threshold; readings above this value trigger a warning alert.',
    CONSTRAINT pk_digital_health_rpm_alert_threshold PRIMARY KEY(`digital_health_rpm_alert_threshold_id`)
) COMMENT 'Defines alert threshold rules for RPM device readings. Each row specifies the upper/lower bounds for a measurement type that, when exceeded, trigger clinical alerts for a patient or program.';

CREATE OR REPLACE TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` (
    `digital_health_prom_response_id` BIGINT COMMENT 'Surrogate primary key for the PROM response record.',
    `baseline_response_id` BIGINT COMMENT 'Self-referential FK to the baseline PROM response for longitudinal comparison.',
    `care_site_id` BIGINT COMMENT 'FK to the care site associated with this PROM collection.',
    `clinician_id` BIGINT COMMENT 'FK to the clinician who ordered or is associated with this PROM.',
    `demographics_id` BIGINT COMMENT '',
    `fhir_resource_log_id` BIGINT COMMENT 'FHIR QuestionnaireResponse resource ID for interoperability.',
    `mpi_record_id` BIGINT COMMENT 'FK to patient MPI record.',
    `digital_health_rpm_program_enrollment_id` BIGINT COMMENT 'FK to RPM enrollment if PROM is part of an RPM program.',
    `scheduling_appointment_id` BIGINT COMMENT 'FK to the appointment associated with this PROM collection.',
    `visit_id` BIGINT COMMENT 'FK to the encounter during which the PROM was collected, if applicable.',
    `administered_timestamp` TIMESTAMP COMMENT 'When the PROM was administered.',
    `administration_method` STRING COMMENT '',
    `administration_mode` STRING COMMENT 'How the PROM was administered (portal, tablet, phone).',
    `alert_triggered_flag` BOOLEAN COMMENT 'Whether the PROM score triggered a clinical alert (e.g., PHQ-9 >= 10 triggers depression follow-up).',
    `alert_type` STRING COMMENT 'Type of alert triggered: depression_screen_positive, suicide_risk, functional_decline, pain_escalation.',
    `assessment_date` DATE COMMENT '',
    `collection_date` DATE COMMENT 'Date the PROM was completed.',
    `collection_method` STRING COMMENT 'How the PROM was collected: patient_portal, tablet_kiosk, phone_ivr, paper_scan, rpm_app, email_link.',
    `collection_setting` STRING COMMENT 'Setting of collection: pre_visit, post_visit, remote, inpatient, post_discharge.',
    `collection_timestamp` TIMESTAMP COMMENT 'Timestamp when the patient completed the PROM.',
    `completed_timestamp` TIMESTAMP COMMENT 'When the patient completed the PROM.',
    `completion_rate_pct` DECIMAL(18,2) COMMENT 'Percentage of questions answered (for partial responses).',
    `completion_status` STRING COMMENT '',
    `created_timestamp` TIMESTAMP COMMENT 'Record creation timestamp.',
    `domain_fatigue_score` DECIMAL(18,2) COMMENT 'Domain-specific score for fatigue subscale.',
    `domain_mental_health_score` DECIMAL(18,2) COMMENT 'Domain-specific score for mental health subscale.',
    `domain_pain_score` DECIMAL(18,2) COMMENT 'Domain-specific score for pain subscale.',
    `domain_physical_function_score` DECIMAL(18,2) COMMENT 'Domain-specific score for physical function subscale.',
    `domain_social_participation_score` DECIMAL(18,2) COMMENT 'Domain-specific score for social participation subscale.',
    `follow_up_completed_flag` BOOLEAN COMMENT 'Whether the required follow-up was completed.',
    `follow_up_required_flag` BOOLEAN COMMENT 'Whether clinical follow-up is required based on the PROM score.',
    `gad7_total_score` STRING COMMENT 'GAD-7 total score (0-21); populated when instrument_name=GAD-7.',
    `instrument_category` STRING COMMENT 'Category of PROM: generic_hrqol, disease_specific, functional_status, mental_health, pain, satisfaction.',
    `instrument_code` STRING COMMENT 'PROM instrument code (e.g. PROMIS-29).',
    `instrument_loinc_code` STRING COMMENT 'LOINC panel code for the PROM instrument.',
    `instrument_name` STRING COMMENT 'Name of the PROM instrument (e.g., PROMIS-29, KOOS, HOOS, VR-12, PHQ-9, GAD-7, DASH, ODI).',
    `instrument_version` STRING COMMENT 'Version of the PROM instrument used.',
    `language_code` STRING COMMENT 'Language in which the PROM was administered.',
    `loinc_code` STRING COMMENT '',
    `mcid_threshold_met_flag` BOOLEAN COMMENT 'Whether the score change meets the Minimal Clinically Important Difference (MCID) threshold.',
    `phq9_total_score` STRING COMMENT 'PHQ-9 total score (0-27); populated when instrument_name=PHQ-9.',
    `proxy_completed_flag` BOOLEAN COMMENT 'Whether the PROM was completed by a proxy (caregiver) rather than the patient.',
    `question_code` STRING COMMENT '',
    `question_text` STRING COMMENT '',
    `raw_score` DECIMAL(18,2) COMMENT 'Computed raw score for the response/instrument.',
    `response_numeric_score` DECIMAL(18,2) COMMENT '',
    `response_status` STRING COMMENT 'Status of the PROM response: completed, partial, not_started, expired, declined.',
    `response_timestamp` TIMESTAMP COMMENT '',
    `response_value` DECIMAL(18,2) COMMENT '',
    `score_change_from_baseline` DECIMAL(18,2) COMMENT 'Change in score from the patients baseline PROM for this instrument.',
    `score_interpretation` STRING COMMENT 'Clinical interpretation of the score: normal, mild, moderate, severe, minimal.',
    `t_score` DECIMAL(18,2) COMMENT 'T-score (standardized score with mean=50, SD=10) for PROMIS instruments.',
    `total_score` DECIMAL(18,2) COMMENT 'Total or summary score for the PROM instrument.',
    `updated_timestamp` TIMESTAMP COMMENT 'Record last-updated timestamp.',
    CONSTRAINT pk_digital_health_prom_response PRIMARY KEY(`digital_health_prom_response_id`)
) COMMENT 'Stores Patient-Reported Outcome Measure (PROM) responses. Each row represents a patients response to a validated PROM instrument (e.g., PROMIS, KOOS, HOOS, VR-12, PHQ-9, GAD-7) at a specific point in time.';

CREATE OR REPLACE TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` (
    `digital_health_portal_engagement_event_id` BIGINT COMMENT 'Surrogate primary key for the portal engagement event.',
    `care_site_id` BIGINT COMMENT 'FK to the care site context of the engagement event.',
    `communication_campaign_id` BIGINT COMMENT 'FK to the communication campaign that drove this portal engagement.',
    `demographics_id` BIGINT COMMENT '',
    `clinician_id` BIGINT COMMENT 'FK to the clinician who received or sent the portal message.',
    `secure_message_thread_id` BIGINT COMMENT 'Identifier of the secure message thread, if event_type is message-related.',
    `mpi_record_id` BIGINT COMMENT 'FK to patient MPI record.',
    `portal_account_id` BIGINT COMMENT 'FK to the patient portal account that generated this event.',
    `digital_health_prom_response_id` BIGINT COMMENT 'FK to the PROM response if event_type=prom_completed.',
    `proxy_access_id` BIGINT COMMENT 'FK to the proxy access record if this was a proxy session.',
    `digital_health_rpm_device_reading_id` BIGINT COMMENT 'FK to the RPM reading if event_type=rpm_data_viewed.',
    `scheduling_appointment_id` BIGINT COMMENT 'FK to the appointment if the event is appointment-related.',
    `portal_session_id` BIGINT COMMENT 'Portal session identifier grouping multiple events in a single user session.',
    `lab_order_id` BIGINT COMMENT 'FK to the lab order whose result was viewed.',
    `visit_id` BIGINT COMMENT 'FK to the encounter associated with this event, if applicable.',
    `appointment_action_flag` BOOLEAN COMMENT '',
    `bill_pay_action_flag` BOOLEAN COMMENT '',
    `browser_type` STRING COMMENT 'Browser or app version used to access the portal.',
    `channel` STRING COMMENT '',
    `created_timestamp` TIMESTAMP COMMENT 'Record creation timestamp in the data lakehouse.',
    `device_type` STRING COMMENT 'Device type used to access the portal: desktop, mobile_web, ios_app, android_app, tablet.',
    `document_type` STRING COMMENT 'Type of document uploaded or downloaded: after_visit_summary, lab_result, imaging_report, care_plan, insurance_card.',
    `duration_seconds` STRING COMMENT '',
    `error_code` STRING COMMENT 'Error code if event_status=failed.',
    `error_description` STRING COMMENT 'Description of the error if event_status=failed.',
    `event_category` STRING COMMENT 'High-level category: authentication, messaging, scheduling, clinical_data, billing, documents, prom, rpm, account_management.',
    `event_date` DATE COMMENT 'Calendar date of the event for partitioning and daily aggregation.',
    `event_status` STRING COMMENT 'Outcome of the event: success, failed, abandoned, timeout.',
    `event_timestamp` TIMESTAMP COMMENT 'Timestamp when the portal engagement event occurred.',
    `event_type` STRING COMMENT 'Type of portal engagement event: login, logout, message_sent, message_read, appointment_scheduled, appointment_cancelled, appointment_rescheduled, test_result_viewed, medication_list_viewed, care_plan_viewed, rx_renewal_requested, bill_paid, bill_viewed, document_uploaded, document_downloaded, prom_completed, rpm_data_viewed, proxy_access_used, account_settings_updated, notification_preference_updated.',
    `feature_name` STRING COMMENT 'Specific feature or module used (e.g., MyChart Messaging, Test Results, Appointments).',
    `ip_address` STRING COMMENT '',
    `ip_address_hash` STRING COMMENT 'Hashed IP address for security auditing without storing raw PII.',
    `is_proxy_session` BOOLEAN COMMENT 'Whether the session was conducted by a proxy/delegate rather than the patient.',
    `message_sent_flag` BOOLEAN COMMENT '',
    `notification_channel` STRING COMMENT 'Channel through which the patient was notified to take this portal action: email, sms, push_notification, none.',
    `page_name` STRING COMMENT 'Name of the portal page or feature where the event occurred.',
    `page_or_feature` STRING COMMENT '',
    `result_viewed_flag` BOOLEAN COMMENT '',
    `session_duration_seconds` DECIMAL(18,2) COMMENT 'Duration of the portal session in seconds.',
    `session_end_timestamp` TIMESTAMP COMMENT 'Timestamp when the portal session ended.',
    `session_start_timestamp` TIMESTAMP COMMENT 'Timestamp when the portal session started.',
    `success_flag` BOOLEAN COMMENT 'Whether the interaction succeeded.',
    `updated_timestamp` TIMESTAMP COMMENT 'Record last-updated timestamp.',
    CONSTRAINT pk_digital_health_portal_engagement_event PRIMARY KEY(`digital_health_portal_engagement_event_id`)
) COMMENT 'Captures patient portal engagement events and metrics. Each row represents a discrete patient interaction with the patient portal (e.g., login, message sent, appointment scheduled, test result viewed, prescription renewal requested), enabling engagement analytics and outreach optimization.';

CREATE OR REPLACE TABLE `vibe_healthcare_v1`.`digital_health`.`rpm_enrollment` (
    `rpm_enrollment_id` BIGINT COMMENT 'Primary key for rpm_enrollment',
    `digital_health_rpm_program_enrollment_id` BIGINT COMMENT 'Foreign key linking to digital_health.digital_health_rpm_program_enrollment. Business justification: rpm_enrollment is a completely siloed table containing only its PK with no inbound or outbound FK. It is described as RPM program enrollment and alert thresholds, which is the same business concept ',
    CONSTRAINT pk_rpm_enrollment PRIMARY KEY(`rpm_enrollment_id`)
) COMMENT 'RPM program enrollment and alert thresholds';

CREATE OR REPLACE TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` (
    `portal_session_id` BIGINT COMMENT 'Primary key for portal_session',
    `care_site_id` BIGINT COMMENT 'Reference to the health system facility or organization context associated with the portal session.',
    `mpi_record_id` BIGINT COMMENT 'Reference to the patient master record (MPI) for whom this portal session was established.',
    `portal_account_id` BIGINT COMMENT 'Reference to the portal user account that authenticated for this session (may be patient, proxy, or caregiver).',
    `previous_portal_session_id` BIGINT COMMENT 'Self-referencing FK on portal_session (previous_portal_session_id)',
    `access_channel` STRING COMMENT 'The interface channel through which the portal was accessed (distinct from device type).',
    `authentication_method` STRING COMMENT 'The mechanism used to authenticate the user at session start.',
    `browser_name` STRING COMMENT 'Web browser name and version used for the portal session, where applicable.',
    `consent_acknowledged_flag` BOOLEAN COMMENT 'Indicates whether required terms-of-use or privacy consent was acknowledged during the session.',
    `device_identifier` STRING COMMENT 'Unique identifier of the device used for the session, supporting trusted-device and fraud-detection workflows.',
    `device_type` STRING COMMENT 'Category of physical device used to access the patient portal.',
    `failed_login_attempts` STRING COMMENT 'Number of failed authentication attempts preceding this successful session, supporting security monitoring.',
    `geo_country` STRING COMMENT 'ISO 3166-1 alpha-3 country code derived from the session source IP for access-pattern monitoring.',
    `geo_region` STRING COMMENT 'State, province, or region inferred from the session source IP location.',
    `ip_address` STRING COMMENT 'Source IP address from which the portal session originated, used for access auditing and geolocation.',
    `last_activity_timestamp` TIMESTAMP COMMENT 'Timestamp of the most recent user interaction within the session, used to enforce inactivity timeout policies.',
    `locale_preference` STRING COMMENT 'Language and locale setting (e.g., en-US, es-US) used during the portal session for accessibility and personalization.',
    `login_timestamp` TIMESTAMP COMMENT 'The principal real-world event time when the portal session was initiated via successful authentication.',
    `logout_timestamp` TIMESTAMP COMMENT 'Timestamp when the session was explicitly ended by the user via logout. Nullable for sessions ended by timeout or system.',
    `mfa_completed` BOOLEAN COMMENT 'Indicates whether multi-factor authentication was successfully completed during this session.',
    `operating_system` STRING COMMENT 'Operating system and version reported by the accessing device.',
    `page_view_count` STRING COMMENT 'Number of distinct portal pages or screens viewed during the session, supporting engagement analytics.',
    `phi_accessed_flag` BOOLEAN COMMENT 'Indicates whether Protected Health Information was viewed or accessed during this session, driving HIPAA audit logging.',
    `primary_activity_type` STRING COMMENT 'The dominant functional activity the user performed during the session.',
    `proxy_access_flag` BOOLEAN COMMENT 'Indicates whether the session was conducted by an authorized proxy (e.g., parent, guardian, caregiver) rather than the patient directly.',
    `proxy_relationship` STRING COMMENT 'The relationship of the acting user to the patient when proxy access is used.',
    `session_created_timestamp` TIMESTAMP COMMENT 'Timestamp when the session record was first captured in the system.',
    `session_duration_seconds` STRING COMMENT 'Total elapsed time in seconds between login and session termination, supporting engagement and access analytics.',
    `session_expiry_timestamp` TIMESTAMP COMMENT 'Timestamp at which the session token expires and re-authentication is required.',
    `session_status` STRING COMMENT 'Current lifecycle state of the portal session.',
    `session_token` STRING COMMENT 'Opaque externally-issued session token / business key used to reference this portal session across systems.',
    `session_updated_timestamp` TIMESTAMP COMMENT 'Timestamp when the session record was last modified.',
    `termination_reason` STRING COMMENT 'The business reason the session ended, supporting security and user-experience analysis.',
    `user_agent` STRING COMMENT 'Full user-agent header captured from the client, supporting compatibility and security analytics.',
    CONSTRAINT pk_portal_session PRIMARY KEY(`portal_session_id`)
) COMMENT 'Master reference table for portal_session. Referenced by session_id.';

CREATE OR REPLACE TABLE `vibe_healthcare_v1`.`digital_health`.`secure_message_thread` (
    `secure_message_thread_id` BIGINT COMMENT 'Primary key for secure_message_thread',
    `care_site_id` BIGINT COMMENT 'Identifier of the facility or practice location that owns or routes the messaging thread within a multi-facility health system.',
    `care_team_id` BIGINT COMMENT 'Identifier of the care team the thread is routed to, enabling shared-inbox group messaging and coverage.',
    `clinician_id` BIGINT COMMENT 'Identifier of the clinician or care team member currently responsible for responding to the thread.',
    `employee_id` BIGINT COMMENT 'Identifier of the party (patient, provider, or care team member) who originated the conversation thread.',
    `mpi_record_id` BIGINT COMMENT 'Identifier of the patient who is the subject of and a participant in the secure messaging thread.',
    `visit_id` BIGINT COMMENT 'Identifier of the clinical encounter that this messaging thread is associated with or arose from, if any.',
    `parent_secure_message_thread_id` BIGINT COMMENT 'Self-referencing FK on secure_message_thread (parent_secure_message_thread_id)',
    `channel` STRING COMMENT 'The interface/channel through which the secure conversation is conducted.',
    `closed_reason` STRING COMMENT 'Categorical reason describing why the thread was closed, supporting quality and operations reporting.',
    `consent_on_file` BOOLEAN COMMENT 'Indicates whether documented patient consent for secure electronic messaging is on file, required for compliant communication.',
    `created_at` TIMESTAMP COMMENT 'Timestamp when this thread record was first captured in the source system.',
    `escalation_status` STRING COMMENT 'Current escalation state of the thread when response SLAs are at risk or breached, supporting triage workflows.',
    `first_response_at` TIMESTAMP COMMENT 'Timestamp of the first provider response, used to measure response time against patient-engagement SLAs.',
    `has_attachment` BOOLEAN COMMENT 'Indicates whether any message in the thread includes a file attachment such as a document or image.',
    `is_archived` BOOLEAN COMMENT 'Indicates whether the thread has been archived out of active inboxes while retained for compliance.',
    `is_clinical` BOOLEAN COMMENT 'Indicates whether the thread contains clinical content requiring licensed clinician review versus purely administrative content.',
    `language_code` STRING COMMENT 'ISO 639-1 language code of the conversation, supporting patient communication preferences and interpreter needs.',
    `last_message_at` TIMESTAMP COMMENT 'Timestamp of the most recent message in the thread, used for inbox sorting and stale-thread detection.',
    `message_count` STRING COMMENT 'Total number of individual messages exchanged within the thread, used for engagement and workload analytics.',
    `opened_at` TIMESTAMP COMMENT 'Timestamp when the secure conversation thread was first opened/initiated.',
    `priority` STRING COMMENT 'Clinical priority assigned to the thread, influencing response SLA and provider triage queues.',
    `requires_response` BOOLEAN COMMENT 'Flags whether an outstanding response is awaited from a provider, used for SLA monitoring and escalation.',
    `resolved_at` TIMESTAMP COMMENT 'Timestamp when the thread was marked resolved or closed by the responsible clinician.',
    `response_due_at` TIMESTAMP COMMENT 'Timestamp by which a response is required to meet the service-level commitment for the assigned priority.',
    `retention_expiry_date` DATE COMMENT 'Date when the thread becomes eligible for purge under the applicable HIPAA medical-record retention policy.',
    `sensitivity_level` STRING COMMENT 'Confidentiality sensitivity classification controlling who may view the thread (e.g., behavioral health, HIV, substance use special protections).',
    `subject_category` STRING COMMENT 'Standardized clinical or administrative topic of the thread used for routing and reporting. [ENUM-REF-CANDIDATE: medication|symptom|lab_result|referral|insurance|scheduling|general_question|test_results|care_plan — promote to reference product]',
    `thread_reference_number` STRING COMMENT 'Externally-known human-facing reference number for the conversation, surfaced in the patient portal and clinician inbox for cross-system traceability.',
    `thread_status` STRING COMMENT 'Current state of the conversation within its lifecycle, used for inbox triage and SLA tracking.',
    `thread_subject` STRING COMMENT 'Human-readable subject or title of the secure message conversation; may reference clinical context and is therefore treated as PHI under HIPAA.',
    `thread_type` STRING COMMENT 'Categorical classification segmenting threads by their primary business purpose to drive routing and analytics.',
    `unread_count` STRING COMMENT 'Number of unread messages in the thread for the currently responsible recipient, driving inbox notification badges.',
    `updated_at` TIMESTAMP COMMENT 'Timestamp when this thread record was last modified in the source system.',
    CONSTRAINT pk_secure_message_thread PRIMARY KEY(`secure_message_thread_id`)
) COMMENT 'Master reference table for secure_message_thread. Referenced by message_thread_id.';

-- ========= FOREIGN KEYS =========
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ADD CONSTRAINT `fk_digital_health_digital_health_rpm_device_reading_digital_health_rpm_alert_threshold_id` FOREIGN KEY (`digital_health_rpm_alert_threshold_id`) REFERENCES `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold`(`digital_health_rpm_alert_threshold_id`);
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ADD CONSTRAINT `fk_digital_health_digital_health_rpm_device_reading_rpm_alert_threshold_id` FOREIGN KEY (`rpm_alert_threshold_id`) REFERENCES `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold`(`digital_health_rpm_alert_threshold_id`);
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ADD CONSTRAINT `fk_digital_health_digital_health_rpm_device_reading_digital_health_rpm_program_enrollment_id` FOREIGN KEY (`digital_health_rpm_program_enrollment_id`) REFERENCES `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment`(`digital_health_rpm_program_enrollment_id`);
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ADD CONSTRAINT `fk_digital_health_digital_health_rpm_alert_threshold_digital_health_rpm_program_enrollment_id` FOREIGN KEY (`digital_health_rpm_program_enrollment_id`) REFERENCES `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment`(`digital_health_rpm_program_enrollment_id`);
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ADD CONSTRAINT `fk_digital_health_digital_health_prom_response_baseline_response_id` FOREIGN KEY (`baseline_response_id`) REFERENCES `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response`(`digital_health_prom_response_id`);
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ADD CONSTRAINT `fk_digital_health_digital_health_prom_response_digital_health_rpm_program_enrollment_id` FOREIGN KEY (`digital_health_rpm_program_enrollment_id`) REFERENCES `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment`(`digital_health_rpm_program_enrollment_id`);
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ADD CONSTRAINT `fk_digital_health_digital_health_portal_engagement_event_secure_message_thread_id` FOREIGN KEY (`secure_message_thread_id`) REFERENCES `vibe_healthcare_v1`.`digital_health`.`secure_message_thread`(`secure_message_thread_id`);
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ADD CONSTRAINT `fk_digital_health_digital_health_portal_engagement_event_digital_health_prom_response_id` FOREIGN KEY (`digital_health_prom_response_id`) REFERENCES `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response`(`digital_health_prom_response_id`);
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ADD CONSTRAINT `fk_digital_health_digital_health_portal_engagement_event_digital_health_rpm_device_reading_id` FOREIGN KEY (`digital_health_rpm_device_reading_id`) REFERENCES `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading`(`digital_health_rpm_device_reading_id`);
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ADD CONSTRAINT `fk_digital_health_digital_health_portal_engagement_event_portal_session_id` FOREIGN KEY (`portal_session_id`) REFERENCES `vibe_healthcare_v1`.`digital_health`.`portal_session`(`portal_session_id`);
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`rpm_enrollment` ADD CONSTRAINT `fk_digital_health_rpm_enrollment_digital_health_rpm_program_enrollment_id` FOREIGN KEY (`digital_health_rpm_program_enrollment_id`) REFERENCES `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment`(`digital_health_rpm_program_enrollment_id`);
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ADD CONSTRAINT `fk_digital_health_portal_session_previous_portal_session_id` FOREIGN KEY (`previous_portal_session_id`) REFERENCES `vibe_healthcare_v1`.`digital_health`.`portal_session`(`portal_session_id`);
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`secure_message_thread` ADD CONSTRAINT `fk_digital_health_secure_message_thread_parent_secure_message_thread_id` FOREIGN KEY (`parent_secure_message_thread_id`) REFERENCES `vibe_healthcare_v1`.`digital_health`.`secure_message_thread`(`secure_message_thread_id`);

-- ========= TAGS =========
ALTER SCHEMA `vibe_healthcare_v1`.`digital_health` SET TAGS ('pii_division' = 'operations');
ALTER SCHEMA `vibe_healthcare_v1`.`digital_health` SET TAGS ('pii_domain' = 'digital_health');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` SET TAGS ('pii_data_type' = 'transactional_data');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` SET TAGS ('pii_subdomain' = 'remote_monitoring');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` SET TAGS ('pii_domain' = 'digital_health');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` SET TAGS ('pii_tier' = 'ecm');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `digital_health_rpm_device_reading_id` SET TAGS ('pii_business_glossary_term' = 'Rpm Device Reading Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `digital_health_rpm_device_reading_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `digital_health_rpm_device_reading_id` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `care_site_id` SET TAGS ('pii_business_glossary_term' = 'Care Site Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `demographics_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `demographics_id` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `observation_id` SET TAGS ('pii_business_glossary_term' = 'Fhir Observation Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `observation_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `observation_id` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_business_glossary_term' = 'Mpi Record Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_sensitivity' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `rpm_alert_threshold_id` SET TAGS ('pii_business_glossary_term' = 'Alert Threshold Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `clinician_id` SET TAGS ('pii_business_glossary_term' = 'Clinician Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `digital_health_rpm_program_enrollment_id` SET TAGS ('pii_business_glossary_term' = 'Rpm Program Enrollment Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `alert_acknowledged_by` SET TAGS ('pii_business_glossary_term' = 'Alert Acknowledged By');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `alert_acknowledged_flag` SET TAGS ('pii_business_glossary_term' = 'Alert Acknowledged Flag');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `alert_acknowledged_timestamp` SET TAGS ('pii_business_glossary_term' = 'Alert Acknowledged Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `alert_severity` SET TAGS ('pii_business_glossary_term' = 'Alert Severity');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `alert_triggered_flag` SET TAGS ('pii_business_glossary_term' = 'Alert Triggered Flag');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `context_code` SET TAGS ('pii_business_glossary_term' = 'Context Code');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `created_timestamp` SET TAGS ('pii_business_glossary_term' = 'Created Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `device_identifier` SET TAGS ('pii_business_glossary_term' = 'Device Identifier');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `device_manufacturer` SET TAGS ('pii_business_glossary_term' = 'Device Manufacturer');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `device_model` SET TAGS ('pii_business_glossary_term' = 'Device Model');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `device_serial_number` SET TAGS ('pii_internal' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `device_serial_number` SET TAGS ('pii_pii' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `device_type` SET TAGS ('pii_business_glossary_term' = 'Device Type');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `diastolic_bp` SET TAGS ('pii_sensitivity' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `diastolic_mmhg` SET TAGS ('pii_business_glossary_term' = 'Diastolic Mmhg');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `ehr_sync_timestamp` SET TAGS ('pii_business_glossary_term' = 'Ehr Sync Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `ehr_synced_flag` SET TAGS ('pii_business_glossary_term' = 'Ehr Synced Flag');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `glucose_mg_dl` SET TAGS ('pii_business_glossary_term' = 'Glucose Mg Dl');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `heart_rate_bpm` SET TAGS ('pii_business_glossary_term' = 'Heart Rate Bpm');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `loinc_code` SET TAGS ('pii_business_glossary_term' = 'Loinc Code');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `measurement_type` SET TAGS ('pii_business_glossary_term' = 'Measurement Type');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `measurement_unit` SET TAGS ('pii_business_glossary_term' = 'Measurement Unit');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `measurement_value` SET TAGS ('pii_business_glossary_term' = 'Measurement Value');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `notes` SET TAGS ('pii_business_glossary_term' = 'Notes');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `patient_reported_flag` SET TAGS ('pii_business_glossary_term' = 'Patient Reported Flag');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `patient_reported_flag` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `patient_reported_flag` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `reading_date` SET TAGS ('pii_business_glossary_term' = 'Reading Date');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `reading_quality_flag` SET TAGS ('pii_business_glossary_term' = 'Reading Quality Flag');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `reading_timestamp` SET TAGS ('pii_business_glossary_term' = 'Reading Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `reading_value` SET TAGS ('pii_sensitivity' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `received_timestamp` SET TAGS ('pii_business_glossary_term' = 'Received Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `respiratory_rate_bpm` SET TAGS ('pii_business_glossary_term' = 'Respiratory Rate Bpm');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `spo2_percent` SET TAGS ('pii_business_glossary_term' = 'Spo2 Percent');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `systolic_bp` SET TAGS ('pii_sensitivity' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `systolic_mmhg` SET TAGS ('pii_business_glossary_term' = 'Systolic Mmhg');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `temperature_celsius` SET TAGS ('pii_business_glossary_term' = 'Temperature Celsius');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `transmission_method` SET TAGS ('pii_business_glossary_term' = 'Transmission Method');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `updated_timestamp` SET TAGS ('pii_business_glossary_term' = 'Updated Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_device_reading` ALTER COLUMN `weight_kg` SET TAGS ('pii_business_glossary_term' = 'Weight Kg');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` SET TAGS ('pii_data_type' = 'transactional_data');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` SET TAGS ('pii_subdomain' = 'remote_monitoring');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` SET TAGS ('pii_domain' = 'digital_health');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` SET TAGS ('pii_tier' = 'ecm');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `digital_health_rpm_program_enrollment_id` SET TAGS ('pii_business_glossary_term' = 'Rpm Program Enrollment Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `digital_health_rpm_program_enrollment_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `digital_health_rpm_program_enrollment_id` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `employee_id` SET TAGS ('pii_business_glossary_term' = 'Care Manager Employee Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `employee_id` SET TAGS ('pii_confidential' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `employee_id` SET TAGS ('pii_pii' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `care_program_enrollment_id` SET TAGS ('pii_business_glossary_term' = 'Care Program Enrollment Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `care_site_id` SET TAGS ('pii_business_glossary_term' = 'Care Site Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `demographics_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `demographics_id` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `insurance_coverage_id` SET TAGS ('pii_business_glossary_term' = 'Insurance Coverage Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `insurance_coverage_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `insurance_coverage_id` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_business_glossary_term' = 'Mpi Record Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_sensitivity' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `clinician_id` SET TAGS ('pii_business_glossary_term' = 'Clinician Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `billing_month` SET TAGS ('pii_business_glossary_term' = 'Billing Month');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `billing_threshold_met_flag` SET TAGS ('pii_business_glossary_term' = 'Billing Threshold Met Flag');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `condition_managed` SET TAGS ('pii_sensitivity' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `consent_date` SET TAGS ('pii_business_glossary_term' = 'Consent Date');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `consent_date` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `consent_date` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `consent_document_reference` SET TAGS ('pii_business_glossary_term' = 'Consent Document Reference');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `consent_document_reference` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `consent_document_reference` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `consent_obtained_flag` SET TAGS ('pii_business_glossary_term' = 'Consent Obtained Flag');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `consent_obtained_flag` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `consent_obtained_flag` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `cpt_code_primary` SET TAGS ('pii_business_glossary_term' = 'Cpt Code Primary');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `created_timestamp` SET TAGS ('pii_business_glossary_term' = 'Created Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `device_identifier` SET TAGS ('pii_business_glossary_term' = 'Device Identifier');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `device_type_list` SET TAGS ('pii_business_glossary_term' = 'Device Type List');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `disenrollment_date` SET TAGS ('pii_business_glossary_term' = 'Disenrollment Date');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `disenrollment_reason` SET TAGS ('pii_business_glossary_term' = 'Disenrollment Reason');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `enrollment_date` SET TAGS ('pii_business_glossary_term' = 'Enrollment Date');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `enrollment_status` SET TAGS ('pii_business_glossary_term' = 'Enrollment Status');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `escalation_count` SET TAGS ('pii_business_glossary_term' = 'Escalation Count');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `last_clinician_review_date` SET TAGS ('pii_business_glossary_term' = 'Last Clinician Review Date');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `last_reading_date` SET TAGS ('pii_business_glossary_term' = 'Last Reading Date');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `minimum_readings_per_month` SET TAGS ('pii_business_glossary_term' = 'Minimum Readings Per Month');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `monitoring_duration_days` SET TAGS ('pii_business_glossary_term' = 'Monitoring Duration Days');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `monitoring_duration_days` SET TAGS ('pii_vibe_rate_typing' = 'decimal');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `monitoring_frequency_days` SET TAGS ('pii_business_glossary_term' = 'Monitoring Frequency Days');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `next_review_date` SET TAGS ('pii_business_glossary_term' = 'Next Review Date');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `patient_compliance_rate` SET TAGS ('pii_business_glossary_term' = 'Patient Compliance Rate');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `patient_compliance_rate` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `patient_compliance_rate` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `primary_diagnosis_icd10` SET TAGS ('pii_business_glossary_term' = 'Primary Diagnosis Icd10');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `primary_diagnosis_icd10` SET TAGS ('pii_restricted' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `primary_diagnosis_icd10` SET TAGS ('pii_health' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `primary_diagnosis_icd10` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `primary_diagnosis_icd10` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `program_name` SET TAGS ('pii_business_glossary_term' = 'Program Name');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `program_name` SET TAGS ('pii_pii' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `program_name` SET TAGS ('pii_uc_classification' = 'pii');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `program_type` SET TAGS ('pii_business_glossary_term' = 'Program Type');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `readings_this_month` SET TAGS ('pii_business_glossary_term' = 'Readings This Month');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_program_enrollment` ALTER COLUMN `updated_timestamp` SET TAGS ('pii_business_glossary_term' = 'Updated Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` SET TAGS ('pii_data_type' = 'reference_data');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` SET TAGS ('pii_subdomain' = 'remote_monitoring');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` SET TAGS ('pii_domain' = 'digital_health');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` SET TAGS ('pii_tier' = 'ecm');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `digital_health_rpm_alert_threshold_id` SET TAGS ('pii_business_glossary_term' = 'Rpm Alert Threshold Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `digital_health_rpm_alert_threshold_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `digital_health_rpm_alert_threshold_id` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `care_site_id` SET TAGS ('pii_business_glossary_term' = 'Care Site Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_business_glossary_term' = 'Mpi Record Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_sensitivity' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `clinician_id` SET TAGS ('pii_business_glossary_term' = 'Approved By Clinician Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `rpm_clinician_id` SET TAGS ('pii_business_glossary_term' = 'Clinician Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `rpm_created_by_clinician_id` SET TAGS ('pii_business_glossary_term' = 'Created By Clinician Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `digital_health_rpm_program_enrollment_id` SET TAGS ('pii_business_glossary_term' = 'Rpm Program Enrollment Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `alert_notification_method` SET TAGS ('pii_business_glossary_term' = 'Alert Notification Method');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `alert_recipient_role` SET TAGS ('pii_business_glossary_term' = 'Alert Recipient Role');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `alert_severity_lower_critical` SET TAGS ('pii_business_glossary_term' = 'Alert Severity Lower Critical');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `alert_severity_upper_critical` SET TAGS ('pii_business_glossary_term' = 'Alert Severity Upper Critical');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `clinical_rationale` SET TAGS ('pii_business_glossary_term' = 'Clinical Rationale');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `clinical_rationale` SET TAGS ('pii_vibe_rate_typing' = 'decimal');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `consecutive_readings_required` SET TAGS ('pii_business_glossary_term' = 'Consecutive Readings Required');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `created_timestamp` SET TAGS ('pii_business_glossary_term' = 'Created Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `effective_end_date` SET TAGS ('pii_business_glossary_term' = 'Effective End Date');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `effective_start_date` SET TAGS ('pii_business_glossary_term' = 'Effective Start Date');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `is_active` SET TAGS ('pii_business_glossary_term' = 'Is Active');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `lower_critical_value` SET TAGS ('pii_business_glossary_term' = 'Lower Critical Value');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `lower_warning_value` SET TAGS ('pii_business_glossary_term' = 'Lower Warning Value');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `measurement_type` SET TAGS ('pii_business_glossary_term' = 'Measurement Type');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `measurement_unit` SET TAGS ('pii_business_glossary_term' = 'Measurement Unit');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `suppression_window_minutes` SET TAGS ('pii_business_glossary_term' = 'Suppression Window Minutes');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `threshold_scope` SET TAGS ('pii_business_glossary_term' = 'Threshold Scope');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `updated_timestamp` SET TAGS ('pii_business_glossary_term' = 'Updated Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `upper_critical_value` SET TAGS ('pii_business_glossary_term' = 'Upper Critical Value');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_rpm_alert_threshold` ALTER COLUMN `upper_warning_value` SET TAGS ('pii_business_glossary_term' = 'Upper Warning Value');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` SET TAGS ('pii_data_type' = 'transactional_data');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` SET TAGS ('pii_subdomain' = 'patient_engagement');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` SET TAGS ('pii_domain' = 'digital_health');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` SET TAGS ('pii_tier' = 'ecm');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `digital_health_prom_response_id` SET TAGS ('pii_business_glossary_term' = 'Prom Response Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `digital_health_prom_response_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `digital_health_prom_response_id` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `baseline_response_id` SET TAGS ('pii_business_glossary_term' = 'Baseline Response Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `care_site_id` SET TAGS ('pii_business_glossary_term' = 'Care Site Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `clinician_id` SET TAGS ('pii_business_glossary_term' = 'Clinician Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `demographics_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `demographics_id` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `fhir_resource_log_id` SET TAGS ('pii_business_glossary_term' = 'Fhir Questionnaire Response Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_business_glossary_term' = 'Mpi Record Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_sensitivity' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `digital_health_rpm_program_enrollment_id` SET TAGS ('pii_business_glossary_term' = 'Rpm Program Enrollment Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `scheduling_appointment_id` SET TAGS ('pii_business_glossary_term' = 'Scheduling Appointment Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `visit_id` SET TAGS ('pii_business_glossary_term' = 'Visit Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `alert_triggered_flag` SET TAGS ('pii_business_glossary_term' = 'Alert Triggered Flag');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `alert_type` SET TAGS ('pii_business_glossary_term' = 'Alert Type');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `collection_date` SET TAGS ('pii_business_glossary_term' = 'Collection Date');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `collection_method` SET TAGS ('pii_business_glossary_term' = 'Collection Method');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `collection_setting` SET TAGS ('pii_business_glossary_term' = 'Collection Setting');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `collection_timestamp` SET TAGS ('pii_business_glossary_term' = 'Collection Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `completion_rate_pct` SET TAGS ('pii_business_glossary_term' = 'Completion Rate Pct');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `created_timestamp` SET TAGS ('pii_business_glossary_term' = 'Created Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `domain_fatigue_score` SET TAGS ('pii_business_glossary_term' = 'Domain Fatigue Score');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `domain_mental_health_score` SET TAGS ('pii_business_glossary_term' = 'Domain Mental Health Score');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `domain_mental_health_score` SET TAGS ('pii_restricted' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `domain_mental_health_score` SET TAGS ('pii_pii' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `domain_mental_health_score` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `domain_mental_health_score` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `domain_pain_score` SET TAGS ('pii_business_glossary_term' = 'Domain Pain Score');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `domain_physical_function_score` SET TAGS ('pii_business_glossary_term' = 'Domain Physical Function Score');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `domain_social_participation_score` SET TAGS ('pii_business_glossary_term' = 'Domain Social Participation Score');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `follow_up_completed_flag` SET TAGS ('pii_business_glossary_term' = 'Follow Up Completed Flag');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `follow_up_required_flag` SET TAGS ('pii_business_glossary_term' = 'Follow Up Required Flag');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `gad7_total_score` SET TAGS ('pii_business_glossary_term' = 'Gad7 Total Score');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `instrument_category` SET TAGS ('pii_business_glossary_term' = 'Instrument Category');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `instrument_loinc_code` SET TAGS ('pii_business_glossary_term' = 'Instrument Loinc Code');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `instrument_name` SET TAGS ('pii_business_glossary_term' = 'Instrument Name');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `instrument_name` SET TAGS ('pii_pii' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `instrument_name` SET TAGS ('pii_uc_classification' = 'pii');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `instrument_version` SET TAGS ('pii_business_glossary_term' = 'Instrument Version');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `language_code` SET TAGS ('pii_business_glossary_term' = 'Language Code');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `mcid_threshold_met_flag` SET TAGS ('pii_business_glossary_term' = 'Mcid Threshold Met Flag');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `phq9_total_score` SET TAGS ('pii_business_glossary_term' = 'Phq9 Total Score');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `proxy_completed_flag` SET TAGS ('pii_business_glossary_term' = 'Proxy Completed Flag');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `proxy_completed_flag` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `proxy_completed_flag` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `response_numeric_score` SET TAGS ('pii_sensitivity' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `response_status` SET TAGS ('pii_business_glossary_term' = 'Response Status');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `response_value` SET TAGS ('pii_sensitivity' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `score_change_from_baseline` SET TAGS ('pii_business_glossary_term' = 'Score Change From Baseline');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `score_interpretation` SET TAGS ('pii_business_glossary_term' = 'Score Interpretation');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `t_score` SET TAGS ('pii_business_glossary_term' = 'T Score');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `total_score` SET TAGS ('pii_business_glossary_term' = 'Total Score');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_prom_response` ALTER COLUMN `updated_timestamp` SET TAGS ('pii_business_glossary_term' = 'Updated Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` SET TAGS ('pii_data_type' = 'transactional_data');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` SET TAGS ('pii_subdomain' = 'patient_engagement');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` SET TAGS ('pii_domain' = 'digital_health');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` SET TAGS ('pii_tier' = 'ecm');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `digital_health_portal_engagement_event_id` SET TAGS ('pii_business_glossary_term' = 'Portal Engagement Event Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `digital_health_portal_engagement_event_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `digital_health_portal_engagement_event_id` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `care_site_id` SET TAGS ('pii_business_glossary_term' = 'Care Site Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `communication_campaign_id` SET TAGS ('pii_business_glossary_term' = 'Notification Campaign Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `demographics_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `demographics_id` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `clinician_id` SET TAGS ('pii_business_glossary_term' = 'Message Recipient Clinician Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `secure_message_thread_id` SET TAGS ('pii_business_glossary_term' = 'Message Thread Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_business_glossary_term' = 'Mpi Record Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `mpi_record_id` SET TAGS ('pii_sensitivity' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `portal_account_id` SET TAGS ('pii_business_glossary_term' = 'Portal Account Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `portal_account_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `portal_account_id` SET TAGS ('pii_sensitivity' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `digital_health_prom_response_id` SET TAGS ('pii_business_glossary_term' = 'Prom Response Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `proxy_access_id` SET TAGS ('pii_business_glossary_term' = 'Proxy Access Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `proxy_access_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `proxy_access_id` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `digital_health_rpm_device_reading_id` SET TAGS ('pii_business_glossary_term' = 'Rpm Device Reading Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `scheduling_appointment_id` SET TAGS ('pii_business_glossary_term' = 'Scheduling Appointment Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `portal_session_id` SET TAGS ('pii_business_glossary_term' = 'Session Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `lab_order_id` SET TAGS ('pii_business_glossary_term' = 'Test Result Lab Order Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `lab_order_id` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `lab_order_id` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `visit_id` SET TAGS ('pii_business_glossary_term' = 'Visit Id');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `browser_type` SET TAGS ('pii_business_glossary_term' = 'Browser Type');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `created_timestamp` SET TAGS ('pii_business_glossary_term' = 'Created Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `device_type` SET TAGS ('pii_business_glossary_term' = 'Device Type');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `document_type` SET TAGS ('pii_business_glossary_term' = 'Document Type');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `error_code` SET TAGS ('pii_business_glossary_term' = 'Error Code');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `error_description` SET TAGS ('pii_business_glossary_term' = 'Error Description');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `event_category` SET TAGS ('pii_business_glossary_term' = 'Event Category');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `event_date` SET TAGS ('pii_business_glossary_term' = 'Event Date');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `event_status` SET TAGS ('pii_business_glossary_term' = 'Event Status');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `event_timestamp` SET TAGS ('pii_business_glossary_term' = 'Event Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `event_timestamp` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `event_timestamp` SET TAGS ('pii_sensitivity' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `event_type` SET TAGS ('pii_business_glossary_term' = 'Event Type');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `feature_name` SET TAGS ('pii_business_glossary_term' = 'Feature Name');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `feature_name` SET TAGS ('pii_pii' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `feature_name` SET TAGS ('pii_uc_classification' = 'pii');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `ip_address` SET TAGS ('pii_sensitivity' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `ip_address` SET TAGS ('pii_restricted' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `ip_address` SET TAGS ('pii_address' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `ip_address` SET TAGS ('pii_pii' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `ip_address` SET TAGS ('pii_uc_classification' = 'pii');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `ip_address_hash` SET TAGS ('pii_business_glossary_term' = 'Ip Address Hash');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `ip_address_hash` SET TAGS ('pii_restricted' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `ip_address_hash` SET TAGS ('pii_address' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `ip_address_hash` SET TAGS ('pii_pii' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `ip_address_hash` SET TAGS ('pii_uc_classification' = 'pii');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `is_proxy_session` SET TAGS ('pii_business_glossary_term' = 'Is Proxy Session');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `is_proxy_session` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `is_proxy_session` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `notification_channel` SET TAGS ('pii_business_glossary_term' = 'Notification Channel');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `page_name` SET TAGS ('pii_business_glossary_term' = 'Page Name');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `page_name` SET TAGS ('pii_pii' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `page_name` SET TAGS ('pii_uc_classification' = 'pii');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `session_duration_seconds` SET TAGS ('pii_business_glossary_term' = 'Session Duration Seconds');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `session_duration_seconds` SET TAGS ('pii_vibe_rate_typing' = 'decimal');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `session_end_timestamp` SET TAGS ('pii_business_glossary_term' = 'Session End Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `session_start_timestamp` SET TAGS ('pii_business_glossary_term' = 'Session Start Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`digital_health_portal_engagement_event` ALTER COLUMN `updated_timestamp` SET TAGS ('pii_business_glossary_term' = 'Updated Timestamp');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`rpm_enrollment` SET TAGS ('pii_data_type' = 'transactional_data');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`rpm_enrollment` SET TAGS ('pii_subdomain' = 'remote_monitoring');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`rpm_enrollment` ALTER COLUMN `rpm_enrollment_id` SET TAGS ('pii_business_glossary_term' = 'rpm_enrollment Identifier');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`rpm_enrollment` ALTER COLUMN `digital_health_rpm_program_enrollment_id` SET TAGS ('pii_business_glossary_term' = 'Rpm Program Enrollment Id (Foreign Key)');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` SET TAGS ('pii_data_type' = 'master_data');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` SET TAGS ('pii_subdomain' = 'patient_engagement');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `portal_session_id` SET TAGS ('pii_business_glossary_term' = 'Portal Session Identifier');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `previous_portal_session_id` SET TAGS ('pii_self_ref_fk' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `browser_name` SET TAGS ('pii_pii' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `browser_name` SET TAGS ('pii_uc_classification' = 'pii');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `consent_acknowledged_flag` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `consent_acknowledged_flag` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `device_identifier` SET TAGS ('pii_confidential' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `device_identifier` SET TAGS ('pii_device' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `ip_address` SET TAGS ('pii_confidential' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `ip_address` SET TAGS ('pii_ip' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `ip_address` SET TAGS ('pii_pii' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `ip_address` SET TAGS ('pii_uc_classification' = 'pii');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `proxy_access_flag` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `proxy_access_flag` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `proxy_relationship` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `proxy_relationship` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `session_token` SET TAGS ('pii_restricted' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`portal_session` ALTER COLUMN `session_token` SET TAGS ('pii_identifier' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`secure_message_thread` SET TAGS ('pii_data_type' = 'master_data');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`secure_message_thread` SET TAGS ('pii_subdomain' = 'patient_engagement');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`secure_message_thread` ALTER COLUMN `secure_message_thread_id` SET TAGS ('pii_business_glossary_term' = 'Secure Message Thread Identifier');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`secure_message_thread` ALTER COLUMN `parent_secure_message_thread_id` SET TAGS ('pii_self_ref_fk' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`secure_message_thread` ALTER COLUMN `consent_on_file` SET TAGS ('pii_phi' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`secure_message_thread` ALTER COLUMN `consent_on_file` SET TAGS ('pii_uc_classification' = 'phi');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`secure_message_thread` ALTER COLUMN `thread_subject` SET TAGS ('pii_restricted' = 'true');
ALTER TABLE `vibe_healthcare_v1`.`digital_health`.`secure_message_thread` ALTER COLUMN `thread_subject` SET TAGS ('pii_health' = 'true');
