-- Metric views for domain: guest | Business: Travel_Hospitality | Version: 2 | Generated on: 2026-06-22 19:35:58

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`guest_stay_history`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Core guest stay performance metrics covering revenue, satisfaction, and stay behaviour. Primary fact table for guest-level hospitality KPIs used in executive dashboards and revenue steering."
  source: "`vibe_travel_hospitality_v1`.`guest`.`stay_history`"
  dimensions:
    - name: "stay_status"
      expr: stay_status
      comment: "Current status of the stay record (e.g. checked-out, no-show, cancelled) — used to filter or segment stay performance."
    - name: "guest_type"
      expr: guest_type
      comment: "Classification of the guest (e.g. leisure, corporate, group) — key segmentation dimension for revenue and satisfaction analysis."
    - name: "loyalty_tier_at_stay"
      expr: loyalty_tier_at_stay
      comment: "Loyalty programme tier the guest held at the time of the stay — enables tier-based revenue and satisfaction benchmarking."
    - name: "currency_code"
      expr: currency_code
      comment: "Currency in which the stay financials are denominated — required for multi-currency revenue reporting."
    - name: "rate_plan_code"
      expr: rate_plan_code
      comment: "Rate plan applied to the stay — used to evaluate pricing strategy effectiveness."
    - name: "arrival_month"
      expr: DATE_TRUNC('MONTH', arrival_date)
      comment: "Month of guest arrival — primary time dimension for trend and seasonality analysis."
    - name: "arrival_year"
      expr: YEAR(arrival_date)
      comment: "Year of guest arrival — used for year-over-year performance comparisons."
    - name: "booking_month"
      expr: DATE_TRUNC('MONTH', booking_date)
      comment: "Month the booking was made — supports lead-time and booking-window analysis."
    - name: "complimentary_flag"
      expr: complimentary_flag
      comment: "Indicates whether the stay was complimentary — used to separate revenue-generating stays from comp stays in KPI calculations."
    - name: "service_recovery_flag"
      expr: service_recovery_flag
      comment: "Indicates whether a service recovery action was taken during the stay — used to track quality incidents."
    - name: "vip_code"
      expr: vip_code
      comment: "VIP designation code applied at the time of stay — used to segment high-value guest performance."
  measures:
    - name: "total_room_revenue"
      expr: SUM(CAST(room_revenue AS DOUBLE))
      comment: "Total room revenue across all stays. Core top-line revenue KPI for property and portfolio performance reviews."
    - name: "total_ancillary_revenue"
      expr: SUM(CAST(ancillary_revenue AS DOUBLE))
      comment: "Total ancillary (non-room) revenue generated by guests. Measures the effectiveness of upsell and cross-sell strategies."
    - name: "total_fb_revenue"
      expr: SUM(CAST(fb_revenue AS DOUBLE))
      comment: "Total food and beverage revenue from guest stays. Key indicator of F&B outlet performance and attachment rate."
    - name: "total_folio_amount"
      expr: SUM(CAST(total_folio_amount AS DOUBLE))
      comment: "Total billed amount across all stay folios including room, F&B, and ancillary charges. Represents gross guest spend."
    - name: "total_tax_amount"
      expr: SUM(CAST(tax_amount AS DOUBLE))
      comment: "Total tax collected across all stays. Required for regulatory reporting and net revenue calculations."
    - name: "avg_daily_rate"
      expr: AVG(CAST(adr AS DOUBLE))
      comment: "Average Daily Rate across stays. Fundamental hotel revenue KPI used in RevPAR and pricing strategy decisions."
    - name: "avg_total_folio_per_stay"
      expr: AVG(CAST(total_folio_amount AS DOUBLE))
      comment: "Average total spend per stay. Measures guest value and informs revenue-per-guest benchmarking."
    - name: "avg_gss_score"
      expr: AVG(CAST(gss_score AS DOUBLE))
      comment: "Average Guest Satisfaction Score across stays. Primary customer experience KPI used in operational and executive reviews."
    - name: "total_stays"
      expr: COUNT(DISTINCT stay_history_id)
      comment: "Total number of distinct stay records. Baseline volume metric for occupancy and throughput analysis."
    - name: "total_unique_guests"
      expr: COUNT(DISTINCT profile_id)
      comment: "Total number of unique guests with a stay record. Measures guest reach and repeat-visit base."
    - name: "service_recovery_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN service_recovery_flag = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(stay_history_id), 0), 2)
      comment: "Percentage of stays requiring a service recovery action. Tracks operational quality and guest experience failure rate — a key driver of satisfaction and loyalty."
    - name: "complimentary_stay_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN complimentary_flag = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(stay_history_id), 0), 2)
      comment: "Percentage of stays that were complimentary. Monitors comp room usage relative to total stays for cost control and loyalty programme management."
    - name: "avg_ancillary_revenue_per_stay"
      expr: AVG(CAST(ancillary_revenue AS DOUBLE))
      comment: "Average ancillary revenue per stay record. Measures upsell effectiveness and non-room revenue contribution per guest visit."
    - name: "avg_feedback_topics_extracted"
      expr: AVG(CAST(feedback_topics_extracted AS DOUBLE))
      comment: "Average number of feedback topics extracted per stay. Indicates depth of guest feedback capture and NLP pipeline coverage."
$$;

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`guest_profile`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Guest profile master metrics covering loyalty enrolment, opt-in rates, VIP composition, and data quality. Used by CRM, loyalty, and marketing teams to steer guest engagement strategy."
  source: "`vibe_travel_hospitality_v1`.`guest`.`profile`"
  dimensions:
    - name: "guest_type"
      expr: guest_type
      comment: "Classification of the guest (e.g. leisure, corporate, group) — primary segmentation for profile analysis."
    - name: "loyalty_tier"
      expr: loyalty_tier
      comment: "Current loyalty programme tier of the guest — used to segment profile counts and engagement metrics by tier."
    - name: "profile_status"
      expr: profile_status
      comment: "Active/inactive/merged status of the profile — used to filter active guest base and track data hygiene."
    - name: "country_of_residence_code"
      expr: country_of_residence_code
      comment: "Country of residence of the guest — used for geographic segmentation of the guest base."
    - name: "vip_status"
      expr: vip_status
      comment: "VIP designation on the profile — used to size and track the high-value guest segment."
    - name: "preferred_language_code"
      expr: preferred_language_code
      comment: "Guest preferred language — used for localisation strategy and communication planning."
    - name: "loyalty_enrollment_year"
      expr: YEAR(loyalty_enrollment_date)
      comment: "Year the guest enrolled in the loyalty programme — used for cohort-based loyalty growth analysis."
    - name: "gender"
      expr: gender
      comment: "Guest gender — used for demographic segmentation in marketing and product personalisation."
    - name: "is_merge_survivor"
      expr: is_merge_survivor
      comment: "Indicates whether this profile survived a deduplication merge — used to assess profile data quality and deduplication coverage."
  measures:
    - name: "total_active_profiles"
      expr: COUNT(DISTINCT CASE WHEN profile_status = 'ACTIVE' THEN profile_id END)
      comment: "Total number of active guest profiles. Baseline measure of the addressable guest base for CRM and marketing."
    - name: "total_loyalty_members"
      expr: COUNT(DISTINCT CASE WHEN loyalty_member_number IS NOT NULL THEN profile_id END)
      comment: "Total number of guest profiles enrolled in the loyalty programme. Key loyalty programme scale metric."
    - name: "email_opt_in_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN email_opt_in = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(profile_id), 0), 2)
      comment: "Percentage of guest profiles opted in to email marketing. Measures the reachable email audience and consent health."
    - name: "marketing_opt_in_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN marketing_opt_in = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(profile_id), 0), 2)
      comment: "Percentage of guest profiles opted in to marketing communications. Tracks consent coverage for campaign targeting."
    - name: "sms_opt_in_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN sms_opt_in = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(profile_id), 0), 2)
      comment: "Percentage of guest profiles opted in to SMS communications. Measures SMS channel reach for direct marketing."
    - name: "gdpr_erasure_request_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN gdpr_erasure_requested = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(profile_id), 0), 2)
      comment: "Percentage of guest profiles with a GDPR erasure request. Critical compliance KPI monitored by legal and data privacy teams."
    - name: "vip_profile_count"
      expr: COUNT(DISTINCT CASE WHEN vip_status IS NOT NULL AND vip_status != '' THEN profile_id END)
      comment: "Number of guest profiles with an active VIP designation. Tracks the size of the high-value guest segment."
    - name: "merged_profile_count"
      expr: COUNT(DISTINCT CASE WHEN merged_into_profile_id IS NOT NULL THEN profile_id END)
      comment: "Number of profiles that have been merged into another profile. Measures deduplication activity and data quality improvement over time."
$$;

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`guest_communication_consent`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Guest communication consent metrics covering consent coverage, double opt-in compliance, suppression rates, and third-party sharing consent. Critical for GDPR/regulatory compliance and marketing reachability reporting."
  source: "`vibe_travel_hospitality_v1`.`guest`.`communication_consent`"
  dimensions:
    - name: "consent_type"
      expr: consent_type
      comment: "Type of consent captured (e.g. email marketing, SMS, profiling) — primary dimension for consent coverage analysis."
    - name: "consent_status"
      expr: consent_status
      comment: "Current status of the consent record (e.g. granted, withdrawn, expired) — used to filter active consents."
    - name: "consent_method"
      expr: consent_method
      comment: "Method by which consent was captured (e.g. web form, in-person, email) — used to evaluate consent capture channel effectiveness."
    - name: "consent_source"
      expr: consent_source
      comment: "Source system or touchpoint where consent was captured — used for consent provenance and audit reporting."
    - name: "jurisdiction"
      expr: jurisdiction
      comment: "Legal jurisdiction governing the consent record (e.g. EU, UK, US) — required for jurisdiction-specific compliance reporting."
    - name: "legal_basis"
      expr: legal_basis
      comment: "Legal basis for processing under GDPR or equivalent regulation — used in regulatory audit and compliance dashboards."
    - name: "consent_language_code"
      expr: consent_language_code
      comment: "Language in which consent was presented to the guest — used for localisation compliance checks."
    - name: "consent_granted_month"
      expr: DATE_TRUNC('MONTH', consent_granted_date)
      comment: "Month consent was granted — used for consent volume trend analysis."
    - name: "double_opt_in_flag"
      expr: double_opt_in_flag
      comment: "Indicates whether double opt-in confirmation was completed — used to segment high-quality confirmed consents."
  measures:
    - name: "total_active_consents"
      expr: COUNT(DISTINCT CASE WHEN consent_status = 'GRANTED' AND record_active_flag = TRUE THEN communication_consent_id END)
      comment: "Total number of currently active and granted consent records. Measures the size of the legally reachable guest audience."
    - name: "consent_withdrawal_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN consent_status = 'WITHDRAWN' THEN 1 ELSE 0 END) / NULLIF(COUNT(communication_consent_id), 0), 2)
      comment: "Percentage of consent records that have been withdrawn. Tracks opt-out trends and marketing list attrition — a key compliance and CRM health metric."
    - name: "double_opt_in_confirmation_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN double_opt_in_flag = TRUE AND double_opt_in_confirmed_timestamp IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(SUM(CASE WHEN double_opt_in_flag = TRUE THEN 1 ELSE 0 END), 0), 2)
      comment: "Percentage of double opt-in consent requests that were confirmed by the guest. Measures consent quality and email deliverability health."
    - name: "suppression_list_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN suppression_list_flag = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(communication_consent_id), 0), 2)
      comment: "Percentage of consent records on the suppression list. Tracks the proportion of guests who must not be contacted — critical for compliance and deliverability."
    - name: "third_party_sharing_consent_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN third_party_sharing_consent_flag = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(communication_consent_id), 0), 2)
      comment: "Percentage of consent records permitting third-party data sharing. Governs eligibility for partner marketing programmes and data monetisation."
    - name: "profiling_consent_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN profiling_consent_flag = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(communication_consent_id), 0), 2)
      comment: "Percentage of consent records permitting guest profiling. Determines the eligible audience for personalisation and AI-driven recommendation engines."
    - name: "total_unique_consented_guests"
      expr: COUNT(DISTINCT CASE WHEN consent_status = 'GRANTED' THEN guest_profile_id END)
      comment: "Total number of unique guests with at least one active granted consent. Measures the breadth of the consented guest base for marketing reach planning."
$$;

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`guest_corporate_account`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Corporate account performance and portfolio metrics covering revenue targets, credit exposure, discount levels, and contract health. Used by sales, revenue management, and finance to manage the B2B guest segment."
  source: "`vibe_travel_hospitality_v1`.`guest`.`corporate_account`"
  dimensions:
    - name: "account_status"
      expr: account_status
      comment: "Current status of the corporate account (e.g. active, suspended, closed) — primary filter for active portfolio analysis."
    - name: "account_type"
      expr: account_type
      comment: "Type of corporate account (e.g. negotiated, preferred, transient) — used to segment revenue and discount analysis."
    - name: "rate_program_type"
      expr: rate_program_type
      comment: "Rate programme type associated with the account — used to evaluate pricing strategy by programme."
    - name: "vip_tier"
      expr: vip_tier
      comment: "VIP tier assigned to the corporate account — used to segment high-value accounts for priority service and reporting."
    - name: "tax_exempt_status"
      expr: tax_exempt_status
      comment: "Tax exemption status of the account — required for revenue and billing compliance reporting."
    - name: "direct_billing_enabled"
      expr: direct_billing_enabled
      comment: "Indicates whether direct billing is enabled for the account — used to segment accounts by billing method and credit exposure."
    - name: "loyalty_program_eligible"
      expr: loyalty_program_eligible
      comment: "Indicates whether the corporate account is eligible for the loyalty programme — used to track loyalty-linked corporate revenue."
    - name: "contract_start_year"
      expr: YEAR(contract_start_date)
      comment: "Year the corporate contract commenced — used for contract vintage and renewal cycle analysis."
    - name: "mice_eligible"
      expr: mice_eligible
      comment: "Indicates whether the account is eligible for MICE (Meetings, Incentives, Conferences, Exhibitions) business — used to size the MICE corporate pipeline."
  measures:
    - name: "total_annual_revenue_target"
      expr: SUM(CAST(annual_revenue_target AS DOUBLE))
      comment: "Sum of annual revenue targets across all corporate accounts. Measures the total contracted revenue commitment from the B2B portfolio."
    - name: "avg_annual_revenue_target"
      expr: AVG(CAST(annual_revenue_target AS DOUBLE))
      comment: "Average annual revenue target per corporate account. Benchmarks account value and supports tiering and prioritisation decisions."
    - name: "total_credit_limit_exposure"
      expr: SUM(CAST(credit_limit AS DOUBLE))
      comment: "Total credit limit extended across all corporate accounts. Measures aggregate credit exposure for finance and risk management."
    - name: "avg_discount_percent"
      expr: AVG(CAST(discount_percent AS DOUBLE))
      comment: "Average negotiated discount percentage across corporate accounts. Tracks the depth of discounting in the B2B portfolio — a key revenue management lever."
    - name: "total_active_accounts"
      expr: COUNT(DISTINCT CASE WHEN account_status = 'ACTIVE' THEN corporate_account_id END)
      comment: "Total number of active corporate accounts. Baseline measure of the B2B client portfolio size."
    - name: "direct_billing_account_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN direct_billing_enabled = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(corporate_account_id), 0), 2)
      comment: "Percentage of corporate accounts with direct billing enabled. Measures the proportion of accounts on invoice-based payment — relevant for AR and cash flow management."
    - name: "mice_eligible_account_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN mice_eligible = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(corporate_account_id), 0), 2)
      comment: "Percentage of corporate accounts eligible for MICE business. Measures the MICE-addressable share of the B2B portfolio for group sales targeting."
    - name: "avg_negotiated_rate_amount"
      expr: AVG(CAST(negotiated_rate_code AS DOUBLE))
      comment: "Average negotiated rate amount across corporate accounts. Tracks the average contracted room rate level for B2B pricing strategy reviews."
$$;

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`guest_vip_designation`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "VIP guest designation metrics covering designation volume, upgrade eligibility, revenue thresholds, and special handling requirements. Used by guest relations, operations, and revenue management to manage the highest-value guest segment."
  source: "`vibe_travel_hospitality_v1`.`guest`.`vip_designation`"
  dimensions:
    - name: "designation_status"
      expr: designation_status
      comment: "Current status of the VIP designation (e.g. active, revoked, expired) — primary filter for active VIP population."
    - name: "designation_scope"
      expr: designation_scope
      comment: "Scope of the VIP designation (e.g. property-level, portfolio-wide) — used to segment VIP management responsibilities."
    - name: "designation_reason"
      expr: designation_reason
      comment: "Reason for the VIP designation (e.g. loyalty tier, revenue threshold, celebrity) — used to understand the composition of the VIP base."
    - name: "amenity_tier_code"
      expr: amenity_tier_code
      comment: "Amenity tier assigned to the VIP guest — used to plan and cost amenity provisioning for the VIP segment."
    - name: "upgrade_eligible"
      expr: upgrade_eligible
      comment: "Indicates whether the VIP guest is eligible for a room upgrade — used to manage upgrade inventory allocation."
    - name: "gm_greeting_required"
      expr: gm_greeting_required
      comment: "Indicates whether a General Manager greeting is required — used for operational pre-arrival planning."
    - name: "incognito_checkin"
      expr: incognito_checkin
      comment: "Indicates whether the guest requires an incognito check-in — used to flag privacy-sensitive arrivals for front-of-house teams."
    - name: "media_blackout"
      expr: media_blackout
      comment: "Indicates whether a media blackout is in effect for the guest — used to enforce privacy and security protocols."
    - name: "effective_from_year"
      expr: YEAR(effective_from)
      comment: "Year the VIP designation became effective — used for cohort and tenure analysis of the VIP base."
  measures:
    - name: "total_active_vip_designations"
      expr: COUNT(DISTINCT CASE WHEN designation_status = 'ACTIVE' THEN vip_designation_id END)
      comment: "Total number of currently active VIP designations. Baseline measure of the active VIP guest population requiring elevated service."
    - name: "total_unique_vip_guests"
      expr: COUNT(DISTINCT profile_id)
      comment: "Total number of unique guest profiles with a VIP designation. Measures the breadth of the VIP guest base across the portfolio."
    - name: "upgrade_eligible_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN upgrade_eligible = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(vip_designation_id), 0), 2)
      comment: "Percentage of VIP designations eligible for room upgrades. Informs upgrade inventory planning and VIP room assignment strategy."
    - name: "gm_greeting_required_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN gm_greeting_required = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(vip_designation_id), 0), 2)
      comment: "Percentage of VIP designations requiring a GM greeting. Measures the operational demand on General Manager time for VIP arrivals."
    - name: "avg_revenue_threshold_amount"
      expr: AVG(CAST(revenue_threshold_amount AS DOUBLE))
      comment: "Average revenue threshold amount set for VIP designations. Benchmarks the revenue qualification bar for VIP status across the portfolio."
    - name: "total_revenue_threshold_amount"
      expr: SUM(CAST(revenue_threshold_amount AS DOUBLE))
      comment: "Total revenue threshold committed across all VIP designations. Measures the aggregate revenue value represented by the VIP guest base."
    - name: "security_escort_required_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN security_escort_required = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(vip_designation_id), 0), 2)
      comment: "Percentage of VIP designations requiring a security escort. Measures the operational security demand and resource planning requirement for VIP arrivals."
    - name: "incognito_checkin_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN incognito_checkin = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(vip_designation_id), 0), 2)
      comment: "Percentage of VIP designations requiring incognito check-in. Tracks the proportion of privacy-sensitive VIP arrivals requiring special front-of-house protocols."
$$;

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`guest_group_block`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Group block performance metrics covering contracted vs. picked-up room nights, attrition risk, deposit compliance, and wash rates. Used by group sales, revenue management, and events teams to manage group business performance."
  source: "`vibe_travel_hospitality_v1`.`guest`.`guest_group_block`"
  dimensions:
    - name: "block_status"
      expr: block_status
      comment: "Current status of the group block (e.g. tentative, definite, cancelled) — primary dimension for group pipeline and conversion analysis."
    - name: "group_type"
      expr: group_type
      comment: "Type of group (e.g. corporate, leisure, MICE, wedding) — used to segment group revenue and performance by category."
    - name: "currency_code"
      expr: currency_code
      comment: "Currency in which the group block financials are denominated — required for multi-currency group revenue reporting."
    - name: "cancellation_policy_code"
      expr: cancellation_policy_code
      comment: "Cancellation policy applied to the group block — used to assess cancellation risk and policy effectiveness."
    - name: "rooming_list_status"
      expr: rooming_list_status
      comment: "Status of the rooming list submission — used to track group operational readiness ahead of arrival."
    - name: "repeat_group_flag"
      expr: repeat_group_flag
      comment: "Indicates whether this is a repeat group booking — used to measure group loyalty and retention."
    - name: "vip_flag"
      expr: vip_flag
      comment: "Indicates whether the group has VIP status — used to segment high-priority group blocks for elevated service planning."
    - name: "arrival_month"
      expr: DATE_TRUNC('MONTH', arrival_date)
      comment: "Month of group arrival — primary time dimension for group business pipeline and seasonality analysis."
    - name: "arrival_year"
      expr: YEAR(arrival_date)
      comment: "Year of group arrival — used for year-over-year group business performance comparisons."
  measures:
    - name: "total_contracted_rate_amount"
      expr: SUM(CAST(contracted_rate_amount AS DOUBLE))
      comment: "Total contracted room rate value across all group blocks. Measures the aggregate contracted revenue commitment from the group segment."
    - name: "avg_contracted_rate_amount"
      expr: AVG(CAST(contracted_rate_amount AS DOUBLE))
      comment: "Average contracted room rate per group block. Benchmarks group pricing levels for revenue management and negotiation strategy."
    - name: "total_deposit_required_amount"
      expr: SUM(CAST(deposit_required_amount AS DOUBLE))
      comment: "Total deposit amount required across all group blocks. Measures the expected deposit cash flow from the group pipeline."
    - name: "total_deposit_received_amount"
      expr: SUM(CAST(deposit_received_amount AS DOUBLE))
      comment: "Total deposit amount actually received from group blocks. Tracks deposit collection performance and cash flow realisation."
    - name: "deposit_collection_rate_pct"
      expr: ROUND(100.0 * SUM(CAST(deposit_received_amount AS DOUBLE)) / NULLIF(SUM(CAST(deposit_required_amount AS DOUBLE)), 0), 2)
      comment: "Percentage of required group deposits that have been collected. Measures deposit compliance and financial risk exposure from the group pipeline."
    - name: "avg_attrition_pct"
      expr: AVG(CAST(attrition_pct AS DOUBLE))
      comment: "Average attrition percentage across group blocks. Tracks the rate at which groups are releasing contracted rooms — a key revenue risk indicator."
    - name: "avg_wash_pct"
      expr: AVG(CAST(wash_pct AS DOUBLE))
      comment: "Average wash percentage applied to group blocks. Measures the expected reduction in contracted room nights — used in revenue forecasting and inventory management."
    - name: "total_group_blocks"
      expr: COUNT(DISTINCT guest_group_block_id)
      comment: "Total number of group block records. Baseline volume metric for group business pipeline sizing."
    - name: "repeat_group_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN repeat_group_flag = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(guest_group_block_id), 0), 2)
      comment: "Percentage of group blocks from repeat groups. Measures group loyalty and the strength of long-term group relationships — a key indicator of group sales retention."
    - name: "cancellation_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN block_status = 'CANCELLED' THEN 1 ELSE 0 END) / NULLIF(COUNT(guest_group_block_id), 0), 2)
      comment: "Percentage of group blocks that have been cancelled. Tracks group cancellation risk and the effectiveness of cancellation policy enforcement."
$$;

CREATE OR REPLACE VIEW `vibe_travel_hospitality_v1`.`_metrics`.`guest_segment`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Guest segment performance and assignment metrics covering revenue contribution, loyalty eligibility, yield management flags, and segment health. Used by revenue management and CRM to evaluate segment strategy and guest classification quality."
  source: "`vibe_travel_hospitality_v1`.`guest`.`segment`"
  dimensions:
    - name: "segment_type"
      expr: segment_type
      comment: "Type of guest segment (e.g. transient, group, corporate, wholesale) — primary dimension for segment performance analysis."
    - name: "segment_status"
      expr: segment_status
      comment: "Current status of the segment record (e.g. active, inactive, superseded) — used to filter the active segment taxonomy."
    - name: "assignment_method"
      expr: assignment_method
      comment: "Method used to assign the guest to this segment (e.g. rule-based, ML model, manual) — used to evaluate assignment quality and automation coverage."
    - name: "rate_strategy_type"
      expr: rate_strategy_type
      comment: "Rate strategy associated with the segment — used to link segment classification to pricing decisions."
    - name: "hierarchy_level"
      expr: hierarchy_level
      comment: "Level of the segment within the segment hierarchy — used for roll-up and drill-down analysis."
    - name: "yield_management_flag"
      expr: yield_management_flag
      comment: "Indicates whether the segment is subject to yield management controls — used to identify revenue-managed vs. fixed-rate segments."
    - name: "loyalty_points_eligible"
      expr: loyalty_points_eligible
      comment: "Indicates whether guests in this segment earn loyalty points — used to track loyalty programme coverage across segments."
    - name: "assignment_year"
      expr: YEAR(assignment_date)
      comment: "Year of segment assignment — used for cohort and trend analysis of segment composition changes."
    - name: "usali_mapping_code"
      expr: usali_mapping_code
      comment: "USALI (Uniform System of Accounts for the Lodging Industry) mapping code — used for standardised financial reporting alignment."
  measures:
    - name: "total_segment_assignments"
      expr: COUNT(DISTINCT segment_id)
      comment: "Total number of segment assignment records. Baseline measure of segment classification volume and coverage."
    - name: "total_unique_guests_segmented"
      expr: COUNT(DISTINCT profile_id)
      comment: "Total number of unique guest profiles with a segment assignment. Measures the breadth of guest segmentation coverage."
    - name: "avg_assignment_confidence_score"
      expr: AVG(CAST(assignment_confidence_score AS DOUBLE))
      comment: "Average confidence score of segment assignments. Measures the quality and reliability of the guest segmentation model — a key data quality KPI."
    - name: "avg_revpar_contribution_pct"
      expr: AVG(CAST(revpar_contribution_pct AS DOUBLE))
      comment: "Average RevPAR contribution percentage across segment assignments. Measures the revenue productivity of each segment relative to total RevPAR."
    - name: "avg_adr_index_vs_property"
      expr: AVG(CAST(adr_index_vs_property AS DOUBLE))
      comment: "Average ADR index of the segment relative to the property average. Measures whether the segment is above or below the property's average rate — a key pricing strategy indicator."
    - name: "avg_ancillary_revenue_per_stay"
      expr: AVG(CAST(ancillary_revenue_per_stay AS DOUBLE))
      comment: "Average ancillary revenue per stay for guests in this segment. Measures the non-room revenue contribution of each segment."
    - name: "avg_fb_attachment_rate_pct"
      expr: AVG(CAST(fb_attachment_rate_pct AS DOUBLE))
      comment: "Average F&B attachment rate for the segment. Measures how effectively F&B revenue is captured from guests in each segment."
    - name: "avg_loyalty_points_multiplier"
      expr: AVG(CAST(loyalty_points_multiplier AS DOUBLE))
      comment: "Average loyalty points multiplier across segment assignments. Tracks the loyalty incentive level applied to each segment — relevant for loyalty programme cost management."
    - name: "yield_managed_segment_rate_pct"
      expr: ROUND(100.0 * SUM(CASE WHEN yield_management_flag = TRUE THEN 1 ELSE 0 END) / NULLIF(COUNT(segment_id), 0), 2)
      comment: "Percentage of segment assignments subject to yield management. Measures the coverage of dynamic pricing controls across the guest segment taxonomy."
$$;