-- Metric views for domain: communication | Business: Ngo | Version: 2 | Generated on: 2026-07-03 05:04:58

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_advocacy_campaign`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Strategic KPIs for advocacy campaigns. Tracks budget efficiency, fundraising performance, and spend-to-target ratios. Relevant to communications directors and program leads managing multi-channel advocacy. Source systems: Salesforce NPSP, Mailchimp, Hootsuite, and UN agency communication platforms. NOTE: campaign_owner_name carries PII sensitivity tag pii_staff per VREQ-055 and should be masked in non-prod environments."
  source: "`vibe_ngo_v1`.`communication`.`advocacy_campaign`"
  dimensions:
    - name: "campaign_type"
      expr: campaign_type
      comment: "Type of advocacy campaign (e.g. awareness, fundraising, policy) — primary grouping for portfolio analysis."
    - name: "campaign_status"
      expr: campaign_status
      comment: "Current lifecycle status of the campaign (e.g. active, closed, draft) — used to filter live vs. historical performance."
    - name: "geographic_focus"
      expr: geographic_focus
      comment: "Geographic region or country focus of the campaign — enables regional performance comparison."
    - name: "primary_channel_mix"
      expr: primary_channel_mix
      comment: "Primary channel mix used (e.g. digital, print, events) — informs channel effectiveness analysis."
    - name: "sdg_alignment_tags"
      expr: sdg_alignment_tags
      comment: "SDG goals the campaign is aligned to — supports donor reporting and impact attribution."
    - name: "is_donor_restricted"
      expr: is_donor_restricted
      comment: "Whether the campaign is subject to donor restrictions — critical for compliance segmentation."
    - name: "launch_year_month"
      expr: DATE_TRUNC('month', launch_date)
      comment: "Month of campaign launch — enables trend analysis of campaign pipeline over time."
    - name: "compliance_review_status"
      expr: compliance_review_status
      comment: "Status of compliance review for the campaign — flags campaigns pending or failing review."
  measures:
    - name: "total_campaigns"
      expr: COUNT(1)
      comment: "Total number of advocacy campaigns. Baseline volume metric for portfolio sizing and capacity planning."
    - name: "total_budget_allocated_usd"
      expr: SUM(CAST(budget_allocated_amount AS DOUBLE))
      comment: "Total budget allocated across campaigns in reporting currency. Drives resource allocation decisions and budget utilization reviews."
    - name: "total_actual_spend_usd"
      expr: SUM(CAST(actual_spend_amount AS DOUBLE))
      comment: "Total actual spend across campaigns. Compared against budget to assess burn rate and financial discipline."
    - name: "total_actual_fundraising_usd"
      expr: SUM(CAST(actual_fundraising_amount AS DOUBLE))
      comment: "Total fundraising revenue generated by advocacy campaigns. Key revenue KPI for communications-driven fundraising."
    - name: "total_target_fundraising_usd"
      expr: SUM(CAST(target_fundraising_amount AS DOUBLE))
      comment: "Total fundraising target across campaigns. Used as denominator for fundraising attainment rate."
    - name: "avg_budget_per_campaign_usd"
      expr: AVG(CAST(budget_allocated_amount AS DOUBLE))
      comment: "Average budget allocated per campaign. Benchmarks campaign investment levels and informs future planning."
    - name: "budget_utilization_rate"
      expr: ROUND(100.0 * SUM(CAST(actual_spend_amount AS DOUBLE)) / NULLIF(SUM(CAST(budget_allocated_amount AS DOUBLE)), 0), 2)
      comment: "Percentage of allocated budget actually spent. Values near 100% indicate efficient execution; significantly under/over signals planning issues."
    - name: "fundraising_attainment_rate"
      expr: ROUND(100.0 * SUM(CAST(actual_fundraising_amount AS DOUBLE)) / NULLIF(SUM(CAST(target_fundraising_amount AS DOUBLE)), 0), 2)
      comment: "Percentage of fundraising target achieved. Core KPI for communications-driven revenue performance reviewed at QBRs."
    - name: "cost_per_fundraising_dollar"
      expr: ROUND(SUM(CAST(actual_spend_amount AS DOUBLE)) / NULLIF(SUM(CAST(actual_fundraising_amount AS DOUBLE)), 0), 4)
      comment: "Spend required to raise one dollar of fundraising revenue. Efficiency ratio used by CFOs and communications VPs to evaluate campaign ROI."
    - name: "donor_restricted_campaign_count"
      expr: COUNT(CASE WHEN is_donor_restricted = TRUE THEN 1 END)
      comment: "Number of campaigns subject to donor restrictions. Compliance risk indicator — high counts require additional oversight."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_campaign_touchpoint`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Constituent engagement and conversion KPIs at the touchpoint level. Measures channel effectiveness, conversion rates, sentiment, and cost efficiency across all campaign interactions. Critical for optimizing multi-channel communication strategies. Source systems: Salesforce Marketing Cloud, HubSpot, Mailchimp, and digital analytics platforms."
  source: "`vibe_ngo_v1`.`communication`.`campaign_touchpoint`"
  dimensions:
    - name: "touchpoint_type"
      expr: touchpoint_type
      comment: "Type of touchpoint (e.g. email, SMS, social, in-person) — primary dimension for channel mix analysis."
    - name: "channel"
      expr: channel
      comment: "Communication channel used for the touchpoint — enables channel-level performance benchmarking."
    - name: "country_code"
      expr: country_code
      comment: "Country where the touchpoint occurred — supports geographic performance analysis."
    - name: "conversion_type"
      expr: conversion_type
      comment: "Type of conversion achieved (e.g. donation, sign-up, petition) — segments conversion performance by outcome type."
    - name: "device_type"
      expr: device_type
      comment: "Device used by the constituent (e.g. mobile, desktop) — informs digital channel optimization."
    - name: "language_preference"
      expr: language_preference
      comment: "Constituent language preference — supports localization effectiveness analysis."
    - name: "response_month"
      expr: DATE_TRUNC('month', response_date)
      comment: "Month of constituent response — enables trend analysis of engagement over time."
    - name: "opt_out_flag"
      expr: opt_out_flag
      comment: "Whether the constituent opted out — critical for list health and compliance monitoring."
  measures:
    - name: "total_touchpoints"
      expr: COUNT(1)
      comment: "Total number of campaign touchpoints delivered. Volume baseline for reach and engagement capacity."
    - name: "total_conversion_value_usd"
      expr: SUM(CAST(conversion_value_usd AS DOUBLE))
      comment: "Total monetary value of conversions generated by touchpoints. Revenue attribution metric for campaign ROI analysis."
    - name: "total_cost_usd"
      expr: SUM(CAST(cost_per_touchpoint_usd AS DOUBLE))
      comment: "Total cost of all touchpoints. Used to compute cost efficiency ratios and budget accountability."
    - name: "conversion_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN conversion_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of touchpoints that resulted in a conversion. Primary effectiveness KPI for campaign optimization — low rates trigger channel or message review."
    - name: "opt_out_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN opt_out_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of touchpoints resulting in opt-out. High opt-out rates signal audience fatigue or messaging misalignment — triggers list hygiene action."
    - name: "avg_conversion_value_usd"
      expr: AVG(CAST(conversion_value_usd AS DOUBLE))
      comment: "Average conversion value per converting touchpoint. Benchmarks quality of conversions across channels and campaigns."
    - name: "avg_sentiment_score"
      expr: AVG(CAST(sentiment_score AS DOUBLE))
      comment: "Average sentiment score across touchpoints. Tracks constituent sentiment trends — declining scores trigger messaging review."
    - name: "cost_per_conversion_usd"
      expr: ROUND(SUM(CAST(cost_per_touchpoint_usd AS DOUBLE)) / NULLIF(COUNT(CASE WHEN conversion_flag = TRUE THEN 1 END), 0), 2)
      comment: "Average cost to achieve one conversion. Core efficiency KPI for communications investment decisions — compared against conversion value to assess ROI."
    - name: "feedback_provided_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN feedback_provided_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of touchpoints where constituent provided feedback. Indicates constituent engagement depth and accountability loop closure."
    - name: "unique_constituents_reached"
      expr: COUNT(DISTINCT constituent_id)
      comment: "Number of distinct constituents reached across touchpoints. Unduplicated reach metric for audience penetration analysis."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_community_engagement_event`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Community-level engagement KPIs tracking participation, inclusivity, and geographic reach of field engagement events. Critical for accountability to affected populations (AAP) frameworks and CHS commitments. Source systems: KoboToolbox, ODK, CommCare, and field data collection platforms used by INGOs and UN agencies."
  source: "`vibe_ngo_v1`.`communication`.`community_engagement_event`"
  dimensions:
    - name: "event_type"
      expr: event_type
      comment: "Type of community engagement event (e.g. focus group, town hall, feedback session) — primary grouping for event portfolio analysis."
    - name: "event_status"
      expr: event_status
      comment: "Current status of the event (e.g. planned, completed, cancelled) — filters operational vs. historical analysis."
    - name: "country_code"
      expr: country_code
      comment: "Country where the event took place — enables geographic performance comparison."
    - name: "admin_level_1"
      expr: admin_level_1
      comment: "First administrative level (e.g. province/state) — supports sub-national geographic drill-down."
    - name: "event_month"
      expr: DATE_TRUNC('month', event_date)
      comment: "Month of event — enables trend analysis of community engagement activity over time."
    - name: "translation_provided"
      expr: translation_provided
      comment: "Whether translation was provided — measures linguistic inclusivity of engagement events."
    - name: "primary_language"
      expr: primary_language
      comment: "Primary language used at the event — supports language accessibility analysis."
    - name: "data_collection_tool"
      expr: data_collection_tool
      comment: "Tool used for data collection (e.g. KoboToolbox, paper) — informs data quality and system usage analysis."
  measures:
    - name: "total_events"
      expr: COUNT(1)
      comment: "Total number of community engagement events conducted. Volume baseline for AAP and CHS accountability reporting."
    - name: "total_feedback_received"
      expr: SUM(CAST(feedback_received AS DOUBLE))
      comment: "Total feedback items received across all events. Measures community voice capture — low values relative to participants indicate weak feedback mechanisms."
    - name: "avg_feedback_per_event"
      expr: AVG(CAST(feedback_received AS DOUBLE))
      comment: "Average feedback items received per event. Benchmarks feedback capture effectiveness across event types and locations."
    - name: "events_with_translation_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN translation_provided = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of events where translation was provided. Inclusivity KPI — low rates in multilingual contexts indicate accessibility gaps."
    - name: "unique_communities_reached"
      expr: COUNT(DISTINCT community_name)
      comment: "Number of distinct communities reached. Geographic breadth metric for program coverage and equity analysis."
    - name: "unique_project_sites"
      expr: COUNT(DISTINCT project_site_id)
      comment: "Number of distinct project sites where engagement events occurred. Operational footprint metric for field coverage assessment."
    - name: "avg_event_duration_minutes"
      expr: AVG(CAST(duration_minutes AS DOUBLE))
      comment: "Average event duration in minutes. Quality indicator — very short events may indicate insufficient community consultation depth."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_constituent_consent`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Consent management KPIs tracking consent coverage, channel opt-in rates, expiry risk, and compliance posture. Critical for GDPR, data protection regulations, and donor audit readiness. Source systems: Salesforce NPSP, Raisers Edge NXT, and custom CRM platforms. NOTE: constituent data carries PII sensitivity per VREQ-022."
  source: "`vibe_ngo_v1`.`communication`.`constituent_consent`"
  dimensions:
    - name: "consent_type"
      expr: consent_type
      comment: "Type of consent (e.g. marketing, data processing, research) — primary grouping for consent portfolio analysis."
    - name: "consent_status"
      expr: consent_status
      comment: "Current status of consent record (e.g. active, withdrawn, expired) — critical for compliance filtering."
    - name: "consent_basis"
      expr: consent_basis
      comment: "Legal basis for consent (e.g. explicit, legitimate interest) — required for GDPR compliance reporting."
    - name: "consent_method"
      expr: consent_method
      comment: "Method by which consent was obtained (e.g. online form, in-person) — informs consent quality and auditability."
    - name: "constituent_country_code"
      expr: constituent_country_code
      comment: "Country of the constituent — enables jurisdiction-specific compliance analysis."
    - name: "is_minor"
      expr: is_minor
      comment: "Whether the constituent is a minor — triggers parental consent requirements and heightened data protection obligations."
    - name: "consent_granted_month"
      expr: DATE_TRUNC('month', consent_granted_date)
      comment: "Month consent was granted — enables trend analysis of consent acquisition over time."
    - name: "double_opt_in_confirmed"
      expr: double_opt_in_confirmed
      comment: "Whether double opt-in was confirmed — quality indicator for consent validity."
  measures:
    - name: "total_consent_records"
      expr: COUNT(1)
      comment: "Total consent records. Baseline for consent database size and coverage assessment."
    - name: "active_consent_count"
      expr: COUNT(CASE WHEN consent_status = 'active' THEN 1 END)
      comment: "Number of currently active consent records. Determines the addressable audience for compliant communications."
    - name: "consent_withdrawal_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN consent_status = 'withdrawn' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of consent records that have been withdrawn. Rising withdrawal rates signal trust or communication quality issues requiring leadership action."
    - name: "double_opt_in_confirmation_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN double_opt_in_confirmed = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of consents confirmed via double opt-in. Quality and compliance KPI — low rates increase regulatory risk in GDPR jurisdictions."
    - name: "minor_consent_with_parental_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_minor = TRUE AND parental_consent_obtained = TRUE THEN 1 END) / NULLIF(COUNT(CASE WHEN is_minor = TRUE THEN 1 END), 0), 2)
      comment: "Percentage of minor constituent records with parental consent obtained. Critical child safeguarding compliance KPI — any gap is a regulatory and reputational risk."
    - name: "expiring_consent_count_90d"
      expr: COUNT(CASE WHEN consent_expiry_date <= DATE_ADD(CURRENT_DATE(), 90) AND consent_status = 'active' THEN 1 END)
      comment: "Number of active consents expiring within 90 days. Operational risk metric — triggers consent renewal campaigns to prevent addressable audience shrinkage."
    - name: "email_channel_opt_in_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN channel_email = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of consent records with email channel opt-in. Determines email-addressable audience size for campaign planning."
    - name: "unique_constituents_with_consent"
      expr: COUNT(DISTINCT constituent_id)
      comment: "Number of distinct constituents with at least one consent record. Unduplicated consented audience size — key input for fundraising and communications capacity planning."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_constituent_message`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Message delivery, engagement, and response KPIs across all constituent communication channels. Tracks open rates, click rates, opt-out rates, and response compliance. Source systems: Salesforce Marketing Cloud, Mailchimp, Twilio, and email service providers. NOTE: recipient_name, recipient_email, recipient_phone, sender_name, sender_email carry PII sensitivity tags per VREQ-022/VREQ-055 and must be masked in non-prod."
  source: "`vibe_ngo_v1`.`communication`.`constituent_message`"
  dimensions:
    - name: "channel"
      expr: channel
      comment: "Communication channel (e.g. email, SMS, WhatsApp) — primary dimension for channel performance analysis."
    - name: "message_type"
      expr: message_type
      comment: "Type of message (e.g. newsletter, appeal, acknowledgement) — segments message performance by purpose."
    - name: "message_direction"
      expr: message_direction
      comment: "Direction of message (inbound/outbound) — separates constituent-initiated from org-initiated communications."
    - name: "delivery_status"
      expr: delivery_status
      comment: "Delivery status of the message (e.g. delivered, bounced, failed) — operational quality indicator."
    - name: "language_code"
      expr: language_code
      comment: "Language of the message — supports multilingual communication effectiveness analysis."
    - name: "priority"
      expr: priority
      comment: "Message priority level — enables SLA compliance analysis by priority tier."
    - name: "sent_month"
      expr: DATE_TRUNC('month', sent_timestamp)
      comment: "Month message was sent — enables trend analysis of communication volume and performance."
    - name: "response_required_flag"
      expr: response_required_flag
      comment: "Whether a response is required — filters messages needing SLA tracking."
  measures:
    - name: "total_messages_sent"
      expr: COUNT(1)
      comment: "Total messages sent. Volume baseline for communication capacity and channel utilization."
    - name: "open_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN opened_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of messages opened by recipients. Primary email engagement KPI — low rates trigger subject line and send-time optimization."
    - name: "click_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN clicked_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of messages where recipient clicked a link. Content engagement KPI — low click rates signal weak calls-to-action or irrelevant content."
    - name: "reply_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN replied_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of messages that received a reply. Dialogue engagement metric — important for two-way communication accountability."
    - name: "opt_out_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN opt_out_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of messages resulting in opt-out. Audience health KPI — rising opt-out rates trigger immediate communications strategy review."
    - name: "complaint_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN complaint_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of messages generating a complaint. Reputational risk KPI — high complaint rates can trigger ESP blacklisting and donor trust erosion."
    - name: "avg_sentiment_score"
      expr: AVG(CAST(sentiment_score AS DOUBLE))
      comment: "Average sentiment score of constituent messages. Tracks constituent relationship health — declining sentiment triggers relationship management intervention."
    - name: "response_overdue_count"
      expr: COUNT(CASE WHEN response_required_flag = TRUE AND replied_flag = FALSE AND response_due_date < CURRENT_DATE() THEN 1 END)
      comment: "Number of messages requiring response that are past due date. SLA compliance KPI — directly impacts constituent satisfaction and accountability commitments."
    - name: "unique_constituents_messaged"
      expr: COUNT(DISTINCT constituent_id)
      comment: "Number of distinct constituents messaged. Unduplicated reach metric for audience engagement breadth."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_crisis_communication`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Crisis communication response KPIs tracking activation speed, media response rates, stakeholder notification compliance, and post-crisis review completion. Critical for organizational resilience and donor confidence. Source systems: internal incident management systems, SAP, and field sitrep platforms used by UN agencies and INGOs."
  source: "`vibe_ngo_v1`.`communication`.`crisis_communication`"
  dimensions:
    - name: "crisis_type"
      expr: crisis_type
      comment: "Type of crisis (e.g. security, reputational, operational, natural disaster) — primary grouping for crisis portfolio analysis."
    - name: "crisis_communication_status"
      expr: crisis_communication_status
      comment: "Current status of crisis communication (e.g. active, resolved, monitoring) — operational filter."
    - name: "severity_level"
      expr: severity_level
      comment: "Severity level of the crisis — enables risk-tiered performance analysis."
    - name: "geographic_scope"
      expr: geographic_scope
      comment: "Geographic scope of the crisis — supports regional crisis management analysis."
    - name: "regulatory_reporting_required_flag"
      expr: regulatory_reporting_required_flag
      comment: "Whether regulatory reporting is required — filters crises with compliance obligations."
    - name: "donor_notification_required_flag"
      expr: donor_notification_required_flag
      comment: "Whether donor notification is required — critical for grant compliance and donor relationship management."
    - name: "activation_month"
      expr: DATE_TRUNC('month', activation_date)
      comment: "Month of crisis activation — enables trend analysis of crisis frequency over time."
    - name: "post_crisis_review_status"
      expr: post_crisis_review_status
      comment: "Status of post-crisis review — tracks organizational learning completion."
  measures:
    - name: "total_crisis_activations"
      expr: COUNT(1)
      comment: "Total number of crisis communication activations. Volume baseline for organizational resilience and risk exposure assessment."
    - name: "donor_notification_compliance_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN donor_notification_required_flag = TRUE AND donor_notification_sent_date IS NOT NULL THEN 1 END) / NULLIF(COUNT(CASE WHEN donor_notification_required_flag = TRUE THEN 1 END), 0), 2)
      comment: "Percentage of crises requiring donor notification where notification was actually sent. Grant compliance KPI — failure to notify donors can trigger award suspension."
    - name: "regulatory_report_compliance_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN regulatory_reporting_required_flag = TRUE AND regulatory_report_submitted_date IS NOT NULL THEN 1 END) / NULLIF(COUNT(CASE WHEN regulatory_reporting_required_flag = TRUE THEN 1 END), 0), 2)
      comment: "Percentage of crises requiring regulatory reporting where report was submitted. Compliance KPI — non-compliance risks statutory penalties and donor audit findings."
    - name: "post_crisis_review_completion_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN post_crisis_review_status = 'completed' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of crisis activations with completed post-crisis reviews. Organizational learning KPI — low rates indicate failure to capture lessons learned."
    - name: "key_messages_approval_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN key_messages_approved IS NOT NULL AND key_messages_approved != '' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of crises where key messages were formally approved before release. Communications governance KPI — unapproved messaging creates reputational risk."
    - name: "active_crisis_count"
      expr: COUNT(CASE WHEN crisis_communication_status = 'active' THEN 1 END)
      comment: "Number of currently active crisis communications. Real-time operational load metric for crisis management team capacity planning."
    - name: "avg_crisis_duration_days"
      expr: AVG(DATEDIFF(deactivation_date, activation_date))
      comment: "Average duration of crisis communications in days. Operational efficiency metric — longer durations indicate more complex or poorly managed crises."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_digital_content`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Digital content performance KPIs tracking reach, engagement, brand compliance, and accessibility across all digital channels. Informs content strategy and platform investment decisions. Source systems: social media management platforms (Hootsuite, Sprout Social), CMS platforms, and digital analytics tools."
  source: "`vibe_ngo_v1`.`communication`.`digital_content`"
  dimensions:
    - name: "content_type"
      expr: content_type
      comment: "Type of digital content (e.g. blog, video, social post, infographic) — primary grouping for content portfolio analysis."
    - name: "platform"
      expr: platform
      comment: "Digital platform where content is published (e.g. Facebook, Twitter, website) — enables platform-level performance comparison."
    - name: "content_status"
      expr: content_status
      comment: "Current status of content (e.g. published, draft, archived) — filters live vs. pipeline content."
    - name: "language_code"
      expr: language_code
      comment: "Language of the content — supports multilingual content strategy analysis."
    - name: "is_brand_compliant"
      expr: is_brand_compliant
      comment: "Whether content meets brand guidelines — compliance quality filter."
    - name: "is_accessibility_compliant"
      expr: is_accessibility_compliant
      comment: "Whether content meets accessibility standards — inclusivity compliance indicator."
    - name: "publish_month"
      expr: DATE_TRUNC('month', actual_publish_timestamp)
      comment: "Month content was published — enables trend analysis of content output and performance."
    - name: "moderation_status"
      expr: moderation_status
      comment: "Content moderation status — flags content pending review or flagged for issues."
  measures:
    - name: "total_content_pieces"
      expr: COUNT(1)
      comment: "Total digital content pieces. Volume baseline for content production capacity and pipeline management."
    - name: "total_impressions"
      expr: SUM(CAST(impressions_count AS DOUBLE))
      comment: "Total impressions across all digital content. Top-of-funnel reach metric for brand awareness and campaign visibility."
    - name: "total_reach"
      expr: SUM(CAST(reach_count AS DOUBLE))
      comment: "Total unduplicated reach across digital content. Audience penetration metric — key for donor and beneficiary awareness campaigns."
    - name: "total_video_views"
      expr: SUM(CAST(video_views_count AS DOUBLE))
      comment: "Total video views across all video content. Engagement depth metric — video is typically the highest-engagement content format."
    - name: "total_engagement_actions"
      expr: SUM(CAST(engagement_likes_count AS DOUBLE) + CAST(engagement_comments_count AS DOUBLE) + CAST(engagement_shares_count AS DOUBLE))
      comment: "Total engagement actions (likes + comments + shares) across all content. Composite engagement volume metric for content effectiveness."
    - name: "avg_engagement_per_piece"
      expr: AVG(CAST(engagement_likes_count AS DOUBLE) + CAST(engagement_comments_count AS DOUBLE) + CAST(engagement_shares_count AS DOUBLE))
      comment: "Average total engagement actions per content piece. Content quality benchmark — low averages trigger content strategy review."
    - name: "brand_compliance_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_brand_compliant = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of content pieces meeting brand guidelines. Brand governance KPI — non-compliant content creates reputational risk."
    - name: "accessibility_compliance_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_accessibility_compliant = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of content meeting accessibility standards. Inclusivity and legal compliance KPI — critical for organizations serving persons with disabilities."
    - name: "avg_click_through_count"
      expr: AVG(CAST(click_through_count AS DOUBLE))
      comment: "Average click-through count per content piece. Content conversion effectiveness metric — drives website traffic and donation page visits."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_donor_stewardship_touchpoint`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Donor stewardship effectiveness KPIs tracking touchpoint volume, cost efficiency, sentiment, and follow-up compliance. Critical for major donor retention and grant relationship management. Source systems: Salesforce NPSP, Raisers Edge NXT, and relationship management platforms. NOTE: donor data carries PII sensitivity per VREQ-022."
  source: "`vibe_ngo_v1`.`communication`.`donor_stewardship_touchpoint`"
  dimensions:
    - name: "touchpoint_type"
      expr: touchpoint_type
      comment: "Type of stewardship touchpoint (e.g. impact report, site visit, thank-you call) — primary grouping for stewardship portfolio analysis."
    - name: "channel"
      expr: channel
      comment: "Communication channel used for stewardship (e.g. email, in-person, phone) — enables channel effectiveness comparison."
    - name: "donor_tier"
      expr: donor_tier
      comment: "Donor tier (e.g. major, mid-level, mass) — enables tier-differentiated stewardship analysis."
    - name: "touchpoint_status"
      expr: touchpoint_status
      comment: "Status of the touchpoint (e.g. completed, planned, overdue) — operational filter for pipeline management."
    - name: "country_code"
      expr: country_code
      comment: "Country of the stewardship touchpoint — supports geographic relationship management analysis."
    - name: "sdg_alignment"
      expr: sdg_alignment
      comment: "SDG alignment of the stewardship content — supports impact-linked donor reporting."
    - name: "touchpoint_month"
      expr: DATE_TRUNC('month', touchpoint_date)
      comment: "Month of touchpoint — enables trend analysis of stewardship activity cadence."
    - name: "compliance_review_status"
      expr: compliance_review_status
      comment: "Compliance review status of the touchpoint — flags touchpoints pending or failing compliance review."
  measures:
    - name: "total_stewardship_touchpoints"
      expr: COUNT(1)
      comment: "Total donor stewardship touchpoints. Volume baseline for stewardship program activity and relationship management capacity."
    - name: "total_stewardship_cost_usd"
      expr: SUM(CAST(cost_amount AS DOUBLE))
      comment: "Total cost of stewardship activities. Budget accountability metric for donor relations investment."
    - name: "avg_cost_per_touchpoint_usd"
      expr: AVG(CAST(cost_amount AS DOUBLE))
      comment: "Average cost per stewardship touchpoint. Efficiency benchmark — compared across channels and donor tiers to optimize stewardship investment."
    - name: "avg_sentiment_score"
      expr: AVG(CAST(sentiment_score AS DOUBLE))
      comment: "Average donor sentiment score across stewardship touchpoints. Relationship health KPI — declining sentiment predicts donor attrition and requires proactive intervention."
    - name: "avg_data_quality_score"
      expr: AVG(CAST(data_quality_score AS DOUBLE))
      comment: "Average data quality score of stewardship records. Data governance KPI — low scores indicate CRM hygiene issues affecting stewardship effectiveness."
    - name: "follow_up_overdue_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN follow_up_required_flag = TRUE AND follow_up_due_date < CURRENT_DATE() AND touchpoint_status != 'completed' THEN 1 END) / NULLIF(COUNT(CASE WHEN follow_up_required_flag = TRUE THEN 1 END), 0), 2)
      comment: "Percentage of required follow-ups that are past due. Relationship management SLA KPI — overdue follow-ups directly risk major donor retention."
    - name: "restricted_communication_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_restricted_communication = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of stewardship touchpoints flagged as restricted communications. Compliance risk indicator — high rates require additional oversight and donor condition review."
    - name: "unique_donors_stewarded"
      expr: COUNT(DISTINCT constituent_id)
      comment: "Number of distinct donors receiving stewardship touchpoints. Coverage metric — ensures major donor portfolio is being actively managed."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_email_broadcast`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Email broadcast performance and compliance KPIs tracking delivery rates, consent verification, and broadcast pipeline health. Source systems: Mailchimp, Salesforce Marketing Cloud, Constant Contact, and ESP platforms used by NGOs. NOTE: sender_name carries PII sensitivity tag pii_staff per VREQ-055."
  source: "`vibe_ngo_v1`.`communication`.`email_broadcast`"
  dimensions:
    - name: "broadcast_type"
      expr: broadcast_type
      comment: "Type of email broadcast (e.g. newsletter, appeal, transactional) — primary grouping for broadcast portfolio analysis."
    - name: "broadcast_status"
      expr: broadcast_status
      comment: "Current status of the broadcast (e.g. sent, scheduled, draft) — operational filter."
    - name: "esp_platform"
      expr: esp_platform
      comment: "Email service provider platform used — enables platform performance comparison."
    - name: "language_code"
      expr: language_code
      comment: "Language of the broadcast — supports multilingual campaign analysis."
    - name: "country_code"
      expr: country_code
      comment: "Country of the broadcast — enables geographic performance analysis."
    - name: "compliance_check_status"
      expr: compliance_check_status
      comment: "Status of compliance check (e.g. passed, failed, pending) — critical for regulatory compliance monitoring."
    - name: "send_month"
      expr: DATE_TRUNC('month', send_date)
      comment: "Month broadcast was sent — enables trend analysis of email program activity."
    - name: "is_ab_test"
      expr: is_ab_test
      comment: "Whether the broadcast is an A/B test — segments optimization experiments from standard sends."
  measures:
    - name: "total_broadcasts"
      expr: COUNT(1)
      comment: "Total email broadcasts sent. Volume baseline for email program activity and capacity."
    - name: "consent_verified_broadcast_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN consent_verified = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of broadcasts where consent was verified before sending. Critical compliance KPI — unverified consent broadcasts create GDPR and CAN-SPAM liability."
    - name: "compliance_pass_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN compliance_check_status = 'passed' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of broadcasts passing compliance checks. Governance KPI — failed compliance checks must be resolved before broadcast deployment."
    - name: "ab_test_adoption_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_ab_test = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of broadcasts using A/B testing. Optimization maturity KPI — low rates indicate missed opportunities for evidence-based message improvement."
    - name: "total_broadcasts_with_consent_verified"
      expr: COUNT(CASE WHEN consent_verified = TRUE THEN 1 END)
      comment: "Absolute count of broadcasts with verified consent. Compliance baseline count for audit reporting."
    - name: "unique_segments_targeted"
      expr: COUNT(DISTINCT segment_id)
      comment: "Number of distinct audience segments targeted across broadcasts. Segmentation sophistication metric — broader segmentation indicates more personalized communication strategy."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_feedback_case`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Accountability to affected populations (AAP) KPIs tracking feedback case volume, resolution rates, SLA compliance, and escalation patterns. Critical for CHS commitments, donor accountability reporting, and organizational learning. Source systems: KoboToolbox, Commcare, UNHCR PRIMES, and custom feedback management systems."
  source: "`vibe_ngo_v1`.`communication`.`feedback_case`"
  dimensions:
    - name: "case_type"
      expr: case_type
      comment: "Type of feedback case (e.g. complaint, suggestion, query) — primary grouping for feedback portfolio analysis."
    - name: "case_category"
      expr: case_category
      comment: "Category of the feedback case — enables thematic analysis of community concerns."
    - name: "case_status"
      expr: case_status
      comment: "Current status of the case (e.g. open, resolved, escalated) — operational filter for pipeline management."
    - name: "priority_level"
      expr: priority_level
      comment: "Priority level of the case — enables SLA-tiered performance analysis."
    - name: "submission_channel"
      expr: submission_channel
      comment: "Channel through which feedback was submitted (e.g. hotline, in-person, digital) — informs channel accessibility analysis."
    - name: "escalation_tier"
      expr: escalation_tier
      comment: "Escalation tier of the case — tracks severity distribution of feedback portfolio."
    - name: "is_sensitive"
      expr: is_sensitive
      comment: "Whether the case is flagged as sensitive — critical filter for safeguarding and protection case analysis."
    - name: "received_month"
      expr: DATE_TRUNC('month', received_date)
      comment: "Month feedback was received — enables trend analysis of feedback volume and patterns."
  measures:
    - name: "total_feedback_cases"
      expr: COUNT(1)
      comment: "Total feedback cases received. Volume baseline for AAP accountability and CHS compliance reporting."
    - name: "case_resolution_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN case_status = 'resolved' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of feedback cases resolved. Core AAP KPI — low resolution rates indicate systemic accountability failures requiring leadership intervention."
    - name: "anonymous_case_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_anonymous = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of cases submitted anonymously. Trust indicator — high anonymous rates suggest fear of retaliation and weak community trust in feedback mechanisms."
    - name: "sensitive_case_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_sensitive = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of cases flagged as sensitive. Risk indicator — high rates may signal safeguarding or protection concerns requiring escalation."
    - name: "sla_breach_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN sla_due_date < CURRENT_DATE() AND case_status != 'resolved' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of open cases past SLA due date. Accountability SLA KPI — breaches directly violate CHS commitments and donor accountability requirements."
    - name: "avg_resolution_days"
      expr: AVG(DATEDIFF(resolved_date, received_date))
      comment: "Average days to resolve a feedback case. Operational efficiency and accountability KPI — benchmarked against CHS and donor-mandated SLA targets."
    - name: "escalated_case_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN escalation_tier IS NOT NULL AND escalation_tier != '' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of cases requiring escalation. Quality and complexity indicator — high escalation rates signal frontline capacity or process gaps."
    - name: "unique_project_sites_with_feedback"
      expr: COUNT(DISTINCT project_site_id)
      comment: "Number of distinct project sites generating feedback cases. Coverage metric — sites with zero feedback may indicate inaccessible feedback mechanisms."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_impact_story`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Impact storytelling portfolio KPIs tracking consent compliance, publication readiness, sensitivity management, and donor visibility. Critical for donor reporting, fundraising communications, and beneficiary dignity standards. Source systems: content management systems, Salesforce NPSP, and field documentation platforms. NOTE: registrant_id links to beneficiary PII — anonymization_required flag must be enforced per VREQ-022."
  source: "`vibe_ngo_v1`.`communication`.`impact_story`"
  dimensions:
    - name: "story_type"
      expr: story_type
      comment: "Type of impact story (e.g. beneficiary story, community story, program story) — primary grouping for story portfolio analysis."
    - name: "approval_status"
      expr: approval_status
      comment: "Approval status of the story (e.g. approved, pending, rejected) — publication readiness filter."
    - name: "consent_status"
      expr: consent_status
      comment: "Consent status for story publication — critical compliance filter; stories without active consent must not be published."
    - name: "sensitivity_level"
      expr: sensitivity_level
      comment: "Sensitivity level of the story — determines publication restrictions and review requirements."
    - name: "country_code"
      expr: country_code
      comment: "Country of origin of the story — enables geographic portfolio analysis."
    - name: "donor_visibility"
      expr: donor_visibility
      comment: "Donor visibility level (e.g. public, restricted, confidential) — segments stories by donor reporting eligibility."
    - name: "thematic_area"
      expr: thematic_area
      comment: "Thematic area of the story (e.g. health, education, protection) — supports program-aligned storytelling analysis."
    - name: "publication_month"
      expr: DATE_TRUNC('month', publication_date)
      comment: "Month of story publication — enables trend analysis of storytelling output."
  measures:
    - name: "total_impact_stories"
      expr: COUNT(1)
      comment: "Total impact stories in the portfolio. Volume baseline for communications content pipeline management."
    - name: "consent_compliant_story_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN consent_status = 'active' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of stories with active consent. Critical compliance KPI — stories published without active consent violate beneficiary dignity standards and data protection law."
    - name: "anonymization_required_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN anonymization_required = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of stories requiring anonymization. Protection risk indicator — high rates in conflict/displacement contexts indicate elevated beneficiary safety requirements."
    - name: "embargo_active_count"
      expr: COUNT(CASE WHEN embargo_flag = TRUE AND embargo_until_date >= CURRENT_DATE() THEN 1 END)
      comment: "Number of stories currently under embargo. Publication pipeline metric — embargoed stories represent future communications capacity."
    - name: "translation_available_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN translation_available = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of stories available in translation. Multilingual accessibility KPI — low rates limit reach in non-English donor and beneficiary markets."
    - name: "protection_flagged_story_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN protection_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of stories with protection flags. Safeguarding KPI — protection-flagged stories require additional review before publication to prevent harm to subjects."
    - name: "approved_stories_count"
      expr: COUNT(CASE WHEN approval_status = 'approved' THEN 1 END)
      comment: "Number of approved stories ready for publication. Content pipeline readiness metric for communications planning."
    - name: "consent_expiring_90d_count"
      expr: COUNT(CASE WHEN consent_expiry_date <= DATE_ADD(CURRENT_DATE(), 90) AND consent_status = 'active' THEN 1 END)
      comment: "Number of stories with consent expiring within 90 days. Proactive compliance risk metric — triggers consent renewal outreach to prevent publication suspension."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_media_activity`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Media relations performance KPIs tracking media value, reach, sentiment, and pickup rates across press releases, interviews, and media engagements. Source systems: media monitoring platforms (Meltwater, Cision), PR management tools, and communications tracking systems used by INGOs."
  source: "`vibe_ngo_v1`.`communication`.`media_activity`"
  dimensions:
    - name: "activity_type"
      expr: activity_type
      comment: "Type of media activity (e.g. press release, interview, media briefing) — primary grouping for media portfolio analysis."
    - name: "outlet_type"
      expr: outlet_type
      comment: "Type of media outlet (e.g. print, broadcast, digital, wire) — enables channel-level media performance analysis."
    - name: "media_activity_status"
      expr: media_activity_status
      comment: "Status of the media activity (e.g. published, pending, cancelled) — operational filter."
    - name: "sentiment"
      expr: sentiment
      comment: "Sentiment of media coverage (e.g. positive, neutral, negative) — critical for reputational risk monitoring."
    - name: "geographic_market"
      expr: geographic_market
      comment: "Geographic market of the media activity — enables regional media presence analysis."
    - name: "language"
      expr: language
      comment: "Language of the media activity — supports multilingual media strategy analysis."
    - name: "publication_month"
      expr: DATE_TRUNC('month', publication_date)
      comment: "Month of publication — enables trend analysis of media coverage volume and quality."
    - name: "sdg_alignment"
      expr: sdg_alignment
      comment: "SDG alignment of the media activity — supports impact-linked communications reporting."
  measures:
    - name: "total_media_activities"
      expr: COUNT(1)
      comment: "Total media activities. Volume baseline for media relations program activity."
    - name: "total_media_value_usd"
      expr: SUM(CAST(media_value_usd AS DOUBLE))
      comment: "Total earned media value in USD. ROI metric for communications investment — benchmarks PR effectiveness against paid media costs."
    - name: "total_reach_estimate"
      expr: SUM(CAST(reach_estimate AS DOUBLE))
      comment: "Total estimated audience reach across media activities. Brand awareness metric — key for donor acquisition and public advocacy campaigns."
    - name: "total_circulation_estimate"
      expr: SUM(CAST(circulation_estimate AS DOUBLE))
      comment: "Total circulation estimate across media outlets. Audience exposure metric for print and broadcast media."
    - name: "avg_media_value_per_activity_usd"
      expr: AVG(CAST(media_value_usd AS DOUBLE))
      comment: "Average earned media value per activity. Efficiency benchmark for media relations investment."
    - name: "negative_sentiment_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN sentiment = 'negative' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of media activities with negative sentiment. Reputational risk KPI — rising negative sentiment triggers crisis communications review."
    - name: "positive_sentiment_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN sentiment = 'positive' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of media activities with positive sentiment. Brand health KPI — tracked at board level for organizational reputation management."
    - name: "beneficiary_feedback_coverage_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN beneficiary_feedback_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of media activities incorporating beneficiary feedback. Accountability and dignity KPI — measures whether affected populations have voice in external communications."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_media_contact`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Media contact database quality and relationship KPIs tracking engagement rates, influence scores, and list health. Informs media relations strategy and contact database investment. Source systems: Cision, Meltwater, and custom media contact management systems. NOTE: first_name, last_name, full_name, primary_email, mobile_number, phone_number carry PII sensitivity tags per VREQ-022."
  source: "`vibe_ngo_v1`.`communication`.`media_contact`"
  dimensions:
    - name: "outlet_type"
      expr: outlet_type
      comment: "Type of media outlet (e.g. print, broadcast, digital) — primary grouping for contact portfolio analysis."
    - name: "relationship_tier"
      expr: relationship_tier
      comment: "Relationship tier with the media contact (e.g. tier 1, tier 2) — enables tiered engagement strategy analysis."
    - name: "record_status"
      expr: record_status
      comment: "Status of the contact record (e.g. active, inactive, blacklisted) — data quality filter."
    - name: "primary_language"
      expr: primary_language
      comment: "Primary language of the media contact — supports multilingual media relations planning."
    - name: "geographic_coverage"
      expr: geographic_coverage
      comment: "Geographic coverage area of the media contact — enables regional media relations analysis."
    - name: "opt_in_status"
      expr: opt_in_status
      comment: "Whether the contact has opted in to communications — compliance filter for GDPR-compliant media outreach."
    - name: "blacklist_status"
      expr: blacklist_status
      comment: "Whether the contact is blacklisted — critical filter to prevent inappropriate outreach."
  measures:
    - name: "total_media_contacts"
      expr: COUNT(1)
      comment: "Total media contacts in the database. Volume baseline for media relations reach capacity."
    - name: "active_opted_in_contacts"
      expr: COUNT(CASE WHEN opt_in_status = TRUE AND record_status = 'active' AND blacklist_status = FALSE THEN 1 END)
      comment: "Number of active, opted-in, non-blacklisted media contacts. Addressable media list size — the true reachable media audience for compliant outreach."
    - name: "blacklist_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN blacklist_status = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of contacts on the blacklist. List health KPI — high rates indicate relationship management issues or data quality problems."
    - name: "avg_influence_score"
      expr: AVG(CAST(influence_score AS DOUBLE))
      comment: "Average influence score across media contacts. Portfolio quality metric — higher scores indicate stronger media relationships with high-reach journalists."
    - name: "avg_data_quality_score"
      expr: AVG(CAST(data_quality_score AS DOUBLE))
      comment: "Average data quality score of media contact records. CRM hygiene KPI — low scores indicate stale or incomplete contact data reducing outreach effectiveness."
    - name: "recently_engaged_contact_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN last_engagement_date >= DATE_ADD(CURRENT_DATE(), -180) THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of contacts engaged in the last 180 days. Relationship activity KPI — low rates indicate dormant media relationships requiring reactivation."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_message_thread`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Constituent communication thread management KPIs tracking resolution rates, response times, complaint handling, and SLA compliance. Source systems: Zendesk, Salesforce Service Cloud, and constituent relationship management platforms."
  source: "`vibe_ngo_v1`.`communication`.`message_thread`"
  dimensions:
    - name: "thread_type"
      expr: thread_type
      comment: "Type of message thread (e.g. inquiry, complaint, support) — primary grouping for thread portfolio analysis."
    - name: "thread_status"
      expr: thread_status
      comment: "Current status of the thread (e.g. open, closed, escalated) — operational filter for pipeline management."
    - name: "communication_channel"
      expr: communication_channel
      comment: "Channel of the thread (e.g. email, chat, phone) — enables channel-level performance analysis."
    - name: "escalation_level"
      expr: escalation_level
      comment: "Escalation level of the thread — tracks severity distribution of communication issues."
    - name: "priority_level"
      expr: priority_level
      comment: "Priority level of the thread — enables SLA-tiered performance analysis."
    - name: "country_code"
      expr: country_code
      comment: "Country of the thread — supports geographic communication management analysis."
    - name: "is_complaint"
      expr: is_complaint
      comment: "Whether the thread is a complaint — critical filter for complaint management KPIs."
    - name: "initiated_month"
      expr: DATE_TRUNC('month', initiated_timestamp)
      comment: "Month thread was initiated — enables trend analysis of communication volume."
  measures:
    - name: "total_message_threads"
      expr: COUNT(1)
      comment: "Total message threads. Volume baseline for constituent communication management capacity."
    - name: "thread_resolution_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN thread_status = 'closed' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of message threads resolved. Service quality KPI — low resolution rates indicate constituent service capacity or process gaps."
    - name: "complaint_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_complaint = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of threads that are complaints. Constituent satisfaction risk indicator — rising complaint rates trigger service quality review."
    - name: "avg_sentiment_score"
      expr: AVG(CAST(sentiment_score AS DOUBLE))
      comment: "Average sentiment score across message threads. Constituent relationship health KPI — declining sentiment predicts increased complaints and attrition."
    - name: "sla_breach_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN response_due_date < CURRENT_DATE() AND thread_status != 'closed' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of open threads past response due date. SLA compliance KPI — breaches directly impact constituent satisfaction and accountability commitments."
    - name: "confidential_thread_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN is_confidential = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of threads flagged as confidential. Data protection and sensitivity management KPI — high rates require enhanced access controls."
    - name: "avg_resolution_days"
      expr: AVG(DATEDIFF(resolution_timestamp, initiated_timestamp))
      comment: "Average days to resolve a message thread. Operational efficiency KPI — benchmarked against service level commitments."
    - name: "unique_constituents_in_threads"
      expr: COUNT(DISTINCT constituent_id)
      comment: "Number of distinct constituents with active message threads. Engagement breadth metric for constituent service capacity planning."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_plan`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Communication plan portfolio KPIs tracking budget allocation, plan approval rates, and pipeline health. Supports communications directors in managing annual and campaign-level communication planning. Source systems: internal planning tools, Salesforce, and project management platforms."
  source: "`vibe_ngo_v1`.`communication`.`plan`"
  dimensions:
    - name: "plan_type"
      expr: plan_type
      comment: "Type of communication plan (e.g. annual, campaign, crisis) — primary grouping for plan portfolio analysis."
    - name: "plan_status"
      expr: plan_status
      comment: "Current status of the plan (e.g. active, draft, closed) — operational filter for pipeline management."
    - name: "approval_status"
      expr: approval_status
      comment: "Approval status of the plan — governance filter for approved vs. pending plans."
    - name: "frequency"
      expr: frequency
      comment: "Frequency of communication activities in the plan (e.g. weekly, monthly) — informs cadence planning."
    - name: "currency_code"
      expr: currency_code
      comment: "Currency of the plan budget — required for multi-currency budget consolidation."
    - name: "plan_start_month"
      expr: DATE_TRUNC('month', start_date)
      comment: "Month the plan starts — enables trend analysis of plan pipeline over time."
  measures:
    - name: "total_plans"
      expr: COUNT(1)
      comment: "Total communication plans. Volume baseline for communications planning portfolio management."
    - name: "total_budget_amount"
      expr: SUM(CAST(budget_amount AS DOUBLE))
      comment: "Total budget allocated across all communication plans. Financial planning KPI for communications investment oversight."
    - name: "avg_budget_per_plan"
      expr: AVG(CAST(budget_amount AS DOUBLE))
      comment: "Average budget per communication plan. Benchmarks investment levels across plan types and periods."
    - name: "approved_plan_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN approval_status = 'approved' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of plans with approved status. Governance KPI — low approval rates indicate bottlenecks in communications planning process."
    - name: "active_plan_budget_total"
      expr: SUM(CASE WHEN plan_status = 'active' THEN budget_amount ELSE 0 END)
      comment: "Total budget across currently active communication plans. Current-period financial commitment metric for budget management."
    - name: "unique_country_offices_with_plans"
      expr: COUNT(DISTINCT country_office_id)
      comment: "Number of distinct country offices with communication plans. Geographic coverage metric — offices without plans may lack structured communications capacity."
$$;

CREATE OR REPLACE VIEW `vibe_ngo_v1`.`_metrics`.`communication_campaign_media_outreach`
WITH METRICS
LANGUAGE YAML
AS $$
  version: 1.1
  comment: "Campaign media outreach effectiveness KPIs tracking response rates, coverage conversion, and follow-up compliance. Informs media relations strategy for advocacy campaigns. Source systems: PR management platforms, Cision, and campaign tracking tools."
  source: "`vibe_ngo_v1`.`communication`.`campaign_media_outreach`"
  dimensions:
    - name: "outreach_status"
      expr: outreach_status
      comment: "Status of the media outreach (e.g. sent, responded, no response) — primary grouping for outreach pipeline analysis."
    - name: "coverage_type"
      expr: coverage_type
      comment: "Type of media coverage achieved (e.g. article, interview, mention) — segments coverage quality."
    - name: "contact_role"
      expr: contact_role
      comment: "Role of the media contact in the outreach (e.g. journalist, editor) — enables role-level effectiveness analysis."
    - name: "engagement_month"
      expr: DATE_TRUNC('month', engagement_date)
      comment: "Month of media engagement — enables trend analysis of outreach activity."
    - name: "embargo_agreement_flag"
      expr: embargo_agreement_flag
      comment: "Whether an embargo agreement is in place — compliance filter for embargoed outreach."
  measures:
    - name: "total_outreach_activities"
      expr: COUNT(1)
      comment: "Total media outreach activities. Volume baseline for media relations program activity."
    - name: "response_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN response_received_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of media outreach activities receiving a response. Core media relations effectiveness KPI — low rates indicate weak media relationships or poor pitch relevance."
    - name: "interview_conversion_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN interview_granted_flag = TRUE THEN 1 END) / NULLIF(COUNT(CASE WHEN response_received_flag = TRUE THEN 1 END), 0), 2)
      comment: "Percentage of responses that converted to an interview. Media relations quality KPI — measures ability to convert media interest into substantive coverage opportunities."
    - name: "follow_up_required_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN follow_up_required_flag = TRUE THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of outreach activities requiring follow-up. Pipeline management KPI — high rates indicate media contacts needing additional nurturing."
    - name: "coverage_achieved_rate"
      expr: ROUND(100.0 * COUNT(CASE WHEN coverage_url IS NOT NULL AND coverage_url != '' THEN 1 END) / NULLIF(COUNT(1), 0), 2)
      comment: "Percentage of outreach activities resulting in published coverage. Ultimate media relations effectiveness KPI — measures conversion from outreach to actual media coverage."
$$;